### ISSUE TITLE
Resumable upload to fb page returns error "There was a problem uploading your video. Please try again." code : 6001

### ISSUE THREAD

**Issue by sai905905** [facebook/php-graph-sdk#1000]
try {
            $response = $fb->uploadVideo('me', $videoPath, $data, $token);

        } catch (FacebookResponseException $e) {

            // When Graph returns an error
            return 'error_code-'. $e->getCode() . ' ' . $e->getMessage();

        } catch (FacebookSDKException $e) {

            // When validation fails or other local issues
            return 'error_code-'. $e->getCode() . ' ' . $e->getMessage();

        }

********************* SDK RESUMABLE UPLOAD CODE********************

public function uploadVideo($target, $pathToFile, $metadata = [], $accessToken = null, $maxTransferTries = 5, $graphVersion = null)
    {
        $accessToken = $accessToken ?: $this->defaultAccessToken;
        $graphVersion = $graphVersion ?: $this->defaultGraphVersion;

        $uploader = new FacebookResumableUploader($this->app, $this->client, $accessToken, $graphVersion);
        $endpoint = '/'.$target.'/videos';
        $file = $this->videoToUpload($pathToFile);
        $chunk = $uploader->start($endpoint, $file);

        do {
            $chunk = $this->maxTriesTransfer($uploader, $endpoint, $chunk, $maxTransferTries);
        } while (!$chunk->isLastChunk());

        return [
          'video_id' => $chunk->getVideoId(),
          'success' => $uploader->finish($endpoint, $chunk->getUploadSessionId(), $metadata),
        ];
    }

**Comment by nasy** [comment]
Any updates on this? I am having the same issue, sometimes upload works sometimes it fails. No apparent reason. 

¯\_(ツ)_/¯

**Comment by phaizullin** [comment]
#1001 this is fix of your problem

**Comment by yguedidi** [comment]
@sai905905 @nasy I just answered there: https://github.com/facebook/php-graph-sdk/issues/1012#issuecomment-397869019
