### ISSUE TITLE
Graph returned an error using graph version v2.10 and Facebook SDK for PHP 5.X

### ISSUE THREAD

**Issue by milap-virtueinfo** [facebook/php-graph-sdk#1002]
Hello 

I have integrated facebook social login button for my one project. Earlier it was using graph version v2.2 and everything works fine, But facebook no longer supported to version v2.2.
So I have upgraded it to v2.10.

But it seems when I logged in using facebook the callback popup automatic gets close.
And my login flow gets disturbed.

I have used https://github.com/facebook/php-graph-sdk code, when I executed code of exception It shows me following error(unreadable).

Graph returned an error: URL àª²à«‹àª¡ àª•àª°à«€ àª¶àª•àª¤àª¾àª‚ àª¨àª¥à«€: àª† URL àª¨à«€ àª¡à«‹àª®à«‡àª¨ àªàªªà«àª²àª¿àª•à«‡àª¶àª¨ àª¡à«‹àª®à«‡àª¨à«àª¸àª®àª¾àª‚ àª¸àª®àª¾àªµà«‡àª² àª¨àª¥à«€. àª† URL àª²à«‹àª¡ àª•àª°àªµàª¾, àª¤àª®àª¾àª°à«€ àªàªªà«àª²àª¿àª•à«‡àª¶àª¨ àª¸à«‡àªŸàª¿àª‚àª—à«àª¸àª®àª¾àª‚ àª¬àª§àª¾ àª¡à«‹àª®à«‡àª¨à«àª¸ àª…àª¨à«‡ àªàªªà«àª²àª¿àª•à«‡àª¶àª¨ àª¡à«‹àª®à«‡àª¨à«àª¸ àª•à«àª·à«‡àª¤à«àª° àª®àª¾àªŸà«‡ àª¤àª®àª¾àª°à«€ àªàªªà«àª²àª¿àª•à«‡àª¶àª¨ àª¸àª¬àª¡à«‹àª®à«‡àª¨à«àª¸ àª‰àª®à«‡àª°àªµàª¾ àª®àª¾àªŸà«‡ àª¸àª®àª°à«àª¥ àª¹à«‹àª¯ àª›à«‡.

Can any one let me know how can I debug error in readable format?
Or is there anything missing in https://github.com/facebook/php-graph-sdk code?

**Comment by yguedidi** [comment]
@milap-virtueinfo thanks for posting your issue here! Unfortunatly, it looks like a usage issue more than an SDK issue. You should check the changelog of the Graph API from 2.2 to 2.10, or ask for help on StackOverflow
