### ISSUE TITLE
Getting List of Accounts (Pages) & Page Access Token?

### ISSUE THREAD

**Issue by sagargulati** [facebook/php-graph-sdk#1003]
Greetings,

I was wondering Is there any inbuilt function to get a list of accounts or **pages (business)** with **ID, Name** that can be used to list the pages in a dashboard scenario where user selects a particular page and then it get's the page access token and that can be used with **Instagram Business API** to get other details and perform actions on **Instagram** mainly [these](https://developers.facebook.com/docs/instagram-api/business-discovery) available in the docs?

I know about `/me/accounts` but that shows a lot of complex data, I'm looking for a example code or solution that could help.

Also does the SDK support **Instagram Graph API**? If yes, how can we use it?

Thanks!

**Comment by yguedidi** [comment]
Thank you for using the Facebook PHP SDK!

If you need help about using it, you should ask your questions on [StackOverflow](https://stackoverflow.com/) and tag them with the `facebook-php-sdk` tag.

So I'm closing this, but if you found a bug in the SDK or think about a feature, feel free to open a new GitHub issues.
