### ISSUE TITLE
Graph returned an error: Can't Load URL: The domain of this URL isn't included in the app's domains. To be able to load this URL, add all domains and subdomains of your app to the App Domains field in your app settings.

### ISSUE THREAD

**Issue by Gangababu93** [facebook/php-graph-sdk#1004]
Hello

I have integrated facebook social login button in on of my project. Earlier it was using graph version v2.2 and everything works fine.But now it is throwing an error "Graph returned an error: Can't Load URL: The domain of this URL isn't included in the app's domains. To be able to load this URL, add all domains and subdomains of your app to the App Domains field in your app settings".
Even though we have matched the domains of my website and in facebook app settings.
This error comes when we filled up the login username and password, page redirects to new page saying above error
And my login flow gets disturbed.

**Comment by Arkellys** [comment]
Hello @Gangababu93,

Did you add 'Facebook Login' product in your app settings ?
If so, make sure that you added your callback url in the 'Valid OAuth redirect URIs' field of Facebook Login settings.

Adding the callback to the `getAccessToken()` function can help too : 
`$helper->getAccessToken($callbackUrl);`

**Comment by yguedidi** [comment]
Closing as @Arkellys answered to it, thanks for that! If you need more help @Gangababu93, please check StackOverflow
