### ISSUE TITLE
getLoginUrl is asking for more permissions  than requested

### ISSUE THREAD

**Issue by eakbas** [facebook/php-graph-sdk#1009]
I'm using v5.6.2 and my code is this: 

```
$permissions = ['email'];
$loginUrl = $helper->getLoginUrl(base_url() . '/account/connect_facebook2/fbcallback', $permissions);
```
Although I am only asking for the user's e-mail, I get the following message from Facebook: 

"<my-app> will receive: your name and profile picture, friend list, birthday, current city, photos, videos and email address."  with the following warning: 

"Submit for Login Review. Some of the permissions below have not been approved for use by Facebook.
Submit for review now or learn more. " 

What could be wrong?

**Comment by yguedidi** [comment]
@eakbas thanks for posting you issue here! To answer your last question, I think for sure that it's not the SDK that can be wrong, it's an issue that was never reported, so I'd guess it's something in your code.
Please ask StackOverflow for more help. I'm then closing this.
