### ISSUE TITLE
facebook php sdk not returning page rating review id

### ISSUE THREAD

**Issue by ashutoshtiwari22** [facebook/php-graph-sdk#1010]
When we calling the page ratings  fields "open_graph_story" from Facebook graph api then it is returning page ratings id but when we are calling from php sdk then it is coming as blank not returning  rating id so can not reply from api.
Please let me now if there is any other information I can provide. Thank you for your help.

**Comment by yguedidi** [comment]
@ashutoshtiwari22 thanks for posting your issue here!
Is this issue the same than #700 ?
Could you try its fix in #817 and tell us if it works? thanks

**Comment by ashutoshtiwari22** [comment]
@yguedidi Thanks, issue solved
