### ISSUE TITLE
Problems trying to upload heavy videos (2 min, 300MB aprox) by chunks

### ISSUE THREAD

**Issue by nasy** [facebook/php-graph-sdk#1012]
I am having problems trying to upload heavy videos by chunks (2 min, 300MB aprox). Video fails while in the middle of the uploading process.

With smaller size videos it works fine.

This is the code from the SDK that I am using:

SDK Version is
   "facebook/graph-sdk": "5.6.2"

    $response = $this->_facebookConnection->uploadVideo(
        $facebookPageId,
        $localPath,
        [
        'title' => '',
        'description' => 'TEST'
        ],
        $accessToken
    );
Any ideas what can be happening? We have been dealing with this issues with this for a while now.

Thanks!

This is the debug stack trace:

STARTING...

CHUNK...CHUNK...CHUNK...CHUNK...CHUNK...CHUNK...CHUNK...CHUNK...CHUNK...CHUNK...CHUNK...CHUNK...CHUNK...CHUNK...CHUNK...CHUNK...CHUNK...CHUNK...CHUNK...CHUNK...CHUNK..

.ERRROR !

There was a problem uploading your video. Please try again.
CODE 600
SUBCODE 1363037

{"error":{"message":"There was a problem uploading your video. Please try again.","type":"OAuthException","code":6001,"error_data":{"start_offset":95420416,"end_offset":100663296},"error_subcode":1363037,"is_transient":false,"error_user_title":"Error Uploading Video","error_user_msg":"There was a problem uploading your video. Please try uploading it again.","fbtrace_id":"CZSLYkPN90q"}}

ERRROR !
There was a problem uploading your video. Please try again.
CODE 600
SUBCODE 1363037

{"error":{"message":"There was a problem uploading your video. Please try again.","type":"OAuthException","code":6001,"error_data":{"start_offset":95420416,"end_offset":100663296},"error_subcode":1363037,"is_transient":false,"error_user_title":"Error Uploading Video","error_user_msg":"There was a problem uploading your video. Please try uploading it again.","fbtrace_id":"AGSPyDDIl5G"}}
ERRROR !
There was a problem uploading your video. Please try again.
CODE 600
SUBCODE 1363037

{"error":{"message":"There was a problem uploading your video. Please try again.","type":"OAuthException","code":6001,"error_data":{"start_offset":95420416,"end_offset":100663296},"error_subcode":1363037,"is_transient":false,"error_user_title":"Error Uploading Video","error_user_msg":"There was a problem uploading your video. Please try uploading it again.","fbtrace_id":"G1uYSi6PfzN"}}
ERRROR !
There was a problem uploading your video. Please try again.
CODE 600
SUBCODE 1363037

.....

.....

10 times
Fail!

**Comment by phaizullin** [comment]
#1000 this is fix of your problem

**Comment by yguedidi** [comment]
@nasy thanks for posting your issue here!
By uploading by chunks, you could expect errors, and it's the responsability of your code to properly handle those errors (that why the API is called "Resumable Upload" haha).
So just catch that exception in your code and do what the error message suggest: try again ;)
So I'm closing this.

**Comment by nasy** [comment]
@yguedidi Thanks for your answer.

 However, I don't know how to resume the upload if I do not have the start_offset and end_offset in the uploadVideo response.  All I have is an exception "There was a problem uploading your video. Please try again." and nothing else. (I got the full error code by debugging FacebookResumableUploader.php)

 However, I think @phaizullin is right about this fix:
https://github.com/facebook/php-graph-sdk/pull/1001
