### ISSUE TITLE
[6.0] Batch Request support for omit_response_on_success

### ISSUE THREAD

**Issue by sudsy** [facebook/php-graph-sdk#438]
Support should be added for omit_response_on_success

I propose the the following syntax:

``` php
  $requests = [
    'get-friends' => $fb->request('GET', 'me/friends?limit=5', ['omit_response_on_success' => false]),
    'friends' => $fb->request('GET', '?ids={result=get-friends:$.data.*.id}')
  ];

$responses = $fb->sendBatchRequest($requests)->getResponses();
```

**Comment by SammyK** [comment]
Thanks for the API suggestion @sudsy!

The `omit_response_on_success` option is unique to batch requests and exists outside of the params for the request it's sending.

```
POST /

batch=[{ "method":"GET","relative_url":"me/friends?limit=5","omit_response_on_success":false}]
```

The `$fb->request()` method generates a `FacebookRequest` which shouldn't concern itself with batch request options.

So the batch options need to exist on the `FacebookBatchRequest` entity & it's factories. Perhaps adding a factory for generating a `FacebookBatchRequest` entity and adding the batch options to the `FacebookBatchRequest::add()` method:

```
$myFriendsListRequest = $fb->request('GET', 'me/friends?limit=5');
$friendsRequest = $fb->request('GET', '?ids={result=get-friends:$.data.*.id}');

$batch = $fb->newBatchRequest();
$batch->add($myFriendsListRequest, $name = null, ['omit_response_on_success' => false]);
$batch->add($friendsRequest);

$res = $fb->getClient()->sendBatchRequest($batch);
```

Thoughts?

**Comment by sudsy** [comment]
Looks like a more logical approach to me.

I probably won't have time to implement it though. I don't use this sdk very often and just submitted the pr because I had to make the change for my own needs.

I am guessing that the line

```
$batch->add($myFriendsListRequest, $name = null, ['omit_response_on_success' => false]);
```
needs to change to 
```
$batch->add($myFriendsListRequest, 'get-friends', ['omit_response_on_success' => false]);
```
Otherwise, all good.

**Comment by SammyK** [comment]
> I probably won't have time to implement it though.

No worries. We can add this to the growing TODO list for v5/6. :)

> needs to change to

Indeed you'd need to change it to match your example. :)

**Comment by facebook-github-bot-0** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by SammyK** [comment]
Feature added in #713. :)

**Comment by khiemtranthien** [comment]
For "facebook/graph-sdk: "5.5.0", "facebook/php-ads-sdk" : "2.9.*", **name** and **omit_response_on_success** should be in an array.

`$batch->add($myFriendsListRequest, array('name' => 'get-friends', 'omit_response_on_success' => false));`
