### ISSUE TITLE
[6.0][Proposal] Remove Collection class

### ISSUE THREAD

**Issue by yguedidi** [facebook/php-graph-sdk#440]
A node is not a collection, an edge is.

Node:
- Counting fields of a node don't makes sense
- Traversing its fields too
- (ArrayAccess or not is not part of this issue)

Edge:
- Counting number of nodes of an edge makes sense
- Tranversing its nodes too
- ArrayAcces too (don't be surprizied here, I'm not against ArrayAccess, here it's a legitimate usage IMO :) )

I propose to "move" methods that have sense from Collection to GraphEdge and add missing ones to GraphNode

**Comment by devmsh** [comment]
Totally agreed :)

**Comment by SammyK** [comment]
:+1:

**Comment by yguedidi** [comment]
I'll send a preview PR soon

**Comment by devmsh** [comment]
I just realized that we may have some common functionality between edges and list fields https://github.com/facebook/facebook-php-sdk-v4/issues/401#issuecomment-102787044 ?

**Comment by yguedidi** [comment]
@devmsh I think all `list<type>` types are just arrays of `type`..

**Comment by devmsh** [comment]
Yes, and this is very close to the Edge?

We need to have the same API to deal with both edge or list fields?

> * Counting number of nodes of an edge makes sense
> * Tranversing its nodes too
> * ArrayAcces too

**Comment by yguedidi** [comment]
No, edges are paginated and can have extra data, lists are not IMO

**Comment by yguedidi** [comment]
PR opened: #443 :)

**Comment by devmsh** [comment]
I'm not saying that the `list fields` is sub type of `edges`, what I mean that both of them are collections and have many common functionality.

To make the question more clear, do we need to keep the `Collection` class and just remove it from the `GraphNode` so we can use it in both `GraphEdge` and `GraphListField` or we need to `implements \ArrayAccess, \Countable, \IteratorAggregate` in both of them to have some flexibility on changing the implementation for each of them?

**Comment by SammyK** [comment]
Good point @devmsh - I think the edges and `list<type>`'s could extend from a base collection class.

**Comment by devmsh** [comment]
While we may have another nodes - open graph node for example - it may be better to have the following:

General Collection and Item classes
Specific GraphEdge and GraphNode classes

It will remove the wrong dependencies and still allow for re-usability and will make GraphNode and GraphEdge code more clear?

**Comment by yguedidi** [comment]
@devmsh Just one question: What is the value of a `Collection` class over a simple array?
Look:
- `Countable`, `Traversable`, `ArrayAccess` are native with array!
- `$collection->all()`? Not needed!
- `$collection->asArray()`? Obvious! :)
- `$collection->map(function() {...})`? `array_map(function() {...}, $array)!
- `$collection->asJson()`? `json_encode($array)`!

Edges are also arrays in fact, but there have extra fields and pagination, that's why we need a dedicated class.

**Comment by yguedidi** [comment]
@SammyK @devmsh @gfosco I'm know that I want to change many (many) things about design/API of the current SDK.

@gfosco What do you decide, should we continue discuss about my thoughts and release a perfect 5.0 (perfect after we discuss, when we all agree, I can be wrong lol)? Or should we release current 5.0 and take time for all the refactoring?

**Comment by gfosco** [comment]
If they are just thoughts, we should get 5.0 out.  If it's a less than 1-week project, lets change things.

**Comment by yguedidi** [comment]
My answer: #447 :)

**Comment by devmsh** [comment]
`Collection` is not about pagination - if so, why the pagination code written in the `GraphEdge`?

`Array` and `Collection` is just a data structure that allow for storing multiple values, some languages like C# implement `Array` to has fixed length, while `Collection` size can be extended in the real time, in the other hand Java allow `Array` to save primitives while `Collection` can not do so!

So

1. `Collection` is just a data structure and must be separated from any dedicated class.
1. `Collection` can be represent paginated or simple group of objects
1. `Collection` allow for more flexibility, can be extended, and easy to use from any developer even if he/she did not have the experience to deal with array helper functions.
1. It could be helpful to reuse a ready made `Collection` class like [PHP Collection](http://jmsyst.com/libs/php-collection) ?

**Comment by yguedidi** [comment]
Why use a `Collection` as we only need a simple natvie array?

**Comment by devmsh** [comment]
> 3. Collection allow for more flexibility, can be extended, and easy to use from any developer even if he/she did not have the experience to deal with array helper functions.

Why not to use `Collection`?

**Comment by SammyK** [comment]
Not sure we're staying on topic here. Lol

But if the issue is whether or not to share a base `Collection` between the Graph nodes and the `list<type>`'s, then I can see @yguedidi's point that the `list<type>`'s could just be an array of whatever type they are. Alternatively, if we wanted to cast them as a `Collection` subtype, we could ensure that every item in the collection is a valid type.

**Comment by devmsh** [comment]
and allow the developers to deal with both of them using the same API?

while our reasons are clear, I think we must vote on this for now.

I :+1: for removing the dependency with `GraphNode`,  and :-1:  for decouple the `GraphEdge` with the `Collection` because it "maybe" helper and reusable even for `list<type>` or other scenario.

**Comment by SammyK** [comment]
I feel like I'd have to see some code that does what you guys are talking about because I'm not 100% sure I understand. Sorry! :)
