### ISSUE TITLE
Issue unlinking image file

### ISSUE THREAD

**Issue by mattmezza** [facebook/php-graph-sdk#578]
This piece of code gives me the Permission denied if I try to unlink the image I want to upload on Facebook

``` php
$filen = "image.png";
$req = new Facebook\FacebookRequest(
$fb->getApp(), $fb_access_token, 'POST', '/me/photos', array(
    'source' => $fb->fileToUpload($filen),
    'message' => "The message"
    ));
$res = $klein->fb->getClient()->sendRequest($req);
$graphNode = $res->getGraphNode();
$msg = "Posted with graphNode id: " . $graphNode['id'];
// here I get the warning and I cannot remove image.png
unlink($filen);
```

If I explicitely call the close() method things work

``` php
$filen = "image.png";
$fb_file = $fb->fileToUpload($filen);
$req = new Facebook\FacebookRequest(
$fb->getApp(), $fb_access_token, 'POST', '/me/photos', array(
    'source' => $fb_file,
    'message' => "The message"
    ));
$res = $klein->fb->getClient()->sendRequest($req);
$graphNode = $res->getGraphNode();
$msg = "Posted with graphNode id: " . $graphNode['id'];
// if I remove this call to the close() method I get permission denied warning
$fb_file->close();
unlink($filen);
```

It seems like Facebook is not closing the file after having used it for the upload, or maybe I am using  the default deconstructor in a wrong manner.

**Comment by SammyK** [comment]
Hey @mattmezza! Thanks for submitting this!

Have you tried to run the snippet just by itself? I've copied your example exactly and can't replicate the warning. I've even tried to reference `$fb_file` after the `unlink()` and it still works without a warning. I'm curious if there's something environment-specific going on here.

**Comment by mattmezza** [comment]
Hey @SammyK to let you reproduce the issue I have created a working example of that on this repository that you can clone and run with your facebook app data https://github.com/mattmezza/fb-sdk-file-issue.

In the project there is a img folder in which I am generating image files (just a square img colored). The good.php (after the auth with fb) posts and then deletes the image file while the bad.php just posts the image to facebook but fails to unlink it afterwards.

I don't know if this is an issue related to the library or to its wrong usage but I hope this helps out understanding it.


Currently I am running the project on this environment:

- Windows 7 Professional SP1 64bit
- XAMPP
    - Apache 2.4.18
    - PHP 7.0.4
