### ISSUE TITLE
PSR-4 and flat directory structure

### ISSUE THREAD

**Issue by localheinz** [facebook/php-graph-sdk#595]
Wondering, why use PSR-4 and not flatten the directory structure?

As seen in [`composer.json`](https://github.com/facebook/facebook-php-sdk-v4/blob/master/composer.json#L25-L35):

``` json
{
    "autoload": {
        "psr-4": {
            "Facebook\\": "src/Facebook/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Facebook\\Tests\\": "tests/"
        }
    }
}
```

you already have bought into flattening the directory structure for tests. 

Why not also flatten it for production code?

I've opened a PR in https://github.com/facebook/facebook-instant-articles-sdk-php/pull/109 to flatten the directory structure, there the vote is :-1:, using consistency as an argument. 

Here, however, it already is inconsistent within a single project.

How about making it consistent here (like most everyone who has adopted PSR-4 has), then also making an argument for the aforementioned PR to 👍 for a flattened directory structure?

**Comment by SammyK** [comment]
This has been brought up before and I'm 👍 for it. But let's see what @yguedidi thinks and also let's slate this one for v6. :)

**Comment by yguedidi** [comment]
I'm OK to flatten, but yes, only in v6.

**Comment by localheinz** [comment]
Thank you, @yguedidi!
