### ISSUE TITLE
Dropping the `-v4` suffix from the repo & Packagist

### ISSUE THREAD

**Issue by SammyK** [facebook/php-graph-sdk#638]
Let's finally knock out the conversation that started way back in #411 and drop the `-v4` from this repo name and Packagist. It's causing a lot of confusion with devs learning the Facebook PHP SDK for the first time so it'll be good to finally fix this. :)

We'll need help from Vivek on this one, but step one would be [rename the repo in GitHub](https://help.github.com/articles/renaming-a-repository/) then [point Packagist to the new repo name](https://github.com/composer/packagist/issues/47#issuecomment-130599468). Vivek: Here's the [direct edit link on Packagist](https://packagist.org/packages/facebook/php-sdk-v4/edit).

Then we can discuss renaming the package on Packagist to `facebook/sdk`. I believe this is done by abandoning `facebook/php-sdk-v4` and updating the name in `composer.json` to `facebook/sdk` and resubmitting. @yguedidi @stof Is that right?

**Comment by yguedidi** [comment]
Looks good to me :)

**Comment by yguedidi** [comment]
But I'd suggest `facebook/graph-sdk` for packagist package name haha

**Comment by SammyK** [comment]
> But I'd suggest `facebook/graph-sdk` for packagist package name haha

Yeah, that's a good idea since that would disambiguate it from the ads SDK and any other PHP SDK's @ Facebook.

Ping @viv001 :)

**Comment by viv001** [comment]
Sounds good guys! I will have a look on Monday and follow up on this thread :)
One thought though - Is there a reason we want to drop "php" from the package name? Like why not `facebook/php-graph-sdk` (I'd also consider `facebook/php-graph-api-sdk`) ?

**Comment by SammyK** [comment]
Sweet - thanks @viv001!

> Is there a reason we want to drop "php" from the package name?

It's just to remove some redundancy. Packagist only hosts php packages so there's no need for the prefix. :)

**Comment by stof** [comment]
@SammyK the process of updating is indeed right.
And +1 for removing the ``php`` redundancy in the composer package name (the github repo can of course keep it as there are other repositories)

**Comment by SammyK** [comment]
Thanks @stof! :)

Perhaps we could rename the repo to match the name on Packagist but with a `php-` prefix.

**Packagist:** `facebook/graph-sdk`
**GitHub:** `facebook/php-graph-sdk`

**Comment by stof** [comment]
Looks good to me

**Comment by viv001** [comment]
Update: Changed the github repo name
Waiting on previous owner of the corresponding packagist to grant me admin access to the package. Shall change the url and the name on it once I have the privileges.

**Comment by SammyK** [comment]
Yay! Thanks @viv001! :)

**Comment by viv001** [comment]
Update #2, updated composer.json and switched packagist to use the new package. Also set up corresponding github service hook for auto-update. 
@SammyK, @yguedidi : Can you confirm everything is as expected and close this? :)

**Comment by SammyK** [comment]
Yes! Works perfectly on my tests! Once @yguedidi confirms, we can close this one out. :)

@viv001 One more quick suggestion. The the [old `facebook/php-sdk`](https://packagist.org/packages/facebook/php-sdk) suggests using the `facebook/php-sdk-v4` package.

<img width="760" alt="screen shot 2016-08-22 at 6 37 47 pm" src="https://cloud.githubusercontent.com/assets/578780/17875430/bfd571ca-6897-11e6-93dd-d648a9f1a1ce.png">

Can we update this one on Packagist to point to the new package as well? :)

**Comment by viv001** [comment]
Done :)

**Comment by yguedidi** [comment]
Looks good! We finally remove it!! :)

**Comment by SammyK** [comment]
![](https://media.giphy.com/media/ZFTKZ8zwj38gE/giphy.gif)

Thanks for everyone's help on this! ❤️
