### ISSUE TITLE
Facebook SDK returned an error: Unknown SSL protocol error in connection to graph.facebook.com:443 

### ISSUE THREAD

**Issue by brojen** [facebook/php-graph-sdk#640]
My server doesn't have any SSL, is it possible to integrate facebook login with out SSL?

**Comment by SammyK** [comment]
Hey @brojen! Connecting to Facebook via HTTPS is required. I found [this](http://blog.techstacks.com/2010/03/3-common-causes-of-unknown-ssl-protocol-errors-with-curl.html) which might help you solve the error you're getting. :)
