### ISSUE TITLE
Upgrade Facebook graph api calls and app from 2.1 to 2.7 php

### ISSUE THREAD

**Issue by usamamashkoor** [facebook/php-graph-sdk#642]
Hi can some one please tell me how can i Upgrade Facebook graph api calls and app from 2.1 to 2.7 php.
I have seen facebook upgradation document 
https://developers.facebook.com/docs/apps/upgrading
bu this upgrade show only version by version upgrade like 2.0 to 2.1

Thanks and Regards
M.Usama

**Comment by SammyK** [comment]
Hey @usamamashkoor! You've really got the right guide to upgrade the Graph version. You'll basically have to go one step at a time. I recommend changing your code to point to v2.2 and test. If all is OK, then change to v2.3 and test. And so on.

There's also a helpful [Graph version upgrade tool](https://developers.facebook.com/tools/api_versioning/) that will help you identify changes in the API that are specific for your app based on the requests your app makes.

Good luck with the upgrade! :)
