### ISSUE TITLE
Switch default branch to 5.4

### ISSUE THREAD

**Issue by SammyK** [facebook/php-graph-sdk#645]
Hey @viv001! Now that v6.0 dev has officially begun on `master`, could you update the repo's default branch to `5.4`? :)

**Comment by SammyK** [comment]
Ping @viv001 :)

**Comment by yguedidi** [comment]
ping @viv001, should be 5.4 now (title edited) :)

**Comment by viv001** [comment]
@SammyK, @yguedidi : Sorry guys, completely missed it. So I just have to change the Default branch to 5.4 on GitHub settings right?

**Comment by SammyK** [comment]
No worries! Yes, that's correct. :)

**Comment by viv001** [comment]
Done :)
