### ISSUE TITLE
page tab ? help!

### ISSUE THREAD

**Issue by qwe356558603** [facebook/php-graph-sdk#648]
Create the page TAB, use the graph API I didn't find anything about TAB of the url attribute is set!
$data=array(
       		'app_id'=>'xxxxxxxxxxxx',
       		'custom_name'=>"百度",
       		'position'=>3,
       	);

![image](https://cloud.githubusercontent.com/assets/18321666/18189761/33846f62-70f0-11e6-9335-9032bf09d02e.png)

**Comment by SammyK** [comment]
Hey @qwe356558603! I'm not sure I understand your question. Can you provide some more details?
