### ISSUE TITLE
FacebookServerException: client_secret should not be passed to /oauth/

### ISSUE THREAD

**Issue by ahsanrana** [facebook/php-graph-sdk#649]
this is my code 

```php
error_reporting(E_ALL);
ini_set("display_errors", 1);
// Init PHP Sessions
if(!session_id()) {
    session_start();
}

require_once __DIR__ . '/fb/vendor/autoload.php';

use Facebook\Facebook;
use Facebook\Exceptions\FacebookResponseException;
use Facebook\Exceptions\FacebookSDKException;


$fb = new Facebook([
  'app_id' => 'XXXXX',
  'app_secret' => 'XXXXXXX',
  'default_graph_version' => 'v2.71',
  
]);

echo '<pre>';
$r_url = 'http://localhost/fb_callback.php';
$helper = $fb->getRedirectLoginHelper();
var_dump($_GET,$_SESSION);
$_SESSION['FBRLH_state'] = $_GET['state'];
try {
  $accessToken = $helper->getAccessToken($r_url);
  var_dump($helper->getError());
} catch(Facebook\Exceptions\FacebookResponseException $e) {
  // When Graph returns an error
  //echo 'Graph returned an error: ' . $e->getMessage();
  var_dump($helper->getError());
  //exit;
} catch(Facebook\Exceptions\FacebookSDKException $e) {
  // When validation fails or other local issues
  //echo 'Facebook SDK returned an error: ' . $e->getMessage();
  
  //exit;
}

var_dump($helper->getError());
var_dump($helper->getPersistentDataHandler());

exit;
if (! isset($accessToken)) {
  if ($helper->getError()) {
    header('HTTP/1.0 401 Unauthorized');
    echo "Error: " . $helper->getError() . "\n";
    echo "Error Code: " . $helper->getErrorCode() . "\n";
    echo "Error Reason: " . $helper->getErrorReason() . "\n";
    echo "Error Description: " . $helper->getErrorDescription() . "\n";
  } else {
    header('HTTP/1.0 400 Bad Request');
    echo 'Bad request';
  }
  exit;
}

// Logged in
echo '<h3>Access Token</h3>';
var_dump($accessToken->getValue());

// The OAuth 2.0 client handler helps us manage access tokens
$oAuth2Client = $fb->getOAuth2Client();

// Get the access token metadata from /debug_token
$tokenMetadata = $oAuth2Client->debugToken($accessToken);
echo '<h3>Metadata</h3>';
var_dump($tokenMetadata);

// Validation (these will throw FacebookSDKException's when they fail)
$tokenMetadata->validateAppId('XXXXXXXXXXXXX'); // Replace {app-id} with your app id
// If you know the user ID this access token belongs to, you can validate it here
//$tokenMetadata->validateUserId('123');
$tokenMetadata->validateExpiration();

if (! $accessToken->isLongLived()) {
  // Exchanges a short-lived access token for a long-lived one
  try {
    $accessToken = $oAuth2Client->getLongLivedAccessToken($accessToken);
  } catch (Facebook\Exceptions\FacebookSDKException $e) {
    echo "<p>Error getting long-lived access token: " . $helper->getMessage() . "</p>\n\n";
    exit;
  }

  echo '<h3>Long-lived</h3>';
  var_dump($accessToken->getValue());
}

$_SESSION['fb_access_token'] = (string) $accessToken;
```

in return m having this 

```
Fatal error:  Uncaught Facebook\Exceptions\FacebookServerException: client_secret should not be passed to /oauth/ in C:\xampp\htdocs\fb\vendor\facebook\php-sdk-v4\src\Facebook\Exceptions\FacebookResponseException.php:111
Stack trace:
#0 C:\xampp\htdocs\fb\vendor\facebook\php-sdk-v4\src\Facebook\FacebookResponse.php(210): Facebook\Exceptions\FacebookResponseException::create(Object(Facebook\FacebookResponse))
#1 C:\xampp\htdocs\fb\vendor\facebook\php-sdk-v4\src\Facebook\FacebookResponse.php(255): Facebook\FacebookResponse->makeException()
#2 C:\xampp\htdocs\fb\vendor\facebook\php-sdk-v4\src\Facebook\FacebookResponse.php(82): Facebook\FacebookResponse->decodeBody()
#3 C:\xampp\htdocs\fb\vendor\facebook\php-sdk-v4\src\Facebook\FacebookClient.php(224): Facebook\FacebookResponse->__construct(Object(Facebook\FacebookRequest), '{"error":{"mess...', 400, Array)
#4 C:\xampp\htdocs\fb\vendor\facebook\php-sdk-v4\src\Facebook\Authentication\OAuth2Client.php(277): Facebook\FacebookClient->sendRequest(Object(Facebook\FacebookRequest))
# in C:\xampp\htdocs\fb\vendor\facebook\php-sdk-v4\src\Facebook\Exceptions\FacebookResponseException.php on line 111
```

**Comment by SammyK** [comment]
Hey @ahsanrana!

This line `'default_graph_version' => 'v2.71',` should be `'default_graph_version' => 'v2.7',`.

Also - in what situation are you getting that error message? Can you provide more details about the steps you're taking to generate that error message?

**Comment by ahsanrana** [comment]
thanks for the version --
as far as i know the problem starts when i call "$accessToken = $helper->getAccessToken($r_url);"
i tried to var_dump($_GET,$_SESSION,$_COOKIE); after $fb->getRedirectLoginHelper();

this is the $_SESSION array
array(3) {
  ["facebook_access_token"]=>
  string(0) ""
  ["FBRLH_state"]=>
   "NULL"
  ["fb_access_token"]=>
  string(181) "blablabla"
}

**Comment by SammyK** [comment]
Are you hitting this script directly or are you allowing Facebook to redirect you to it after clicking on a "login with Facebook" link?

**Comment by ahsanrana** [comment]
<h1> login.php</h1>
code`
if(!session_id()) {
    session_start();
}
require_once __DIR__ . '/fb/vendor/autoload.php';

use Facebook\Facebook;
use Facebook\Exceptions\FacebookResponseException;
use Facebook\Exceptions\FacebookSDKException;


$fb = new Facebook([
  'app_id' => 'xxxxx',
  'app_secret' => 'xxx',
  'default_graph_version' => 'v2.7',
  'persistent_data_handler'=>'session',
  
]);

$r_url = 'http://localhost:80/fb_callback.php';
$helper = $fb->getRedirectLoginHelper();

$permissions = ['email']; // Optional permissions
$loginUrl = $helper->getLoginUrl($r_url, $permissions);

echo '<a href="' . htmlspecialchars($loginUrl) . '">Log in with Facebook!</a>';

`
<h1>fb_callback.php</h1>
`if(!session_id()) {
    session_start();
}

error_reporting(E_ALL);
ini_set("display_errors", 1);
// Init PHP Sessions

require_once __DIR__ . '/fb/vendor/autoload.php';

use Facebook\Facebook;
use Facebook\Exceptions\FacebookResponseException;
use Facebook\Exceptions\FacebookSDKException;


$fb = new Facebook([
  'app_id' => 'xxx',
  'app_secret' => 'xxxx',
  'default_graph_version' => 'v2.7',
  'persistent_data_handler'=>'session',
  
]);

echo '<pre>';
$r_url = 'http://localhost:80/fb_callback.php';
$helper = $fb->getRedirectLoginHelper();
var_dump($_GET,$_SESSION,$_COOKIE);
$_SESSION['FBRLH_state'] = $_GET['state'];

var_dump($helper->getPersistentDataHandler());

try {
  $accessToken = $helper->getAccessToken($r_url);
  var_dump($helper->getError());
} catch(Facebook\Exceptions\FacebookResponseException $e) {
  // When Graph returns an error
  //echo 'Graph returned an error: ' . $e->getMessage();
  var_dump($helper->getError());
  //exit;
} catch(Facebook\Exceptions\FacebookSDKException $e) {
  // When validation fails or other local issues
  //echo 'Facebook SDK returned an error: ' . $e->getMessage();
  
  //exit;
}
`

**Comment by ahsanrana** [comment]
i forgot to tell you , for first time i run the code it worked bt after that , error

**Comment by ahsanrana** [comment]
does this have any connection with Oath url-> app?

**Comment by ahsanrana** [comment]
sorry my mistake , solved

**Comment by SammyK** [comment]
Glad you figured it out! Can you post the solution so others can benefit as well? :)

**Comment by ahsanrana** [comment]
well its bit embarrassing , but the error was due to wrong (Valid OAuth redirect URIs) in app settings. just figure the right Valid OAuth redirect URIs . no code is needed

**Comment by SammyK** [comment]
Thanks @ahsanrana! :)

**Comment by ahsanrana** [comment]
hi sammy K , i working on marketing , and i want to share my code to know if i am doing it right , bt m unable to find right fb person to share my code , can u help me
