### ISSUE TITLE
picture GraphObjectMap for Album

### ISSUE THREAD

**Issue by flod1** [facebook/php-graph-sdk#651]
```
class GraphAlbum extends GraphNode
{
    /**
     * @var array Maps object key names to Graph object types.
     */
    protected static $graphObjectMap = [
        'from' => '\Facebook\GraphNodes\GraphUser',
        'place' => '\Facebook\GraphNodes\GraphPage',
        'picture' => '\Facebook\GraphNodes\GraphPicture',
    ];
```
.....

**Comment by SammyK** [comment]
Hey @flod1! Can you provide more details about your issue?

**Comment by flod1** [comment]
hy, if i fetch Albums by a Page, the Field "picture" ist a GRaphNode, but i could mappet as a "GraphPicture".

Ich test it, and it works fine.

**Comment by flod1** [comment]
another same issu is in the GraphPage class:

`class GraphPage extends GraphNode
{
    /**
     * @var array Maps object key names to Graph object types.
     */
    protected static $graphObjectMap = [
        'best_page' => '\Facebook\GraphNodes\GraphPage',
        'global_brand_parent_page' => '\Facebook\GraphNodes\GraphPage',
        'location' => '\Facebook\GraphNodes\GraphLocation',
        'cover' => '\Facebook\GraphNodes\GraphCoverPhoto',
        'picture' => '\Facebook\GraphNodes\GraphPicture',
    ];`

**Comment by SammyK** [comment]
Closing this since it will be added with #655. :)
