### ISSUE TITLE
Logout doesn't work

### ISSUE THREAD

**Issue by jetsynthesys** [facebook/php-graph-sdk#652]
Hi, 

I'am trying to implement facebook logout but it's not working. Every time I make the request it takes me to home page instead of logging out from facebook. 

Here is the code. 

```php
$fb = new \Facebook\Facebook([/** ... */]);
$helper = $fb->getRedirectLoginHelper();
$fbLogoutUrl = $helper->getLogoutUrl($_SESSION['fb_access_token'], "http://mysite.com");	
//session_destory();  <--- tried with this also but still its not working
header("Location: $fbLogoutUrl");
exit();
```

**Comment by SammyK** [comment]
Hey @jetsynthesys! The `getLogoutUrl()` method will log the user out of Facebook, not your website. If you want to log them out of your website, you'll need to delete the session/cookie containing their session data in your code. I don't recommend using the SDK to log the user out of Facebook.

I hope that helps! :)

**Comment by jetsynthesys** [comment]
Hi @SammyK, that i know but it takes me to https://www.facebook.com/home.php instead of logout, even though I'm passing my portal url in next parameter

**Comment by daniel-bbdev** [comment]
same happening here...

**Comment by arthPD** [comment]
@SammyK, I'm having the same problem. I want my user to log out from their facebook account, but the getLogoutUrl just takes me to facebook homepage.
I'm using laravel framework and have to use a custom persistent data handler.

please help. thanks

**Comment by SammyK** [comment]
I think Facebook might have disabled the logout feature. It hasn't seemed to work for a while now.

**Comment by arthPD** [comment]
Hi @SammyK, this worked for me, https://stackoverflow.com/a/25577384
Apparently, didn't add a platform for my app. Btw, thanks! :)

**Comment by SammyK** [comment]
Awesome! Thanks for sharing the solution! :)
