### ISSUE TITLE
360 Photos are flat using the php-graph-sdk

### ISSUE THREAD

**Issue by Joskin** [facebook/php-graph-sdk#658]
Using -> $fb->post('me/photos' ...) for uploading a 360 photo render it flat instead of 360. The same file works fine using the usual upload directly on facebook.
Am I missing a parameter?

**Comment by SammyK** [comment]
Hey @Joskin! Can you provide the 360 photo you are trying to upload?

**Comment by SammyK** [comment]
To enable 360 photo support with the PHP SDK, make sure to set the `allow_spherical_photo` parameter to `true`.

```php
$fb = new Facebook\Facebook($config);

$data = [
	'source' => $fb->fileToUpload(__DIR__.'/360-photo.jpg'),
	'allow_spherical_photo' => true,
	'message' => 'With 360 params',
	];
$res = $fb->post('/me/photos', $data, $accessToken);
```

Also check out the `spherical_metadata` parameter which gives you more fine-grained control of the 360 photo. See https://developers.facebook.com/docs/graph-api/reference/photo for more info. :)

**Comment by howardEagle** [comment]
I was tried to upload remote file:
```
$fb = new Facebook\Facebook($config);

$data = [
    'url' => $remote_photo,
    'allow_spherical_photo' => true,
    'message' => 'With 360 params',
    ];
$res = $fb->post('/groupId/feed', $data, $accessToken);
```
but photo doesn't appear at the feed.
