### ISSUE TITLE
Ternary operator is poorly supported on some versions of PHP (return an empty response by browser)

### ISSUE THREAD

**Issue by flexeo** [facebook/php-graph-sdk#659]
Facebook SDK stop the php script (return an empty response by browser) very often.

The solution is that the new format of "ternary operator" is poorly supported on some versions of PHP.

You can find more information on that, but the solution is to change in every class:

$var1 = $var1?: $var2;

by (usually):

$var1 = $var1 ? $var1 : $var2;

I made a modified version that works perfectly for me: https://uploadfiles.io/8ec40

For Facebook Developer SDK, I have PHP version 5.4.45-1~dotdeb+7.1

**Comment by SammyK** [comment]
Hey @flexeo! I can't seem to find resources about this issue in PHP. Could you link to an https://3v4l.org/ example or other resources?

**Comment by yguedidi** [comment]
@flexeo I will close this one for now, feel free to post a new issue if you can reproduce the bug and provide us a way to reproduce to or a 3v4l link. Thanks for reporting.
