### ISSUE TITLE
Package facebook/php-sdk-v4 is abandoned, you should avoid using it. Use facebook/graph-sdk instead

### ISSUE THREAD

**Issue by martynbiz** [facebook/php-graph-sdk#661]
Hi, we'll using the old "abandoned" packagist php-sdk-v4 repo, version ^5.1. Is this simply a case of switching the repo in composer?

Eg.

``` 
"require": { ...
   "facebook/php-sdk-v4": "^5.1", ---> "facebook/graph-sdk": "^5.1",
```

At a glance, the files look the same anyway :)

**Comment by SammyK** [comment]
Yep! We just renamed the repo. Let us know if you have any issues with it! :)
