### ISSUE TITLE
Convert docs to standard markdown

### ISSUE THREAD

**Issue by SammyK** [facebook/php-graph-sdk#673]
Then we can link from the official docs to the repo wiki to make sure the docs are always up-to-date. :)

**Comment by yguedidi** [comment]
Aha I just answered you by email! Here my throughts:
I agree about moving the doc to GitHub, but I don't think using the GitHub Wiki feature is a good idea...
I think it's better to keep the doc in the repo, but convert it to Markdown (it will be a tedious work...).
Then, we can require any PR to have its associated doc :)

BTW, in the future, we may use GitHub Pages and [Couscous](http://couscous.io/) to have an online version of the doc!

**Comment by SammyK** [comment]
Just tagged this as "low-hanging fruit" for anyone who wants to take it on! :) Here are the [current docs](https://github.com/facebook/php-graph-sdk/tree/master/docs) in Facebook's flavor of markdown. We just have to:

1. Rename the files to `.md`
2. Remove/update any fbmd to standard or GitHub markdown
3. Update links pointed to `/docs/php/*` to point to the correct doc file in the repo

**Comment by SammyK** [comment]
Just posted the first PR for this (#676) if you want more help in what needs to be done. :)

**Comment by SammyK** [comment]
Now that the docs are organized a bit better, we need to go through each of the files and:

* Remove Facebook-style markup:
  * Remove `<card></card>` tags
  * Remove Facebook header anchors (`{#*}` in headers e.g. `## Example {#example}` -> `## Example`)
  * Convert code blocks from  `~~~~ /* */ ~~~~` to `\`\`\`php /* */ \`\`\``
  * Convert `%FB(devsite:markdown-wiki:info-card {*})` to a [quote block](https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-text): `> *`
  * Convert `%FB(devsite:markdown-wiki:table {*})` to a [table block](https://help.github.com/articles/organizing-information-with-tables/)
* Update all Graph API version references to `v2.8`
* Update links to point to either the relative path (`/docs/php/FacebookCanvasHelper` -> `docs/reference/FacebookCanvasHelper.md`) or the corresponding Facebook documentation for non PHP SDK links (`/docs/javascript` -> `https://developers.facebook.com/docs/javascript`)
* Fix any type-o's you come across for there are many. :)

Let's get this really fleshed-out for v5 on `master` & I'll cherry-pick all the commits to the latest `5.x` branch. Once completed, we'll update the docs on `master` to start reflecting v6. :)

**Comment by nayafia** [comment]
Hi! :wave: I'll tackle this list now.

**Comment by nayafia** [comment]
Clarification question: we're updating all the docs [on this list](https://github.com/facebook/php-graph-sdk/tree/master/docs), right? Does it make sense to merge #677 (for the new ```.md``` extensions) before I go through the files?

**Comment by SammyK** [comment]
Hey @nayafia! Thanks for taking this one on! :) I've merged #677 so we should be good to go. And yes, all the files in `docs/` that have fbmd in them need to be converted which should be all of them except for `docs/README.md` at the moment. :)

**Comment by yguedidi** [comment]
Thanks @nayafia!
