### ISSUE TITLE
Facebook->get() doesn't support parameters?

### ISSUE THREAD

**Issue by pugsley** [facebook/php-graph-sdk#674]
Finally upgrading from v4.x and keen to use the handy `Facebook->get()` helper function but it doesn't accept a parameters array? Seems weird when the `FacebookRequest` class handles parameters with a `GET` request (see `FacebookRequest->getUrl`).

**Comment by SammyK** [comment]
Correct, v5 does not support an array of params, you have to build them yourself with [`http_build_query()`](http://php.net/http_build_query). But since this is a feature that many have requested, it will be added in v6 (see item 6 in #587). :)

**Comment by pugsley** [comment]
Great, thanks!
