### ISSUE TITLE
default access token

### ISSUE THREAD

**Issue by dev-yohan** [facebook/php-graph-sdk#675]
Hi, I see in read me that we can initialize Facebook object like this:
```
$fb = new \Facebook\Facebook([
  'app_id' => '{app-id}',
  'app_secret' => '{app-secret}',
  'default_graph_version' => 'v2.7',
  'default_access_token' => $default,
]);
```
The default_access_token appears as optional, so I'm confused about the purpose of that default token and how can I get that because we want to get the user token for business without ask for a access_token again

regards

**Comment by SammyK** [comment]
The `default_access_token` will be used whenever you make a request without explicitly providing an access token. The following examples will use the default access token:

```php
$fb->get('/me');
$fb->post('/me/photos', $data);
$fb->delete('/123456');
```
