### ISSUE TITLE
OAuthException 191

### ISSUE THREAD

**Issue by shine0565** [facebook/php-graph-sdk#684]
![image](https://cloud.githubusercontent.com/assets/10022881/19548930/d9c33daa-96d3-11e6-8fa8-3c2ebaea9ee7.png)

But on the callback facebook.php, I got a FacebookResponseException error:
URL kan niet worden geladen: Het domein van deze URL is niet toegevoegd aan de domeinen van deze app. Voeg alle domeinen en subdomeinen van je app toe aan het veld Appdomeinen in de instellingen van je app om deze URL te kunnen laden.

I print $e->getResponseData();
got the error code 191.
result like that:

Array ( [error] => Array ( [message] => URL kan niet worden geladen: Het domein van deze URL is niet toegevoegd aan de domeinen van deze app. Voeg alle domeinen en subdomeinen van je app toe aan het veld Appdomeinen in de instellingen van je app om deze URL te kunnen laden. [type] => OAuthException [code] => 191 [fbtrace_id] => DDi/+hJT4+n ) )

my app setting:
![image](https://cloud.githubusercontent.com/assets/10022881/19549157/479ee684-96d5-11e6-8c9d-9a227ec907e8.png)

what's wrong with my program?

**Comment by SammyK** [comment]
Hey @shine0565! The url must also be listed under app settings in the "App Domain" filed.

<img width="384" alt="screen shot 2016-12-13 at 10 30 03 am" src="https://cloud.githubusercontent.com/assets/578780/21148863/3b5cf23e-c11f-11e6-9dfc-f490d67614b7.png">

I hope that helps! :)
