### ISSUE TITLE
opportunity to Cancel user subscription

### ISSUE THREAD

**Issue by bopoda** [facebook/php-graph-sdk#685]
Can we cancel user subscription without direct user intervention using this sdk? or using previous sdk version?
smt like this but from server side only: https://developers.facebook.com/docs/games_payments/advanced/subscriptions/#prompting-a-user-to-cancel-a-subscription
Thanks!

**Comment by SammyK** [comment]
Hey @bopoda! I did some research and it doesn't seem to be possible to cancel a payment subscription from the Graph API. If anyone knows differently - please chime in! :)
