### ISSUE TITLE
ErrorException [ Fatal Error ]: Call to undefined function Facebook\Helpers\random_bytes()

### ISSUE THREAD

**Issue by Shadomax** [facebook/php-graph-sdk#686]
Good morning guys, I just downloaded the v6 of the facebook graph api and implemented it but when i try to visit the page which has the facebook login i have the Error *** ErrorException [ Fatal Error ]: Call to undefined function Facebook\Helpers\random_bytes() ***. Please i need help.

**Comment by SammyK** [comment]
Hey @Shadomax! v6 is the developmental branch. Please use [5.4](https://github.com/facebook/php-graph-sdk/tree/5.4). :)

**Comment by Shadomax** [comment]
Thank you @SammyK for the tip.
