### ISSUE TITLE
please how can i get the user email

### ISSUE THREAD

**Issue by Shadomax** [facebook/php-graph-sdk#687]
Hey guys am sorry to disturb but i have issues using the facebook api v5. I have generated the login url well and included in the permission array email but i can't seem to get the user email from the GraphUser object. Please what can i do?

**Comment by tracylemke** [comment]
Yet to test this sdkbut have u tried this? https://developers.facebook.com/docs/php/howto/example_retrieve_user_profile

**Comment by SammyK** [comment]
Hey @Shadomax! Can you provide some code samples of what you have so far?

**Comment by Shadomax** [comment]
thank you so much for replying but i noticed that the user didn't
authorized their email to be seen by apps. I tried on some other account
and i got the user email. Thanks once again.

On Tue, Dec 13, 2016 at 5:08 PM, Sammy Kaye Powers <notifications@github.com

**Comment by yguedidi** [comment]
Thanks @Shadomax!
