### ISSUE TITLE
how to get the likes count of a facebook page in v2.8 using php-graph-sdk?

### ISSUE THREAD

**Issue by cw-prasanjitmishra** [facebook/php-graph-sdk#688]
I using php-graph-sdk v5.4 and graph API v2.8.

Currently i am able to find the likes of a page using 
"https://graph.facebook.com/{Page_id}/Insights/page_fans_country?access_token={access_Token}".

But i am getting the likes of top 45 countries only.

But i use graph API explorer v2.4, i am getting the exact likes count.

How to get the exact likes count using php-graph-sdk v5.4 and graph API v2.8?

**Comment by SammyK** [comment]
Hey @cw-prasanjitmishra! If you want to get the number of users who liked a page across all countries and brands, you'll want to check the `fan_count` field from the Page node: `/{page-id}?fields=id,fan_count`. See the [Page node docs](https://developers.facebook.com/docs/graph-api/reference/page) for more info.
