### ISSUE TITLE
Guzzle implementation broken

### ISSUE THREAD

**Issue by cyberhck** [facebook/php-graph-sdk#696]
Steps to reproduce:
Remove (if present) PHP curl extension and execute the following:
```
$facebook = new Facebook\Facebook([
    'app_id' => env('FACEBOOK_APP_ID'),
    'app_secret' => env('FACEBOOK_APP_SECRET')
]);
$facebook->get('/me?fields=id,name,email', '<VALID AUTH TOKEN>');
```

Expected:
Everything OK

Actual:
> TypeError: Argument 3 passed to GuzzleHttp\Client::request() must be of the type array, string given, called in /home/cyberkiller/meme.market/vendor/guzzlehttp/guzzle/src/Client.php on line 87

I've found that it's a guzzle implementation thing.

Interesting workaround though is to install curl extension and everything works as expected.

**Comment by galeaspablo** [comment]
They're using guzzle 5, not 6. That's why.

**Comment by cyberhck** [comment]
@galeaspablo thanks for your response, I didn't do a composer update myself, I just pulled facebook as a dependency from composer. Maybe some other issue.
