### ISSUE TITLE
What FB cookie should i exclude from Varnish rule?

### ISSUE THREAD

**Issue by champsupertramp** [facebook/php-graph-sdk#697]
Hi,

I keep recieving the following message when Varnish is enabled on my server:
`Cross-site request forgery validation failed. Required param "state" missing.`

I tried adding the following cookies to exclude in the Varnish rule but still the same issue:
* access_token
* fbsr_*
* fbsr_<app_id>
* FBRLH_*

I also exclude the Login page and callback URL from cache/varnish.

Regards,

**Comment by yguedidi** [comment]
This means the state isn't saved in the session. Check that you use the `FacebookSessionPersistentDataHandler` and that your session is started
