### ISSUE TITLE
How to get facebook user id in php application

### ISSUE THREAD

**Issue by iamQureshi** [facebook/php-graph-sdk#701]
Hi ,
I want to get Facebook user ID in my application. I used  FB.getSession() , its not working. Even that i used another function FB.getAuthResponse, also not working , this function always returns null.
please help me.

**Comment by SammyK** [comment]
Hey @iamQureshi! You're referring to the JavaScript SDK. This is the PHP SDK. Please refer to the documentation:

https://developers.facebook.com/docs/reference/javascript/FB.getLoginStatus
https://developers.facebook.com/docs/reference/javascript/FB.getAuthResponse

**Comment by yguedidi** [comment]
This is the repo of the PHP SDK, `FB.getSession()` and `FB.getAuthResponse` are Javascript calls, so please use Stackoverflow or another channel to get help.
