### ISSUE TITLE
Facebook API could not fetch data

### ISSUE THREAD

**Issue by dragu** [facebook/php-graph-sdk#702]
I have posted it here too: http://stackoverflow.com/questions/40460261/facebook-api-could-not-fetch-data but no answers. I hope you can help me.

I try to fetch data from urls:

demotywatory.pl/4706711/Ten-moment - [API](https://developers.facebook.com/tools/explorer/?method=GET&path=%3Fid%3Dhttp%3A%2F%2Fdemotywatory.pl%2F4706711%2FTen-moment&version=v2.8)

demotywatory.pl/4706300/Co-ma-zrobic-mezczyzna-aby-zrozumiec-ciezarna-kobiete - [API](https://developers.facebook.com/tools/explorer/?method=GET&path=%3Fid%3Dhttp%3A%2F%2Fdemotywatory.pl%2F4706300%2FCo-ma-zrobic-mezczyzna-aby-zrozumiec-ciezarna-kobiete&version=v2.8)

Both returns ID only. The sharing debugger is showing a [blank page](https://developers.facebook.com/tools/debug/sharing/?q=http://demotywatory.pl%2F4706711%2FTen-moment) when I'm trying to debug it.

I think it is a Facebook-side bug. Any idea how to solve this?

**Comment by JamesTheHacker** [comment]
What "data" are you expecting to fetch? Here's the documentation: https://developers.facebook.com/docs/graph-api/reference/v2.8/url

**Comment by dragu** [comment]
If you know better way to make contact with developers than writing here; I'm listening.

**Comment by JamesTheHacker** [comment]
Can you share the code you're using?

**Comment by dragu** [comment]
Code is not required to reproduce the bug.

Look at [this (bugged)](https://developers.facebook.com/tools/explorer/?method=GET&path=%3Fid%3Dhttp%3A%2F%2Fdemotywatory.pl%2F4706711&version=v2.8) response and [this (correct)](https://developers.facebook.com/tools/explorer/?method=GET&path=%3Fid%3Dhttp%3A%2F%2Fdemotywatory.pl%2F3761038&version=v2.8).

Sharing debugger doesnt work with first url. I already wrote it.

**Comment by JamesTheHacker** [comment]
The reason I asked is because it's working fine for me for my own domain.

**Comment by JamesTheHacker** [comment]
You're posting an issue on the PHP SDK. If you are not using the PHP SDK your issue doesn't belong here.

**Comment by dragu** [comment]
> The reason I asked is because it's working fine for me for my own domain.

It does not affect all responses

> You're posting an issue on the PHP SDK. If you are not using the PHP SDK your issue doesn't belong here.

> If you know better way to make contact with developers than writing here; I'm listening.

**Comment by JamesTheHacker** [comment]
@dragu If your issue isn't related to the PHP SDK nobody here can help. Most people here are unpaid contributors and do not work directly for Facebook. I'm sorry you can not get the answers you require, but I'm trying to advise you that you're wasting your time posting such issues here.

From my understanding your issue is relating to the Graph API in general.

**Comment by dragu** [comment]
I understand, thank you for your advice, but writing here give me better chance to inform developers about bug than do nothing and waiting, don't you think?

**Comment by dragu** [comment]
https://developers.facebook.com/bugs/791822784253426/
