### ISSUE TITLE
[6.0] Update guzzle version

### ISSUE THREAD

**Issue by jonathancesario** [facebook/php-graph-sdk#703]
Just wondering, if there any specific reason for not updating the guzzle to its latest stable version? Although it's probably minor, there will be a problem if you use guzzle 6.* with php-graph-sdk

**Comment by foaly-nr1** [comment]
See here https://github.com/facebook/php-graph-sdk/issues/587

**Comment by jonathancesario** [comment]
My bad, I only read the title of other issues. Thanks!
