### ISSUE TITLE
Get the full response returned by Facebook including fbtrace_id

### ISSUE THREAD

**Issue by GMaxera** [facebook/php-graph-sdk#707]
In the past month I had to open some bugs on Facebook support and bugs portal. And to solve my problem they always asked me to provide the fbtrace_id

But when a call if made using this PHP library like $fb->post() or $fb->get(), in case of error a PHP exception is thrown and I didn't find any way to retrieve the full underlying response with the fbtrace_id 

This make impossible for Facebook to help me on debug the problem.

So, please, could you tell me how can I extract the fbtrace_id from a response exception thrown by this library ?

**Comment by SammyK** [comment]
Hey @GMaxera! You can catch the exception and access the response from Graph as an array with `FacebookResponseException::getResponseData()`. Then you can pull out the `fbtrace_id`:

```php
try {
	$res = $fb->get('/foo', $accessToken);
} catch (Facebook\Exceptions\FacebookResponseException $e) {
	var_dump($e->getResponseData()['error']['fbtrace_id']);
}
```
