### ISSUE TITLE
Custom Curl options

### ISSUE THREAD

**Issue by Viliasas** [facebook/php-graph-sdk#708]
Hello,

We are using php-graph-sdk behind proxy and we need to set "CURLOPT_PROXY" for it to work correctly. But it seems to be impossible due to the fact, that FacebookCurlHttpClient does not remember them and reinitializes FacebookCurl in "openConnection" method ($this->facebookCurl->init();).

I'm trying to set "CURLOPT_PROXY" this way:
```
$curlClient = new Facebook\HttpClients\FacebookCurl();
$curlClient->init();
$curlClient->setopt(CURLOPT_PROXY, 'XXX.XXX.XXX.XXX:XXXX');

$client = new Facebook\HttpClients\FacebookCurlHttpClient($curlClient);

$fb = new Facebook\Facebook(array(
  'app_id' => 'X',
  'app_secret' => 'X',
  'default_graph_version' => 'v2.5',
  'http_client_handler' => $client
));
```

Might someone know if I'm doing it wrong or if it's impossible?

**Comment by SammyK** [comment]
Hey @Viliasas! You'll need to [inject your own curl handler](https://www.sammyk.me/how-to-inject-your-own-http-client-in-the-facebook-php-sdk-v5#customizing-the-curl-predefined-constants) if you want to customize the options. Hope that helps! :)
