### ISSUE TITLE
Is it possible to publish post with multiple photos as page 

### ISSUE THREAD

**Issue by itekkdeveloper** [facebook/php-graph-sdk#709]
This is my sample  code, I can only upload one picture in a post published on my selected page with this code, actually I want to upload multiple photos on single post.  I have tried many things using my page id nothing happened. if its possible please help

                                $post = $fb->post('/{mypage-id}/feed', 
                                    array(
                                        'picture' => {image path},
                                        'message' =>{message},
                                        'link' => {link}
                                    ),

**Comment by SammyK** [comment]
Hey @itekkdeveloper! Are you trying to upload multiple photos with one request to the Graph API or have them show up on the Page timeline grouped together in one post?

**Comment by itekkdeveloper** [comment]
yes, if its possible, please help me.


On Sat, Dec 17, 2016 at 3:34 AM, Sammy Kaye Powers <notifications@github.com

**Comment by SammyK** [comment]
If you're just trying to have them all grouped together Facebook will do that automatically for you. But you need to post the the [`/{page-id}/photos` edge](https://developers.facebook.com/docs/graph-api/reference/v2.8/page/photos). Facebook will group them on the Page timeline as if they were one post.

```php
$data = [
	'caption' => 'Image #1',
	'source' => $fb->fileToUpload($image1),
	];
$response = $fb->post('/{page-id}/photos', $data, $accessToken);

// . . .

$data = [
	'caption' => 'Image #99',
	'source' => $fb->fileToUpload($image99),
	];
$response = $fb->post('/{page-id}/photos', $data, $accessToken);
```

**Comment by sanjeetbisht** [comment]
hey I'm using graph version 2.9 but the above method posted images separated and are showing in separate posts.
I want to club the different images into one post in a page.

**Comment by gerryats** [comment]
Were you able to achieve this? I'm trying to do the same thing but photos are uploaded as separate post

**Comment by bisht-sanjeet** [comment]
Didn't worked with above method and haven't tried with new graph api.
So it is still not working for me.

**Comment by jojurdi** [comment]
{ 
  "message": "xxx",
  "published": true,
  "attached_media[0]": "{\"media_fbid\":\"photo_id1\" }"
  "attached_media[1]": "{\"media_fbid\":\"photo_id2\" }"
}
