### ISSUE TITLE
Inconsistency map function between Collection and GraphEdge

### ISSUE THREAD

**Issue by qpautrat** [facebook/php-graph-sdk#714]
Hi there,

There is a design mistake by extending `GraphEdge` from `Collection` in `map` function.
`GraphEdge` is waiting a `FacebookRequest` instance not an array.
This leads to this given error `Catchable Fatal Error: Argument 1 passed to Facebook\GraphNodes\GraphEdge::__construct() must be an instance of Facebook\FacebookRequest, array given`.

**Comment by yguedidi** [comment]
Thank you @qpautrat, you're right! Would you like to provide a PR that fix that issue or let me take care of this? :)

**Comment by qpautrat** [comment]
I don't know why `GraphEdge` extends from `Collection`.  To be honest I just use this package for very limited interest so I don't know much. In my opinion this issue has relative with [Collection class should be removed ?](https://github.com/facebook/php-graph-sdk/issues/440)
I think it is a good idea and it should be resolved this error. What is your thoughts about this ?

**Comment by yguedidi** [comment]
The proposal is for 6.0. A quick fix for 5.4 would be to extend the `map` function in `GraphEdge` :)
