### ISSUE TITLE
broken facebook/php-sdk

### ISSUE THREAD

**Issue by glensc** [facebook/php-graph-sdk#716]
https://packagist.org/packages/facebook/php-sdk should be configured back to to use old repository `github.com/facebookarchive/facebook-php-sdk`

someone has set it's url to be `github.com/facebook/php-graph-sdk` instead of previous `github.com/facebookarchive/facebook-php-sdk` making projects that use `facebook/php-sdk` in their `composer.json` dependencies broken

**Comment by glensc** [comment]
example error: https://github.com/composer/composer/issues/6011

```
    - The requested package facebook/php-sdk ~3.2.3 exists as facebook/php-sdk[4.0.1, 4.0.10, 4.0.11, 4.0.12, 4.0.13, 4.0.14, 4.0.15, 4.0.16, 4.0.17, 4.0.18, 4.0.19, 4.0.2, 4.0.20, 4.0.21, 4.0.22, 4.0.23, 4.0.3, 4.0.4, 4.0.5, 4.0.6, 4.0.7, 4.0.8, 4.0.9, 5.0.0, 5.1.0, 5.1.1, 5.1.2, 5.1.3, 5.1.4, 5.1.5, 5.1.x-dev, 5.2.0, 5.2.1, 5.2.x-dev, 5.3.0, 5.3.1, 5.3.x-dev, 5.4.0, 5.4.1, 5.4.2, 5.4.x-dev, dev-4.0-dev, dev-4.1-dev, dev-master, 6.x-dev, v4.0.0] but these are rejected by your constraint.
```

**Comment by SammyK** [comment]
Oh snap! @viv001 Would you be able to point https://packagist.org/packages/facebook/php-sdk back to https://github.com/facebookarchive/facebook-php-sdk?

Thanks for reporting this @glensc! :)

**Comment by yguedidi** [comment]
I'm OK to point to the new URL to not breal installs, but...

![image](https://cloud.githubusercontent.com/assets/1480128/21561708/90b70018-ce70-11e6-97fe-8228a6c42aaf.png)

Is that too bad to just have to change the `composer.json` to be up to date? :)

**Comment by SammyK** [comment]
The `facebook/php-sdk` namespace pointed to version 3 of the PHP SDK before Fosco rewrote it and v3 isn't available via the `facebook/php-graph-sdk` or `facebook/php-sdk-v4` namespaces. That's why we need to point it back to the old archived v3 PHP SDK. :)

**Comment by yguedidi** [comment]
OMG v3, I totally forgot about it! :)

**Comment by viv001** [comment]
@SammyK just made the change! Can you confirm and close this out? :)

**Comment by glensc** [comment]
https://packagist.org/packages/facebook/php-sdk versons here are correct now:

dev-master
v3.2.3
v3.2.2
v3.2.1
v3.2.0

**Comment by SammyK** [comment]
Thanks @viv001! And thanks for the report @glensc! :)
