### ISSUE TITLE
Update all the copyright headers to 2017

### ISSUE THREAD

**Issue by SammyK** [facebook/php-graph-sdk#717]
Who wants this low hanging fruit? :)

**Comment by localheinz** [comment]
How about using `friendsofphp/php-cs-fixer` with the header comment fixer enabled?

See https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/src/Fixer/Comment/HeaderCommentFixer.php.

**Comment by freekmurze** [comment]
On it!
