### ISSUE TITLE
Upload of SRT Captions File fails due to MimeType

### ISSUE THREAD

**Issue by boredom2** [facebook/php-graph-sdk#731]
Hi there,

in case of Uploading an SRT Caption File as outlined in the Docs with Parameter 'captions_file' pointing to a FacebookFile($path), the API returns an Error about unexpected Mimetypes (which defaults to a text Type). Expected id an application/octet-stream Mimetype.
To solve this Issue, just add a "srt" => "application/octet-stream" line to \Facebook\FileUpload\Mimetypes.

Thanks.

**Comment by SammyK** [comment]
Thanks so much for reporting this! I've added a patch and it will be released in the next tag (sometime later today). :)
