### ISSUE TITLE
Undefined index: location in [facebook\graph-sdk\src\Facebook\GraphNodes\Collection.php

### ISSUE THREAD

**Issue by gemal** [facebook/php-graph-sdk#733]
`Notice Error: Undefined index: location in [facebook\graph-sdk\src\Facebook\GraphNodes\Collection.php, line 201]`

using 5.4.3

call:
`/731850520226885?fields=location{longitude,latitude}`
using v2.8

**Comment by SammyK** [comment]
Hey @gemal! When I run that query it does not return a location field. Make sure the location field exists before trying to use it:

```php
if (isset($data['location'])) {
    // Do stuff here
}
```

**Comment by gemal** [comment]
I did this:
`isset($data["location"]["latitude"])`

that seemed to cause the notice

**Comment by SammyK** [comment]
Try using `getField`:

```php
if ($data->getField('location')) {
    // Do stuff here
}
```
