### ISSUE TITLE
Problem with endpoint /{album-id}/photos

### ISSUE THREAD

**Issue by RaphaelBatagini** [facebook/php-graph-sdk#736]
Post request to this endpoint return the message "An unknown error has occurred" with error code 1.
I'm passing these parameters:
[
    'url' => img_url_from_my_site,
    'message' => 'some text',
   'no_story' => true
]

**Comment by yguedidi** [comment]
@RaphaelBatagini Please use Stackoverflow for help about the Graph API. I'm closing this one.
