### ISSUE TITLE
Video Upload and "find the Videos"

### ISSUE THREAD

**Issue by boredom2** [facebook/php-graph-sdk#738]
Hi there,

if I upload a Video to a Page through the PHP SDK with Attributes:

published=>FALSE
no_story=>TRUE

it seems to work - I get a Result ID.
But these Videos do not appear in the "Video Hub" on my Page, I can only access them from the "Notification Area" of Facebook - there is no other Way to find it.
Shouldnt they appear at elast in the Video Hub, where I can publish it then?
Or is that intended?
Or, other way round, what do I have to add in order to make them appear in the Pages Video Hub?

Thanks!

**Comment by yguedidi** [comment]
Thank you for using the Facebook PHP SDK!

If you need help about using it, you should ask your questions on [StackOverflow](https://stackoverflow.com/) and tag them with the `facebook-php-sdk` tag.

So I'm closing this, but if you found a bug in the SDK or think about a feature, feel free to open a new GitHub issues.
