### ISSUE TITLE
Post in page like page not like user

### ISSUE THREAD

**Issue by klevinkona** [facebook/php-graph-sdk#744]
Trying to post via php sdk in my facebook page, i can post with my personal facebook user, but i need to post like the page

 include('header.php'); 

$accesstoken = $_SESSION['fb_access_token'];

require_once __DIR__ . '/src/Facebook/autoload.php';
use Facebook\FacebookRequest;

$fb = new Facebook\Facebook([
  'app_id' => '384253095275102',
  'app_secret' => 'bb57a6cb95tf21542588bf71a040a330',
  'default_graph_version' => 'v2.2',
  ]);

	try { $response = $fb->post('/726795224144200/feed?', array (
	         "message" => "Message test from php sdk",
            "link" => "http://www.example.com",
            "picture" => "http://www.example.net/images/example.png",
            "name" => "Title",
            "caption" => "www.example.com",
            "description" => "Description example"	 

	 ) ,  $accesstoken );
	} catch(\Facebook\Exceptions\FacebookResponseException $e) {
	  // When Graph returns an error
	  echo 'Graph returned an error: ' . $e->getMessage();
	  exit;
	} catch(\Facebook\Exceptions\FacebookSDKException $e) {
	  // When validation fails or other local issues
	  echo 'Facebook SDK returned an error: ' . $e->getMessage();
	  exit;
	}

	$data = $response->getDecodedBody();

	echo "<pre>";
	var_dump($data);
	echo "</pre>";

**Comment by yguedidi** [comment]
Thank you for using the Facebook PHP SDK!

If you need help about using it, you should ask your questions on [StackOverflow](https://stackoverflow.com/) and tag them with the `facebook-php-sdk` tag.

So I'm closing this, but if you found a bug in the SDK or think about a feature, feel free to open a new GitHub issues.
