### ISSUE TITLE
sdk and captive portal

### ISSUE THREAD

**Issue by dmitry-khartsy** [facebook/php-graph-sdk#745]
Hi!
I want to use PHP GRAPH SDK for authorisation in hotspot (captive portal). While user not authorised (internet access sessionn not started yet), all resources in internet are blocked for him, except domains, added to "walled garden". Other side, to have posibility of athorisation user at facebook.com, he need to have access to facebook.com. So, captive portal need to add facebook.com to "walled garden". And, as result - users can access FB via hotspot WITHOUT ANY autorisation! My question is - is it possible that SDK will use FOR ALL communications to facebook server (including user autorisation in facebook.com) VIA PROXY? And where it could be configured in SDK?

**Comment by yguedidi** [comment]
Thank you for using the Facebook PHP SDK!

If you need help about using it, you should ask your questions on [StackOverflow](https://stackoverflow.com/) and tag them with the `facebook-php-sdk` tag.

So I'm closing this, but if you found a bug in the SDK or think about a feature, feel free to open a new GitHub issues.
