### ISSUE TITLE
QUESTION: Do your tests use API mocking?

### ISSUE THREAD

**Issue by jorgeorpinel** [facebook/php-graph-sdk#748]
Your unit tests seem pretty straightforward. They seem to actually let the SDK use the real API. Is there any mechanism to intercept the HTTP calls to the API or are they really just hitting the real thing? Any mocking at all?

I'm just interested in seeing what FB's approach since this isn't the easiest thing to do on PHP apparently, except perhaps for Guzzle's Mock Handler (which only works for calls done with Guzzle). There are tools like stoplight and prism, as well as mockbin.com (creator of unirest-php) people use but they're a bit complicated...

**Comment by yguedidi** [comment]
Most of our tests are unit tests. Actually there is only one integration test that use real API calls: https://github.com/facebook/php-graph-sdk/blob/93d7dc87e55a541d2e27d38f3aed40abbffdf6e1/tests/FacebookClientTest.php#L207-L258

BTW, @SammyK and I are not from Facebook :)
