### ISSUE TITLE
FB user has two different userIDs

### ISSUE THREAD

**Issue by wzup** [facebook/php-graph-sdk#749]
A weird thing from FB API. One user has two different IDs.

I use FB JavaScript SDK on client. Since I can't find appropriate repo, I'll post my question here. Pass it along to whom it may concern, please.

First, I call `FB.getLoginStatus` request. The response is like this:
```
authResponse: {
    accessToken: "EAAa8S8Ocf.....QZBQ9BPQZDZD",
    expiresIn: 7045,
    grantedScopes: "email,contact_email,public_profile",
    signedRequest: "rFndHA67......M5MDMifQ",
    userID: "x895xxxxxxx3909",  // this is userID #1
}
status: "connected"
```

Then I call `FB.api` for received userID and I get completely different user ID:

```
"id": "x304xxxxxxx3177", // different user ID
"name": "John Doe",
"first_name": "John",
"last_name": "Doe",
"age_range": {
    "min": 21
},
"link": "https://www.facebook.com/app_scoped_user_id/x304xxxxxxx3177/",
"gender": "male",
"locale": "en_US",
"timezone": 8,
"updated_time": "2017-02-03T17:34:27+0000",
"verified": true
```

How is it possible? How to conquer it?
The real user id is the second one, it is in a url for user profile:
> https://www.facebook.com/profile.php?id=x304xxxxxxx3177

Here is my full request flow:
```
FB.getLoginStatus(status => {
    if(status.status == 'connected') {

        // Here FB sends one userID
        // status.authResponse.userID == x895xxxxxxx3909

        FB.api('/' + status.authResponse.userID, 'get', {fields: '...'},
        response => {

            // And here FB sends different userID for the same user
            // response.id == x304xxxxxxx3177
        }
    }
})
```

SO question http://stackoverflow.com/questions/42568726/in-fb-api-one-fb-user-has-two-different-userids-how-is-it-possible-how-to-deal

**Comment by yguedidi** [comment]
@wzup this repository is about the PHP SDK, so I'm closing it. Hope you'll get a response on SO.
