### ISSUE TITLE
needs more recent php version than declared

### ISSUE THREAD

**Issue by LucaRainone** [facebook/php-graph-sdk#753]
The function `hash_equals` used here:
https://github.com/facebook/php-graph-sdk/blob/5.4/src/Facebook/Helpers/FacebookRedirectLoginHelper.php#L247

is available only on PHP 5.6 (http://php.net/manual/en/function.hash-equals.php)

Please provide a fallback function or update the `.readme` and `composer.json` (actually declared for PHP 5.4+)

**Comment by SammyK** [comment]
There's a [polyfill](https://github.com/facebook/php-graph-sdk/blob/5.4/src/Facebook/polyfills.php#L28-L49) for that. ;)
