### ISSUE TITLE
Using @returns instead of @return causes trouble

### ISSUE THREAD

**Issue by barnslig** [facebook/php-graph-sdk#757]
Hello,

I am getting the following error from using your SDK version 5.4.4 in a project with doctrine (shortened):

```
  Uncaught Exception: Doctrine\Common\Annotations\AnnotationException
  
  Message
    [Semantical Error] The annotation "@returns" in method
    Facebook\SignedRequest::split() was never imported. Did you maybe
  forget
    to add a "use" statement for this annotation?

  […]
```

The error can be easily fixed by using @return instead of @returns, [as proposed by phpdoc](https://phpdoc.org/docs/latest/references/phpdoc/tags/return.html). I guess you just mixed up with jsdoc :wink:

In particular, the problem occures at the following positions:

`src/Facebook/SignedRequest.php`:
- [L167](https://github.com/facebook/php-graph-sdk/blob/5.4/src/Facebook/SignedRequest.php#L167)
- [L185](https://github.com/facebook/php-graph-sdk/blob/5.4/src/Facebook/SignedRequest.php#L185)
- [L205](https://github.com/facebook/php-graph-sdk/blob/5.4/src/Facebook/SignedRequest.php#L205)

Please replace those.

**Comment by yguedidi** [comment]
Thanks @barnslig! Can you send a pull request? :)
