### ISSUE TITLE
Application name next to FB post

### ISSUE THREAD

**Issue by jaketoolson** [facebook/php-graph-sdk#760]
I can't seem to find help anywhere on this topic - We've integrated your SDK in to our web-based application and FB has approved our use.  I can't seem to figure out, how do I get FB to show our application name next to the posting?  I'm curious if this is somehow an extra parameter that needs to be passed via the SDK or something.  

Example of what I'm looking to do : 
<img width="208" alt="screenshot 2017-03-23 18 18 09" src="https://cloud.githubusercontent.com/assets/612332/24276637/43d55f76-0ff5-11e7-8419-747ada5f8920.png">

**Comment by yguedidi** [comment]
Thank you for using the Facebook PHP SDK!

If you need help about using it, you should ask your questions on [StackOverflow](https://stackoverflow.com/) and tag them with the `facebook-php-sdk` tag.

So I'm closing this, but if you found a bug in the SDK or think about a feature, feel free to open a new GitHub issues.
