### ISSUE TITLE
Need adding sumary field at the end of responses

### ISSUE THREAD

**Issue by dalmatele** [facebook/php-graph-sdk#762]
We need to get a lot of data from Facebook Graph, for example: Adsets' information. And we use paging mechanism, of course. But we can not know size of data, can not know when we reach the end of our data.
Can you add new field at the end of each response, such as the number page of data?

**Comment by yguedidi** [comment]
Thank you for using the Facebook PHP SDK!

If you need help about using it, you should ask your questions on [StackOverflow](https://stackoverflow.com/) and tag them with the `facebook-php-sdk` tag.

So I'm closing this, but if you found a bug in the SDK or think about a feature, feel free to open a new GitHub issues.
