### ISSUE TITLE
Campaign Copies

### ISSUE THREAD

**Issue by nicolangr** [facebook/php-graph-sdk#764]
Hi all,

i'm facing an issue when trying to create a campaign copy. Calling this API:

`POST /<CAMPAIGN-ID>/copies`

using a campaign id in my business manager i recevie this error:

`(#275) Cannot determine the target object for this request. Currently supported objects include ad account, business account and associated objects. **  ** `

May i do others step before calling copies on campaign?
Thanks

Nicola

**Comment by clin407** [comment]
@nicolangr did you ever figure this out? I'm having the same issue (although I'm trying to copy adsets).

**Comment by yguedidi** [comment]
Thank you for using the Facebook PHP SDK!

If you need help about using it, you should ask your questions on [StackOverflow](https://stackoverflow.com/) and tag them with the `facebook-php-sdk` tag.

So I'm closing this, but if you found a bug in the SDK or think about a feature, feel free to open a new GitHub issues.
