### ISSUE TITLE
Extended Token generation only works on once

### ISSUE THREAD

**Issue by adamellsworth** [facebook/php-graph-sdk#765]
When a user authorizes our application and logs in for the first time we invoke the following with the resultant short-term token and are able to get a valid long-term token in return:

```php
$oAuth2Client = $fb->getOAuth2Client();
$longLivedAccessToken = $oAuth2Client->getLongLivedAccessToken(
  $accessToken
);
```

However, when we try to exchange any subsequent short-term tokens for a user after they log in again (for whatever reason), we're given a weird data response:

`https://graph.facebook.com/v2.8/debug_token?access_token=...&input_token=...`

```php
{
	"data": {
		"app_id": "###",
		"application": "Our Company",
		"expires_at": 0,
		"is_valid": true,
		"issued_at": 1492043004,
		"scopes": [
			"user_events",
			"user_videos",
			"user_friends",
			"email",
			"publish_actions",
			"user_managed_groups",
			"manage_pages",
			"publish_pages",
			"public_profile"
		],
		"user_id": "###"
	}
}
```

Consequently, the following outputs are given for all short-term tokens after the initial one.

```php
return array(
  'extendedToken'  => $longLivedAccessToken->getValue(), // TOKEN_STRING...
  'isLongLived'    => $longLivedAccessToken->isLongLived(), // false
  'expiresAt'      => $longLivedAccessToken->getExpiresAt(), // null
  'isExpired'      => $longLivedAccessToken->isExpired() // null
);
```

I'm not sure if this is the desired functionality or not, but I can't find any documentation which states otherwise.

**Comment by adamellsworth** [comment]
https://developers.facebook.com/bugs/1438835209524230/

**Comment by yguedidi** [comment]
Thank you for using the Facebook PHP SDK!

If you need help about using it, you should ask your questions on [StackOverflow](https://stackoverflow.com/) and tag them with the `facebook-php-sdk` tag.

So I'm closing this, but if you found a bug in the SDK or think about a feature, feel free to open a new GitHub issues.
