### ISSUE TITLE
How to get facebook profile picture from username?

### ISSUE THREAD

**Issue by byseto** [facebook/php-graph-sdk#767]
Hello, im trying to get an user profile picture from username but i cant. I only make it from ID but most people dont know how to get their ids.
I need two files. See code for example.

https://pastebin.com/SWNJyRms

**Comment by vivekpan27** [comment]
As much as I know, it is only possible to get the profile picture of a person if they have permitted your app to access their profile details.

**Comment by yguedidi** [comment]
Thank you for using the Facebook PHP SDK!

If you need help about using it, you should ask your questions on [StackOverflow](https://stackoverflow.com/) and tag them with the `facebook-php-sdk` tag.

So I'm closing this, but if you found a bug in the SDK or think about a feature, feel free to open a new GitHub issues.
