### ISSUE TITLE
Converted from v2.5 to v2.7, "phpGraph returned an error: Error validating application. Application has been deleted."

### ISSUE THREAD

**Issue by gazmendj** [facebook/php-graph-sdk#770]
Hi,

My app was automatically converted to 2.7 and it simply doesn't work and is displaying error 'phpGraph returned an error: Error validating application. Application has been deleted.'.

On the other side app is active on developors facebook page and nothing seems to be wrong from there!!! 

Anyone knows what is happening ???

**Comment by tolbon** [comment]
What do you mean by automatically update ?? 

Your call is always in 2.5 version ? Or 2.7 and more ?

**Comment by yguedidi** [comment]
Thank you for using the Facebook PHP SDK!

If you need help about using it, you should ask your questions on [StackOverflow](https://stackoverflow.com/) and tag them with the `facebook-php-sdk` tag.

So I'm closing this, but if you found a bug in the SDK or think about a feature, feel free to open a new GitHub issues.
