### ISSUE TITLE
email return null for public email

### ISSUE THREAD

**Issue by gaurvivek** [facebook/php-graph-sdk#771]
it returns email only for sdk registered user and return null for all users even if i login using email.
$response = $fb->get('/me?fields=id,name,first_name,last_name,email,gender,education,birthday,location,picture,link', $accessToken);

but it returns null except my registered account.

**Comment by tolbon** [comment]
Do you check the user permission "email" ?
You can only access email address of user who accept your app and your permission email.
email is sensible information.

**Comment by gaurvivek** [comment]
I am doing this
$accessToken = $helper->getAccessToken();
 $response = $fb->get('/me?fields=id,name,first_name,last_name,email,gender,education,birthday,location,picture,link', $accessToken);

what should i do now? How to set permission.

**Comment by tolbon** [comment]
Do you have check email permission in your app dashboard -> app review ?

**Comment by gaurvivek** [comment]
yes I did. It shows green signal near email.
I am adding here sniffed of my app page review
![pb](https://cloud.githubusercontent.com/assets/8137394/25947635/ec6874a4-366d-11e7-82b1-612c7105a871.png)

What anything else should I do?

**Comment by tolbon** [comment]
Did you try with your app in Graph API Explorer ?

**Comment by gaurvivek** [comment]
I am getting my own email not others.
And Graph API Explorer works only for registered api accounts. (As i seen)

**Comment by tolbon** [comment]
You can only access email address of user who accept your app and your permission email.

**Comment by gaurvivek** [comment]
But when i log in with another account, it doesn't ask for permission.

**Comment by gaurvivek** [comment]
Here is sniffed of page when i first time login
![fb1](https://cloud.githubusercontent.com/assets/8137394/25982678/213080e4-36fc-11e7-9e71-61e67d036aad.png)

this is full list of permission and it doesn't ask for email.

![fb2](https://cloud.githubusercontent.com/assets/8137394/25982679/21326e86-36fc-11e7-8a2d-dcb3b6e5d69d.png)

**Comment by tolbon** [comment]
That's weird, I don't know. But that's the reason why you didn't have email. I prefer you ask on [FbDevelopers Groups](https://www.facebook.com/groups/fbdevelopers/) and close this ticket cause it's not a bug of sdk.

Thanks and sorry for didn't help you :(

**Comment by gaurvivek** [comment]
Already did.....here
https://developers.facebook.com/bugs/241915622947783/
they recommended to notify here.

**Comment by tolbon** [comment]
Why you don't say that before ...

**Comment by tolbon** [comment]
Can you post here the encoded body and decoded body of the request when it's null ?
$response->getBody()

This is for all of your account you test ?

**Comment by tolbon** [comment]
`GET https://graph.facebook.com/USER_ID/permissions?access_token=USER_ACCESS_TOKEN`

What the result of that request in curl or php sdk ?

**Comment by gaurvivek** [comment]
I found the solution. I haven't add proper permissions. Thank you for helping.

**Comment by bopoda** [comment]
> I found the solution. I haven't add proper permissions. Thank you for helping.

Hi @gaurvivek, What do you mean?

**Comment by mantissefr** [comment]
Hi guys, I have to tell you a story following gaurvivek issue.

At a time, you could easily import your Facebook friends as name,email list in Yahoo contacts, of course, only friends who had a public email in their settings.

That's what I did with hundreds of friends I added from Groups I liked and wanted to work with.

I had a list of more than a thousand emails in few months thanks to this list (what a Facebook app can do).

I sent emails to my friends list, and an infopreneur answered me it is spam. I had further complaints about me being a hacker and was sacked of a Facebook group with no politeness.

I tried to explain that as we are friends on Facebook it is some kind of agreement to send an email and moreover, it is a public email on their Facebook about Page.

Nobody really knows if it is ok to get and send emails to their friends thanks to Facebook. Personnaly, I think that if Facebook allows it though the API, it is ok. Moreover, Facebook is now worldwide compliant with recent GDPR laws.

Whatever is possible through Facebook API is legal or permitted, that's what I wanted to say.

I love coding and I still do, but I am more into marketing now.

Cheers to the PHP-SDK for Facebook band !

All the best from France.

**Comment by tolbon** [comment]
Donc si tu me donnes ton e-mail j ai le droit de te spammer ? On peux voir ça comme je suis ami avec toi tu laisses tes clés sur ta voiture j ai le droit de la conduire du coup ?
Après c est un email public du coup j ai droit de le spam. Non !
Oui mais on est amis sur Facebook. Perso a mes amis je les spams pas. au pire peut être t introduire via messenger ou via les groupes pour demander qui voudrait bosser avec toi.
La gdpr est plus ou moins clair si tu n’a pas de la personne explicitement pour utiliser son email pour envoyer du démarchage tu es amendable sous le coup de la gdpr.

**Comment by mantissefr** [comment]
C'est quoi l'intérêt de partager son email publiquement si on n'a pas le
droit de l'utiliser ? C'est pas logique.

Pour le parallèle de la voiture, c'est pas ça. La clé de ma voiture, c'est
mon mot de passe pour accéder à mon compte email. Si tu m'écris, c'est que
tu es passager et qu'on discute ensemble.

Ton idée, c'est plus si je te donne mon mot de passe.

Pour moi, envoyer du pourriel, c'est envoyer du contenu sans aucun rapport
avec la relation que j'entretiens avec la personne à qui je m'adresse. Ou
alors, faire du piratage.

C'est un débat sans fin, cette histoire de courriels publiques sur Facebook.

Salut.

**Comment by vmolo4nik** [comment]
### asdasdasda

> _**asdasdas**_

**Comment by vmolo4nik** [comment]
### 

> [`****`](`

- 

- [ ] @1. url

`)

**Comment by gaurvivek** [comment]
Hi @mantissefr , Thats not my story as I already mentioned above that I am not even getting pubic emails from facebook sdk.

**Comment by mantissefr** [comment]
Hi @gaurvivek that's because now Facebook is GDPR compliant.

**Comment by mantissefr** [comment]
However, you can get an email with a facebook login button for example, by asking permission to retrieve it !

**Comment by alexander0205** [comment]
Hey guys I found the problem, taking long time find that, the problem result is you need set 'public_profile','email' this scope.
public_profile: is basic information of the user.
but 
email: is only the email of the user.

**Comment by haris-aqeel** [comment]
Hello I am getting photoURL but not able to see my profile picture in it. PhotoURL link is https://graph.facebook.com/1382654505272071/picture
