### ISSUE TITLE
Field "stop_time" is not cast to DateTime

### ISSUE THREAD

**Issue by janhapke** [facebook/php-graph-sdk#774]
I am reading Campaign Objects from the Marketing API:

https://developers.facebook.com/docs/marketing-api/reference/ad-campaign-group

These Objects contain (among others) the fields `created_time`, `updated_time`, `start_time` and `stop_time`. All of them are returned as DateTime Objects from the Graph SDK, except the `stop_time`, which is a string.

I would expect the `stop_time` to be a DateTime object as well.

I believe the responsible code is this:
https://github.com/facebook/php-graph-sdk/blob/master/src/Facebook/GraphNodes/GraphNode.php#L136-L155

**Comment by yguedidi** [comment]
CLosing as #777 is merged
