### ISSUE TITLE
Fatal error: Call to a member function post() on null

### ISSUE THREAD

**Issue by wafiamustafa** [facebook/php-graph-sdk#775]
facebook object return with null in 

my path is 
             folder root
                                    sub folder
                                               facebooksdk folder  beside it my code in same level
define('FACEBOOK_SDK_V4_SRC_DIR', __DIR__.'/facebook-sdk/src/Facebook/');
require_once(__DIR__.'/facebook-sdk/src/Facebook/autoload.php');
// FB configs 
$config = array();
$config['app_id'] = 'xxxxxxxxxxxxxxx';
$config['app_secret'] = 'yyyyyyyyyyyyyyyyyyyy';
 $config['default_graph_version'] = 'v2.2';
$fb = new Facebook\Facebook($config);

**Comment by tolbon** [comment]
FYI 2.2 graph version is not more supported

https://developers.facebook.com/docs/apps/changelog

**Comment by yguedidi** [comment]
Thank you for using the Facebook PHP SDK!

If you need help about using it, you should ask your questions on [StackOverflow](https://stackoverflow.com/) and tag them with the `facebook-php-sdk` tag.

So I'm closing this, but if you found a bug in the SDK or think about a feature, feel free to open a new GitHub issues.
