### ISSUE TITLE
Unable to convert response from Graph to a GraphEdge because the response does not look like a GraphEdge

### ISSUE THREAD

**Issue by hfuccillo** [facebook/php-graph-sdk#781]
Using the lastest API Graph I'm getting this error: 
Unable to convert response from Graph to a GraphEdge because the response does not look like a GraphEdge. Try using GraphNodeFactory::makeGraphNode() instead.
I need the GraphEdge in order to use the pagination methods.

This works fine:
`$fb = app(SammyK\LaravelFacebookSdk\LaravelFacebookSdk::class);`
`$response = $fb->get('/'.$page.'/feed?limit=100', $token);`
`$posts = $response->getGraphEdge();`

Whit this request I'm getting the error:
`$fb = app(SammyK\LaravelFacebookSdk\LaravelFacebookSdk::class);`
`$response = $fb->get('/'.$page.'/?fields=posts{id,story,message,likes.limit(0).summary(true),comments.limit(0).summary(true), shares}&limit=100', $token);`
`$posts = $response->getGraphEdge();`

Any ideas?
Thanks in advance!

**Comment by tolbon** [comment]
Cause "/feed" is an Edge of Node $page
But when you ask only $page?fields=....... You ask for a Node.

Try with a getGraphNode()

**Comment by hfuccillo** [comment]
Thanks, @tolbon!  You save my day! 
It works!

**Comment by SammyK** [comment]
Thanks for chiming in on this one @tolbon! :)
