### ISSUE TITLE
 Serialization of 'Closure' is not allowed in session

### ISSUE THREAD

**Issue by saurabhaec** [facebook/php-graph-sdk#782]
I am getting this issues when i use this sdk in drupal  custom module without this everything is working fine 

Code :

  use \Facebook\Facebook;

  $this->fb = new Facebook([
      'app_id' => 'xxxxx',
      'app_secret' => 'xxxxx',
      'default_graph_version' => 'v2.5',
    ]); 

Error : 

The website encountered an unexpected error. Please try again later.
Exception: Serialization of 'Closure' is not allowed in session_write_close() (line 226 of vendor/symfony/http-foundation/Session/Storage/NativeSessionStorage.php).
session_write_close() (Line: 226)
Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage->save() (Line: 197)
Drupal\Core\Session\SessionManager->save() (Line: 181)
Symfony\Component\HttpFoundation\Session\Session->save() (Line: 60)
Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 99)
Drupal\page_cache\StackMiddleware\PageCache->pass(Object, 1, 1) (Line: 78)
Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 50)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 23)
Stack\StackedHttpKernel->handle(Object, 1, 1) (Line: 656)
Drupal\Core\DrupalKernel->handle(Object) (Line: 20)

**Comment by tolbon** [comment]
I think you try to save this object in session ?

**Comment by yguedidi** [comment]
@saurabhaec I think @tolbon is right, so it's not a SDK issue, closing it.
