### ISSUE TITLE
SSL operation failed with code 1. OpenSSL Error messages: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol

### ISSUE THREAD

**Issue by Siddharth22** [facebook/php-graph-sdk#783]
First all of I am new with server configuration. My issue is when I am using local-machine in which OpenSSl and ssl certificate is not installed....then my code upload image successfully on Facebook Via using Facebook SDK for PHP.

But When I upload same code on Server where ssl enable and https working fine then my code showing me error :-

 Warning: fopen(): SSL operation failed with code 1. OpenSSL Error messages:
error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol 

at ErrorHandler ->handleError ('2', 'fopen(): SSL operation failed with code 1. OpenSSL Error messages: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol', '/facebook/php-sdk-v4/src/Facebook/FileUpload/FacebookFile.php', '91', array())
I don't know what's going wrong. Is it any server configuration issue or anything else ?

My machine PHP version is:- PHP 5.5.9-1ubuntu4.20 (cli) My server PHP version is :- PHP 5.6.11-1ubuntu3.4 (cli)

**Comment by tolbon** [comment]
Did you see this post ? http://stackoverflow.com/questions/15166950/unable-to-establish-ssl-connection-how-do-i-fix-my-ssl-cert/15168180#15168180

**Comment by yguedidi** [comment]
Thank you for using the Facebook PHP SDK!

If you need help about using it, you should ask your questions on [StackOverflow](https://stackoverflow.com/) and tag them with the `facebook-php-sdk` tag.

So I'm closing this, but if you found a bug in the SDK or think about a feature, feel free to open a new GitHub issues.

PS: thanks @tolbon!

**Comment by saubhagya777** [comment]
# ddaaaa
