### ISSUE TITLE
How can I get page token and post on page as a page

### ISSUE THREAD

**Issue by severin-bruhat** [facebook/php-graph-sdk#785]
Hi,

I think everything is in the title ;)
How can I get page token and post on page as a page ?

Cheers

**Comment by tolbon** [comment]
If you read the documentation 
`https://developers.facebook.com/docs/graph-api/reference/page/feed#publish`
You see :
> A page access token with publish_pages permission can be used to publish new posts on behalf of that page. Posts will appear in the voice of the page.

So if add permission manage_page & publish_pages. And when user accept your app you request for 
`{USER_ID}/accounts`

and you see page have access_token variable so you use this value when you publish

Thx

**Comment by severin-bruhat** [comment]
Thanks,

But how can I get the page access token with the API so I can pass it to the function $fb->post() ?

Thx

**Comment by severin-bruhat** [comment]
I have just found the solution. Here it is 👍 $fb = new \Facebook\Facebook([
            'app_id' => 'XXXXXXXXXXX', //TODO  change
            'app_secret' => 'yyyyyyyyyyyyyyyyyyy', //TODO  change
            'default_graph_version' => 'v2.9',
        ]);

        $linkData = [
            'link' => 'http://google.com', //TODO  change
            'message' => "My message", //TODO  change
        ];

        try {
          $pageId = '0000000000'; //id of the page you want to publish on
          $longLivedToken = $fb->getOAuth2Client()->getLongLivedAccessToken('user_access_token'); //TODO  change
          $fb->setDefaultAccessToken($longLivedToken);
          $response = $fb->sendRequest('GET', $pageId, ['fields' => 'access_token'])
              ->getDecodedBody();

          $foreverPageAccessToken = $response['access_token'];
          $fb->setDefaultAccessToken($foreverPageAccessToken);
          $response = $fb->post('/$pageId/feed', $linkData);
