### ISSUE TITLE
[6.0] Require PHP 7.0 or greater

### ISSUE THREAD

**Issue by SammyK** [facebook/php-graph-sdk#787]
I know we've discussed supporting PHP 5.6 in the next version of the PHP SDK, but since PHP 5.6 is in ["security fixes only"](http://php.net/supported-versions.php) mode, we should consider requiring PHP 7.0 in version 6 of the PHP SDK.

*But wait! Lots of people are still on 5.6!* Yes, which is why we should put v5 of the PHP SDK in the same support mode as PHP 5.6 (security fixes only). We could maintain v5 with security support until PHP 5.6 is EOL on *Dec 31st, 2018*.

With requiring PHP 7.0 and greater we can take advantage of scalar type hints & return values thus giving us the flexibility to continually improve the SDK with static analysis tools. This requirement will also allow us to drop the CSPRNG dependency entirely.

There seems to be a movement of widely-used packages starting to require PHP 7 for their latest versions while maintaining support for PHP 5.6 until it's EOL. This is a great change in pace from previous PHP upgrades. Let's join them in this important movement! :)

**Comment by chancegarcia** [comment]
+1

**Comment by tolbon** [comment]
I think it's a very good idea. But SDK use some nullable type. I have started to migrate 5.6 to 7.0 for sdk but cause of use nullable some points are painfull so I suggest PHP 7.1 for skip pain and cry :) and it's easy way. But I think too newest release no ?

**Comment by yguedidi** [comment]
👍 for 7.1!!

**Comment by yguedidi** [comment]
@SammyK OK for 7.1? I think you are... :)

**Comment by SammyK** [comment]
Just linking these - I left my comments on #809, but yes I'm in favor. :)

**Comment by SammyK** [comment]
Closed via #813
