### ISSUE TITLE
Get "access token" empty

### ISSUE THREAD

**Issue by ZherebcovSergey** [facebook/php-graph-sdk#788]
Hi!

I tried to authorize the user through the API and have a problem. An example of which he did was 

[here](https://github.com/facebook/php-graph-sdk/blob/5.5/docs/examples/facebook_login.md.) 

I get "access token" empty. The application itself is configured correctly in the Facebook Developer Console. This application is available to all users. After redirecting to the page of the Facebook "authorization window with permission rights" appears, and after consent the application falls into the list of applications account Facebook.
On the response page, the script goes to the condition accessToken checking and "Bad request" then.

The code after the redirect I get 
`?code=blablabla`

`composer require facebook/graph-sdk`
In composer.json I get 
`"facebook/graph-sdk": "^5.5"`

All fine there.

```
php -v
PHP 5.6.20-1~dotdeb+7.1 (cli) (built: Apr  1 2016 04:14:49)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
```

**Comment by yguedidi** [comment]
Thank you for using the Facebook PHP SDK!

If you need help about using it, you should ask your questions on [StackOverflow](https://stackoverflow.com/) and tag them with the `facebook-php-sdk` tag.

So I'm closing this, but if you found a bug in the SDK or think about a feature, feel free to open a new GitHub issues.
