### ISSUE TITLE
Call to undefined method Facebook\FacebookRequest::execute

### ISSUE THREAD

**Issue by aloha1003** [facebook/php-graph-sdk#793]
FacebookRequest  not found any function  named : execute() ,   document  not update ?

**Comment by yguedidi** [comment]
Thank you for using the Facebook PHP SDK!

If you need help about using it, you should ask your questions on [StackOverflow](https://stackoverflow.com/) and tag them with the `facebook-php-sdk` tag.

So I'm closing this, but if you found a bug in the SDK or think about a feature, feel free to open a new GitHub issues.
