### ISSUE TITLE
"Unknown has occured" in authentication out of sudden

### ISSUE THREAD

**Issue by peci1** [facebook/php-graph-sdk#794]
My app was working for quite long without problems. Today, I started seeing this kind of exception when accessing some (but not all) API functions:

    Facebook\FacebookResponse(6) ▼ {
       "httpStatusCode" protected => 500
       "headers" protected => array(14) ► 
       "body" protected => "{"error":{"message":"An unknown error has occurred.","type":"OAuthException","code":1,"fbtrace_id":"FaG0tDK3mOp"}}" (114)
       "decodedBody" protected => array(1) ▼ {
          "error" => array(4) ▼ {
             "message" => "An unknown error has occurred." (30)
             "type" => "OAuthException" (14)
             "code" => 1
             "fbtrace_id" => "FaG0tDK3mOp" (11)
          }
       }
       "request" protected => Facebook\FacebookBatchRequest(11) ► 
       "thrownException" protected => Facebook\Exceptions\FacebookResponseException(9) ► 
    }
    
I've updated Facebook SDK to the latest version (5.5.0), and verified the access token and App ID are correct. The app doesn't seem to be blocked in any way when I go to its FB Developer page.

On that page, I see:

    Facebook Login
    Active Login Users

    Notice
    unknown error
    Notice
    unknown error
    Notice
    unknown error
    
It happens at least in the following part of code:

    $queries[] = $this->fb->request('GET', $id . '?fields=share');
    $rawResult = $this->fb->sendBatchRequest($queries);

**Comment by alright** [comment]
Experiencing the same problem. Simple requests work fine, only batch requests throw error.

**Comment by alright** [comment]
It seems that this problem has been fixed from Facebook side

**Comment by peci1** [comment]
I can confirm that, it also started working again for me.
