### ISSUE TITLE
Error with get method: "Invalid appsecret_proof provied in the API argument

### ISSUE THREAD

**Issue by mvcmaker** [facebook/php-graph-sdk#795]
Hi,
I'm using the SDK for php (v.2.9 version), and I get this error while trying to use the get method from Facebook\Facebook class. Token is valid. 
This is my code from constructor:
`$this->fb = new \Facebook\Facebook([
			'app_id'=>FB::APP_ID,
			'app_secret'=>FB::APP_SECRET,
			'default_graph_version'=>FB::DEFAULT_GRAPH_VERSION,
			//'default_access_token'=>FB::SAMPLE_ACCESS_TOKEN, //Optional
		]);`
It has no sense, this is the code which gets the user information from the accessToken:
`if(is_null($fbToken))
			$fbToken = $this->accessToken;
		$appsecret_proof= hash_hmac('sha256', $fbToken, FB::APP_SECRET);
		try {
		  // Get the \Facebook\GraphNodes\GraphUser object for the current user.
		  // If you provided a 'default_access_token', the '{access-token}' is optional.
		  $response = $this->fb->get('/me?fields=id,name,email', $fbToken);
		} catch(\Facebook\Exceptions\FacebookResponseException $e) {
		  // When Graph returns an error
		  $this->lastError = 'Graph returned an error (accessToken ' . $fbToken . '): ' . $e->getMessage();
		  return false;
		} catch(\Facebook\Exceptions\FacebookSDKException $e) {
		  // When validation fails or other local issues
		  $this->lastError = 'Facebook SDK returned an error: ' . $e->getMessage();
		  return false;
		}

		$me = $response->getGraphUser();
		echo 'Logged in as ' . $me->getName();
		return true;`

I've read in the facebook documentation that the appsecret_proof is proved automatically when you use the php sdk. How this is solved?
(see https://developers.facebook.com/docs/graph-api/securing-requests/?locale=en_US)

**Comment by yguedidi** [comment]
Thank you for using the Facebook PHP SDK!

If you need help about using it, you should ask your questions on [StackOverflow](https://stackoverflow.com/) and tag them with the `facebook-php-sdk` tag.

So I'm closing this, but if you found a bug in the SDK or think about a feature, feel free to open a new GitHub issues.
