### ISSUE TITLE
Should I upgrade to 5.x?

### ISSUE THREAD

**Issue by echonox** [facebook/php-graph-sdk#796]
We've got this info from facebook:

Reminder: Graph API v2.3 will be deprecated on July 10, 2017

So our app uses php v4 and Graph API v2.3, so my question is will our app break after July 10?

We use it to import Facebook events

Thanks.

**Comment by yguedidi** [comment]
Thank you for using the Facebook PHP SDK!

If you need help about using it, you should ask your questions on [StackOverflow](https://stackoverflow.com/) and tag them with the `facebook-php-sdk` tag.

So I'm closing this, but if you found a bug in the SDK or think about a feature, feel free to open a new GitHub issues.

**Comment by yguedidi** [comment]
@echonox BTW, it's depends on the API call you do, check the Graph API [Changelog)(https://developers.facebook.com/docs/apps/changelog) or use the Facebook [API Upgrade Tool](https://developers.facebook.com/tools/api_versioning/)
