### ISSUE TITLE
Guzzle http errors when I add facebook graph sdk codeigniter.

### ISSUE THREAD

**Issue by pabloalber84** [facebook/php-graph-sdk#799]
I added facebook graph sdk with composer in codeigniter.
In the past webhosting, works fine, but, I changed to own webhosting (Dedicated server debian 8), and I get this error:
```
<br />
<b>Fatal error</b>:  Unsupported operand types in <b>[URL]/application/third_party/phpseclib/vendor/guzzlehttp/guzzle/src/Client.php</b> on line <b>227</b><br />
```
Line 227:
`        $result = $options + $defaults;`

I called guzzle without facebook php-graph-sdk , and working fine, but when I add facebook php-graph-sdk, this call automatic guzzle, but I receive this error.

Solutions?

**Comment by pabloalber84** [comment]
Fixed, I forgot install php curl :B

**Comment by yguedidi** [comment]
Then I close this :)
