### ISSUE TITLE
Call to undefined method Facebook\FacebookApp::getToken()

### ISSUE THREAD

**Issue by josfaber** [facebook/php-graph-sdk#804]
I'm using the "Simple GET example of a user's profile" and get the error as in the subject. The init of the Facebook\Facebook passes, but the  `$response = $fb->get('/me', '{access-token}');` fails with both my user access token (generated through the graph api explorer) and none supplied.

What am I missing?

my code:
```
require_once 'vendor/autoload.php';
date_default_timezone_set('Europe/Amsterdam');
try {
      $fb = new \Facebook\Facebook([
        'app_id' => '##########',
        'app_secret' => '##########',
        'default_graph_version' => 'v2.9',
      ]);
      $response = $fb->get('/me', '##########');
} catch (FacebookRequestException $ex) {
    echo json_encode(array('error' => $ex->getMessage()));
}
catch (\Exception $ex) {
    echo json_encode(array('error' => $ex->getMessage()));
}  
```  

full error:
```
Fatal error: Call to undefined method Facebook\FacebookApp::getToken() in /Users/######/#####/#######/vendor/facebook/php-sdk-v4/src/Facebook/FacebookRequest.php on line 185
Call Stack
#	Time	Memory	Function	Location
1	0.0004	258544	{main}( )	../facebook_posts.php:0
2	0.0059	612824	Facebook\Facebook->get( )	../facebook_posts.php:18
3	0.0059	613216	Facebook\Facebook->sendRequest( )	../Facebook.php:342
4	0.0059	613288	Facebook\Facebook->request( )	../Facebook.php:467
5	0.0064	653224	Facebook\FacebookRequest->__construct( )	../Facebook.php:545
```

**Comment by reneroboter** [comment]
The error message tells you that the method getToken is undefined. Check your SDK version and compare it with the documentation version did you use. Different version of the the SDK may work little bit different.

**Comment by mvcmaker** [comment]
I think you're using new code from the reference section of Facebook developers web, but you're trying to use this code with an old verion of the sdk. Try to update your sdk version with composer to 5.5 and try again.

**Comment by josfaber** [comment]
Sorry to say the error remains after removing and reinstalling the sdk via composer. The composer.json file sais `"facebook/graph-sdk": "^5.5"`

**Comment by mvcmaker** [comment]
Hi,
I've executed your code in my server, with my php-graph-sdk library, and I get a successfull response (after changing your app_id, app_secret and de accessToken you've hidden). This is my response: 

> object(Facebook\FacebookResponse)#15 (6) {
>   ["httpStatusCode":protected]=>
>   int(200)
>   ["headers":protected]=>
>   array(14) {
>     ["Access-Control-Allow-Origin"]=>
>     string(1) "*"
>     ["ETag"]=>
>     string(42) ""f6a6b285f8719a0948592fdf74ce86314d1b754e""
>     ["Pragma"]=>
>     string(8) "no-cache"
>     ["Cache-Control"]=>
>     string(44) "private, no-cache, no-store, must-revalidate"
>     ["x-fb-rev"]=>
>     string(7) "3125339"
>     ["Content-Type"]=>
>     string(31) "application/json; charset=UTF-8"
>     ["x-fb-trace-id"]=>
>     string(11) "CEsEV2nWpFz"
>     ["facebook-api-version"]=>
>     string(4) "v2.9"
>     ["Expires"]=>
>     string(29) "Sat, 01 Jan 2000 00:00:00 GMT"
>     ["Vary"]=>
>     string(15) "Accept-Encoding"
>     ["X-FB-Debug"]=>
>     string(88) "jmvmXV9mXd2Wn/6UEbzXdPh0FXXlOq3EFrxMW4LHA7BWdtAhxsu0Ey4X01lKKi9hxQejKNKAj4vksf0TMP0hbQ=="
>     ["Date"]=>
>     string(29) "Thu, 29 Jun 2017 11:40:15 GMT"
>     ["Connection"]=>
>     string(10) "keep-alive"
>     ["Content-Length"]=>
>     string(2) "43"
>   }
>   ["body":protected]=>
>   string(43) "{"name":"Juan Juan","id":"224900028028502"}"
>   ["decodedBody":protected]=>
>   array(2) {
>     ["name"]=>
>     string(9) "Juan Juan"
>     ["id"]=>
>     string(15) "224900028028502"
>   }
>   ["request":protected]=>
>   object(Facebook\FacebookRequest)#13 (9) {
>     ["app":protected]=>
>     object(Facebook\FacebookApp)#6 (2) {
>       ["id":protected]=>
>       string(16) "1711102305851052"
>       ["secret":protected]=>
>       string(32) "94f722c8433443384428eecdf925a163"
>     }
>     ["accessToken":protected]=>
>     string(184) "EAAYUPQ0dVqwBAKgDMRr3dxqhT7Ccq4KDpyZB3stnZCWsUVKaTzkoRSbSpG46JCt8db1GPL7hlffuFMMYbMIvwp9ZB5YAcqZAPCMKR5IAxRzdkaxMoP40IFUvEgb319VlISkHqMFeZBZCEAJLpfu8GLvHJs05XRBwkOvDZB7I6p1mt9D5CiwqeAF"
>     ["method":protected]=>
>     string(3) "GET"
>     ["endpoint":protected]=>
>     string(3) "/me"
>     ["headers":protected]=>
>     array(1) {
>       ["Content-Type"]=>
>       string(33) "application/x-www-form-urlencoded"
>     }
>     ["params":protected]=>
>     array(0) {
>     }
>     ["files":protected]=>
>     array(0) {
>     }
>     ["eTag":protected]=>
>     NULL
>     ["graphVersion":protected]=>
>     string(4) "v2.9"
>   }
>   ["thrownException":protected]=>
>   NULL
> }

So sure is a problem with your library. Try to delete completely and install again clean by composer.

**Comment by josfaber** [comment]
You were right Daniel. Turns out there were leftovers from the old 'php-sdk' in the vendor folder, so the wrong classes got called. 

So, my bad, thanks for the help!

**Comment by SammyK** [comment]
@mvcmaker You posted your app secret and an access token in your response. I just edited them out of your reply. I highly recommend you reset your app secret now as anyone can use that to compromise your app.

**Comment by mvcmaker** [comment]
No problem with that, nobody will use it, because is protected by ip address...

**Comment by SammyK** [comment]
@mvcmaker Just because you're having trouble getting it to work doesn't mean no one will use your app to do something malicious. You should still change your app secret. ;)

**Comment by mvcmaker** [comment]
I won't change my private key neither app key, but thanks to remind me.
