### ISSUE TITLE
Can't get expiration date directly from method getExpiresAt()

### ISSUE THREAD

**Issue by mvcmaker** [facebook/php-graph-sdk#805]
Hi,
I'm using a customized method to get the access token expiration date as follows:
```
public function getExpiresAt() {
	$accessToken = new \Facebook\Authentication\AccessToken($this->accessToken);
	return $accessToken->getExpiresAt();
}
```
The problem is that the resturn of this function is always NULL, even when I pass an expired accessToken, because when I launch the get() method just after call this method, I get the en error (generated from a FacebookResponseException) that tells that session was expired at some date and we are now at new date...

What's happening? Why the getExpiresAt method doesn't returns anything but the get methos yes? What's the way to get the real expiration token withou have to analyze by parsing the expection message from the Exception?

**Comment by tolbon** [comment]
Short answer. The long answer come later 

Did you see what the code do ? 

https://github.com/facebook/php-graph-sdk/blob/5.5/src/Facebook/Authentication/AccessToken.php

You see the constructor didn't set the expireAt value if you didn't set it yourself and the getExpireAt is just a simple getter.

I suggest you to use this link
https://developers.facebook.com/docs/graph-api/reference/v2.9/debug_token

**Comment by mvcmaker** [comment]
Thanks! That' great! It worked fine, using the get method by calling the "/debug_token?input_token=....."!
The only problem is that the facebook reference is obsolete, is working on a previous sdk release and the code they post doesn't work, they are based on the session working, while this is not present in current sdk version 5.5.
I was confused with the getExpiredAt() got from the AccessToken class and the real expired at that is got from another way, I don't understand why there are two ways of working with expiration token dates.
One last question: What is the way to extend via sdk the live of the access token? Is there any way to do that?

**Comment by tolbon** [comment]
No It's not obsolete debug_token is always active Why did you say that ? maybe the code of example is deprecated for newer version use **getGraphNode** instead of **getGraphObject**

the expireAt is not a way to get this information, you need to get this information by debug_token, 
or at the connection (<- I need confirmation for this)
, and set this in your class if you need it. it's just POO.

> What is the way to extend via sdk the live of the access token?


If you see that example :
https://developers.facebook.com/docs/php/howto/example_facebook_login
getLongLiveAccess give you a token with 30 days live and died. But with SDK it is impossible to get more than 30 days token. Your user need every 30 days to reconnect to your apps for extends token live

**Comment by mvcmaker** [comment]
@toolbon, I'm sorry to confuse you with my explanation. I didn't mean that the debug_token is osbolete. That's not what I mean. I mean:

> The sample code in Facebook refrence is obsolete, not the url where they references. Facebook samples references to a non existent class in sdk version 5.5 that is Facebook\FacebookSession class.
By the other hand, regarding to the exptend token live by SDK, thanks, it's impossible to doing by sdk to extend token for 30 days. I will make a prove of extend a 60 minutes live token to 30 days by using getLongLiveAccess(). Thanks!

**Comment by tolbon** [comment]
https://developers.facebook.com/docs/facebook-login/access-tokens
If you need lot of more information about token :)

Yeah use getLongLiveAccess() if you need ±30 days token but you can't have more.

**Comment by mvcmaker** [comment]
@tolbon Sorry, I didn't visited the link you gave me, I can extend the token live by using this code, it's not short, but possible. Thanks!

**Comment by yguedidi** [comment]
Thanks @tolbon! @mvcmaker then this can be closed? :)

**Comment by mvcmaker** [comment]
I think yes, it is all, thanks folks!
