### ISSUE TITLE
Unknown SSL protocol error in connection to graph.facebook.com:443

### ISSUE THREAD

**Issue by zohaib055** [facebook/php-graph-sdk#812]
facebook sdk working perfect on the localhost but when i try on my network ip http://192.168.3.9

it gives me  "Unknown SSL protocol error in connection to graph.facebook.com:443" error can anyone 

please help me out what is the cause of this issue and how can it be resolved ?

**Comment by tolbon** [comment]
I think this is not a php facebok sdk error this kind of question is more relevant in StackOverflow ...
but anyway
What versions of PHP and OpenSSL have you got installed?

**Comment by SammyK** [comment]
Thank you for using the Facebook PHP SDK!

If you need assistance using it, you should ask your questions on [StackOverflow](https://stackoverflow.com/) and tag them with the `facebook-php-sdk` tag.

So I'm closing this, but if you find a bug in the SDK or have a feature request, feel free to open a new GitHub issue.
