### ISSUE TITLE
PHP Fatal error: Class 'FacebookRequest' not found

### ISSUE THREAD

**Issue by NorisD** [facebook/php-graph-sdk#816]
Hi!
I checked the file autoload.php and file has been correctly load 

> file Si-> /web/htdocs/.../Facebook/FacebookRequest.php

> 
but if the programm call FacebookRequest class this not found.
I specificed the namespace when created the object  > change errore :  
Call to undefined method Facebook\\FacebookRequest::execute()

**Comment by SammyK** [comment]
Hey @NorisD! Which version of the Facebook PHP SDK are you using? You're referencing v4 syntax which does not exist in v5 (latest stable). If you need further assistance, you should ask your question on [StackOverflow](https://stackoverflow.com/) and tag it with the `facebook-php-sdk` tag. :)
