### ISSUE TITLE
Video upload in chunks stuck with Error 6001:1363037

### ISSUE THREAD

**Issue by neko-fire** [facebook/php-graph-sdk#821]
Hi,

I am using the php-graph-sdk mainly for Video uploads. Everything works well with the samples of the documention besides the video upload in chunks. I've used the selfchunking sample implentation for bigger video files, since the all in one solution dropped an similar error with no debug information. Here some base information:

- 2 sample Video Files with: (4k | ~6min | 2,5GB) and (1080p | 1:41h | ~950MB)
- latest version of the sdk
- user specific valid  token & is a token
- all required permissions granted for the app
- works fine for a long time now with regular post requests for smaller & shorter Videos
- error occurs during upload_phase => transfer

Error for self chunked upload:
`
{
    "error": {
        "message": "There was a problem uploading your video. Please try again.",
        "type": "OAuthException",
        "code": 6001,
        "error_data": {
            "start_offset": 535822336,
            "end_offset": 541065216
        },
        "error_subcode": 1363037,
        "is_transient": false,
        "error_user_title": "Error Uploading Video",
        "error_user_msg": "There was a problem uploading your video. Please try uploading it again.",
        "fbtrace_id": "C4uavwiF1dQ"
    }
`
Error for all in one:
`Graph returned an error: There was a problem uploading your video. Please try again.`

This happens most of the time stopping at a random chunk. Sometimes the upload is successful. I've tried to increase the retry rate up to 1000 with no luck. The upload stopped at chunks:
File1:
CHUNK175
CHUNK45
CHUNK95
CHUNK52
CHUNK61
CHUNK190
CHUNK178

File2:
CHUNK99
CHUNK267
CHUNK102
CHUNK122
CHUNK182

Any idea why this happens?

cheers

**Comment by SammyK** [comment]
Hey @neko-fire!

It seems that each of your video examples exceed the resumable video upload limitations: https://developers.facebook.com/docs/graph-api/video-uploads#nonresumable

You first one exceeds the **2 GB** maximum size and the second one exceeds the **20 mins** max play time. Feel free to open a new issue if you're having this problem with videos under 2GB and under 20 mins long. :)

**Comment by SammyK** [comment]
Oops! My bad. I looked at the wrong part of the docs. Resumable supports **10 GB** and **4 hours**. Whoa! :)

https://developers.facebook.com/docs/graph-api/video-uploads#resumable

Re-opening to investigate further. FWIW, on error `1363037`:

> Returned when the server receives an invalid start offset from the client. Try to parse the start_offset and end_offset from error message and do a retry again.

@yguedidi You have any thoughts on this one? Maybe we need to check for `error_data. start_offset` when this specific subcode is returned?

**Comment by yguedidi** [comment]
@neko-fire do you still encounter this error?
The fact that the error happen on random chunk makes me think it's a Graph error, so all you can do is retry to upload that chunk (which is the goal of resumable uploads haha).

**Comment by neko-fire** [comment]
@yguedidi This error didn't occur for a couple of months now. I think keeping the SDK always up to date has solved it :)

**Comment by yguedidi** [comment]
@neko-fire thanks! :)

**Comment by usamamashkoor** [comment]
is their a way we can show the progress bar while doing resume able video uploads...?
