### ISSUE TITLE
SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

### ISSUE THREAD

**Issue by junaidatique** [facebook/php-graph-sdk#822]
Hi,

I am using v5.5 and I am getting following error.

Message:  fopen(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed on Filename: FileUpload/FacebookFile.php Line Number: 91.

I am trying to upload an image to album from URL.

Please help.

**Comment by SammyK** [comment]
Hey @junaidatique!

How are you trying to upload the remote image? You should use the `url` instead of `source` field. So instead of doing this:

```php
$data = [
  'message' => 'Test photo from HTTPS',
  'source' => $fb->fileToUpload('https://sammyk.s3.amazonaws.com/blog/og_images/a9537d16d1788f212fa80d9ad8215cd1.jpeg'),
];
$response = $fb->post($albumId.'/photos', $data, $accessToken);
```

You should do this instead:

```php
$data = [
  'message' => 'Test photo from HTTPS',
  'url' => 'https://sammyk.s3.amazonaws.com/blog/og_images/a9537d16d1788f212fa80d9ad8215cd1.jpeg',
];
$response = $fb->post($albumId.'/photos', $data, $accessToken);
```

More info on the /album/photos edge: https://developers.facebook.com/docs/graph-api/reference/v2.10/album/photos#publish

**Comment by sanket-rebelute** [comment]
No even url parameter gives same error.
