### ISSUE TITLE
FacebookResponseException code 100 generated with generated access tokens for testing

### ISSUE THREAD

**Issue by mvcmaker** [facebook/php-graph-sdk#823]
Hello,
I get the next exception (Facebook\Exceptions\FacebookResponseException) while trying to use an access token that has been generated with the logged site of developer facebook app with the same app as the app_id I use in the code. The users are the testing users created within the same developer site:

> FaReEx (code 100): (#100) You must provide an app access token or a user access token that is an owner or developer of the app/exception 'Facebook\Exceptions\FacebookAuthenticationException' with message '(#100) You must provide an app access token or a user access token that is an owner or developer of the app' in /var/www/appservices/lib/facebook/src/Facebook/Exceptions/FacebookResponseException.php:106
> Stack trace:
> #0 /var/www/appservices/lib/facebook/src/Facebook/FacebookResponse.php(210): Facebook\Exceptions\FacebookResponseException::create(Object(Facebook\FacebookResponse))
> #1 /var/www/appservices/lib/facebook/src/Facebook/FacebookResponse.php(255): Facebook\FacebookResponse->makeException()
> #2 /var/www/appservices/lib/facebook/src/Facebook/FacebookResponse.php(82): Facebook\FacebookResponse->decodeBody()
> #3 /var/www/appservices/lib/facebook/src/Facebook/FacebookClient.php(225): Facebook\FacebookResponse->__construct(Object(Facebook\FacebookRequest), '{"error":{"mess...', 400, Array)
> #4 /var/www/appservices/lib/facebook/src/Facebook/Facebook.php(469): Facebook\FacebookClient->sendRequest(Object(Facebook\FacebookRequest))
> #5 /var/www/appservices/lib/facebook/src/Facebook/Facebook.php(342): Facebook\Facebook->sendRequest('GET', '/debug_token?in...', Array, NULL, NULL, NULL)
> #6 /var/www/appservices/webservices/facebook/facebook_custom.php(182): Facebook\Facebook->get('/debug_token?in...')
> #7 /var/www/appservices/bin/facebook-drs.php(112): Facebook_custom->debugToken()
> #8 [internal function]: DrsFacebookCli::dumpTokenInfo()
> #9 /var/www/appservices/bin/facebook-drs.php(65): call_user_func('DrsFacebookCli:...')
> #10 {main}

This exception code (100) is not documented in the facebook reference exceptions sections, so I'd like how is the way to create a valid token that is passed through the php sdk without generate this exception.
Is possible a bug from the sdk?

**Comment by SammyK** [comment]
Hey @mvcmaker! Make sure that the test user access token belongs to the app you're using it for (note that test users on the main production app are different than a localhost version of the same app).

As this error is coming from the Graph API and not the Facebook PHP SDK, it is very likely that this is due to a misconfiguration in your implementation code. If you need further assistance with it, you should ask your question on [StackOverflow](https://stackoverflow.com/) and tag it with the `facebook-php-sdk` tag. :)

**Comment by mvcmaker** [comment]
Hi @SammyK You're a little late to write this answer, our company has bankrupcied, so there's no need to solve this yet ;). I'm looking for a new job now. But I can remember since 13th July that this problem was solved and I was able to get the basic information from the access token.
Thanks!

**Comment by SammyK** [comment]
> our company has bankrupcied, so there's no need to solve this yet ;)

Oh noes! Sorry to hear that.

> I'm looking for a new job now. But I can remember since 13th July that this problem was solved and I was able to get the basic information from the access token.

Glad you got it figured out! Good luck on the job hunt! :)

**Comment by tudorppp** [comment]
Hi, can you provide more info about how to solve this issue? There's absolutely no documentation for it :)
