### ISSUE TITLE
Cannot login from HTTPS redirect url on french web hosting OHV.COM because FacebookUrlDetectionHandler failed to detect HTTPS

### ISSUE THREAD

**Issue by solo14000** [facebook/php-graph-sdk#824]
Hi,

Since a few months, facebook login using PHP SDK 5.5 failed from HTTPS website on  the french web hosting OVH.COM

Facebook->getRedirectLoginHelper()->getAccessToken() raises FacebookResponseException with the following message.

> Graph returned an error: Impossible de charger cette URL: Le domaine de cette URL n’est pas inscrit dans ceux de l’application. Pour pouvoir importer cette URL, ajoutez tous les domaines et sous-domaines de votre application au champ Domaines des paramètres de l’application.

The failure comes from the fact I call facebook api using https://my-website/blabla/ redirect URL but facebook SDK resolves it as http://my-website:443/blabla/ (http protocol instead https but with 443 port).

The problem is that OVH provider uses HTTP_X_FORWARDED_PROTO = 'http' with HTTP_X_FORWARDED_PORT = '443' in headers instead of HTTP_X_FORWARDED_PROTO = 'https'.
This leads FacebookUrlDetectionHandler::isBehindSsl() returning false

For now, I fix it overloading  Facebook\Url\FacebookUrlDetectionHandler this way

` protected function isBehindSsl()
	{
		// Validate X_FORWARDED_PROTO = 'http' and X_FORWARDED_PORT = '443'
		($this->getHeader('X_FORWARDED_PROTO') && $this->getHeader('X_FORWARDED_PORT') == '443') ? true : parent::isBehindSsl();
	}
}`

Could you confirm that bug and fix it ?

Thanks

**Comment by bvrignaud** [comment]
Hi,

I am on OVH to, and I have the same problem as you.
My facebook connection works on http but doesn't on https.
Thanks for your patch.

I just done 
```php
protected function isBehindSsl() {
    return true;
}
```
But it isn't a good way.

Thanks

**Comment by solo14000** [comment]
I have open a ticket on OVH asking them to fix the HTTP settings and refering to this facebook sdk issue. Ovh want me to perform some more tests. Personnaly I do not have spare time for these tests. Investigating the bug and making a workaround already take me lots of hours.

**Comment by SammyK** [comment]
Hey @solo14000! Thanks so much for all the hard work digging into this issue!

I did some digging and it appears that looking primarily at the `X-Forwarded-Proto` header to determine HTTP or HTTPS is the "correct" configuration.

As this is a misconfiguration on the web host's end, we can't really apply any patches for this on our end. Hopefully you can convince them to fix their configuration! Good luck! :)
