### ISSUE TITLE
Make default branch 5.x

### ISSUE THREAD

**Issue by SammyK** [facebook/php-graph-sdk#831]
I created a [new branch called 5.x](https://github.com/facebook/php-graph-sdk/tree/5.x) so that we don't have to keep changing the default branch for every minor version bump. So this should be the last default branch change until v6.0 comes out. :)

**Comment by SammyK** [comment]
I'm trying to assign @viv001 to this but you're not showing up in the "Assignees" for some reason.

**Comment by viv001** [comment]
Hi @SammyK, I am not sure what changed but I am not able to see the "Settings" page for this repo. Can you confirm that I am still an admin for it?

**Comment by SammyK** [comment]
Your badge is showing up as "Contributor" for me instead of "Collaborator" or "Admin":

<img width="667" alt="screen shot 2017-08-31 at 3 36 52 pm" src="https://user-images.githubusercontent.com/578780/29944221-3ed2f790-8e62-11e7-8e26-7ad78bc15d38.png">

So I'm guessing not an admin. Doh!

**Comment by gfosco** [comment]
Updated the default branch to 5.x.  Ping me on messenger or email if you need anything in a hurry, sorry for the delay.

**Comment by SammyK** [comment]
Thanks @gfosco! And no worries! Good to see you in the space again :)

**Comment by yguedidi** [comment]
Thanks @gfosco! Happy to see you again too!
