### ISSUE TITLE
Asynchronous request

### ISSUE THREAD

**Issue by VAMPIIRE** [facebook/php-graph-sdk#833]
Can I send an Asynchronous request? I'm using $facebook->post('me/feed', $data); request and I do not need to handle response. Each time, waiting for a response took 3-5 which is not good for me.

**Comment by SammyK** [comment]
Hey @VAMPIIRE!

The Facebook PHP SDK does not natively support async requests (yet!) but you could possibly wrap the request in a Promise if you're making use of an async lib or something. :)
