### ISSUE TITLE
Facebook SDK returned an error: Connection timed out after 10001 milliseconds

### ISSUE THREAD

**Issue by prafullwizorbit** [facebook/php-graph-sdk#834]
Hi
    Facebook SDK returned an error: Connection timed out after 10001 milliseconds while move my code on server .It is written in SDK that this type of error occurs when validation fails or other local issues.But I am unable to understand. I also set ini_set('max_execution_time', 0); for this but error remains the same.
     This is my callback.php code after login redirect uri: 

session_start();
$fb = new Facebook\Facebook([
'app_id' => $app_id, // Replace {app-id} with your app id
'app_secret' => $app_secret,
'default_graph_version' => 'v2.9',
'persistent_data_handler' => 'session'
]); 
 
 $_SESSION['FBRLH_state']=$_GET['state']; 
 
$helper = $fb->getRedirectLoginHelper(); 

try {
 $old_access  =  $accessToken = $helper->getAccessToken();
} catch(Facebook\Exceptions\FacebookResponseException $e) {
  // When Graph returns an error
  echo 'Graph returned an error: ' . $e->getMessage();
  exit;
} catch(Facebook\Exceptions\FacebookSDKException $e) {
  // When validation fails or other local issues
  echo 'Facebook SDK returned an error: ' . $e->getMessage();
  exit;
}

if (! isset($accessToken)) { 
  if ($helper->getError()) {
    header('HTTP/1.0 401 Unauthorized');
    echo "Error: " . $helper->getError() . "\n";
    echo "Error Code: " . $helper->getErrorCode() . "\n";
    echo "Error Reason: " . $helper->getErrorReason() . "\n";
    echo "Error Description: " . $helper->getErrorDescription() . "\n";
  } else {
    header('HTTP/1.0 400 Bad Request');
    echo 'Bad request';
  }
  exit;
}
 
/*echo '<h3>Access Token</h3>';
var_dump($accessToken->getValue());*/
//die();

// The OAuth 2.0 client handler helps us manage access tokens
$oAuth2Client = $fb->getOAuth2Client();

// Get the access token metadata from /debug_token
$tokenMetadata = $oAuth2Client->debugToken($accessToken);
 
// Validation (these will throw FacebookSDKException's when they fail)
$tokenMetadata->validateAppId($app_id); // Replace {app-id} with your app id
// If you know the user ID this access token belongs to, you can validate it here
//$tokenMetadata->validateUserId('123');
$tokenMetadata->validateExpiration();
  
if (! $accessToken->isLongLived()) {	
  // Exchanges a short-lived access token for a long-lived one
  try {
    $accessToken = $oAuth2Client->getLongLivedAccessToken($accessToken);
  } catch (Facebook\Exceptions\FacebookSDKException $e) {
    echo "<p>Error getting long-lived access token: " . $helper->getMessage() . "</p>\n\n";
    exit;
  }

   // '<h3>Long-lived</h3>';
     $final_token = $accessToken->getValue();
}
else{ 
	 $final_token = $old_access;
} 
 
$_SESSION['fb_access_token'] = (string) $final_token; 
this works on localhost but not on server.
Thanks

**Comment by azhard4int** [comment]
+1, we are facing the same issue.

**Comment by SammyK** [comment]
Thank you for using the Facebook PHP SDK!

If you need assistance using it, you should ask your questions on [StackOverflow](https://stackoverflow.com/) and tag them with the `facebook-php-sdk` tag.

So I'm closing this, but if you find a bug in the SDK or have a feature request, feel free to open a new GitHub issue.
