### ISSUE TITLE
This authorization code has been used.

### ISSUE THREAD

**Issue by hrvojebrkasic** [facebook/php-graph-sdk#835]
I'm having big problems with message from title. 
Signup works great, but when I logout and go back to login, I get this message. Code below is where everything happens. Symfony 2.8 is used

`$response = $event->getResponse()->getResponse();

        /** @var User $user */
        $user = $event->getUser();

        $fb = new \Facebook\Facebook([
            'app_id' => $this->fb_app_id,
            'app_secret' => $this->fb_app_secret,
            'default_graph_version' => 'v2.9',
        ]);

        $helper = $fb->getRedirectLoginHelper();

        if (isset($_GET['state'])) {
            $helper->getPersistentDataHandler()->set('state', $_GET['state']);
        }

        try {
                $accessToken = $helper->getAccessToken();
        } catch (FacebookResponseException $e) {
            // When Graph returns an error
            echo 'Graph returned an error: ' . $e->getMessage();
            exit;
        } catch (FacebookSDKException $e) {
            // When validation fails or other local issues
            echo 'Facebook SDK returned an error: ' . $e->getMessage();
            exit;
        }

        if (!isset($accessToken)) {
            if ($helper->getError()) {
                header('HTTP/1.0 401 Unauthorized');
                echo "Error: " . $helper->getError() . "\n";
                echo "Error Code: " . $helper->getErrorCode() . "\n";
                echo "Error Reason: " . $helper->getErrorReason() . "\n";
                echo "Error Description: " . $helper->getErrorDescription() . "\n";
            } else {
                header('HTTP/1.0 400 Bad Request');
                echo 'Bad request';
            }
            exit;
        }

        $oAuth2Client = $fb->getOAuth2Client();

        if (!$accessToken->isLongLived()) {
            // Exchanges a short-lived access token for a long-lived one
            try {
                $accessToken = $oAuth2Client->getLongLivedAccessToken($accessToken);
                $_SESSION['access_token'] = $accessToken;
            } catch (FacebookSDKException $e) {
                echo "<p>Error getting long-lived access token: " . $e->getMessage() . "</p>\n\n";
                exit;
            }
        }

        $user->setFacebookAccessToken((string)$accessToken);

        $this->container->get('fos_user.user_manager')->updateUser($user);`

**Comment by hrvojebrkasic** [comment]
Fixed problem using code below. Fix was loading token from db 

`public function onLogin(SocialLoginEvent $event)
    {
        if ($event->getResponse()->getResourceOwner()->getName() != $this->resourceOwner) return;

        /** @var User $user */
        $user = $event->getUser();

        $fb = new \Facebook\Facebook([
            'app_id' => $this->fb_app_id,
            'app_secret' => $this->fb_app_secret,
            'default_graph_version' => 'v2.9',
        ]);

        $helper = $fb->getRedirectLoginHelper();
        $userAccessToken = $user->getFacebookAccessToken();

        if (isset($_GET['state'])) {
            $helper->getPersistentDataHandler()->set('state', $_GET['state']);
        }

        try {
            if($userAccessToken){
                $accessToken = $userAccessToken;
            } else {
                $accessToken = $helper->getAccessToken();
            }
        } catch (FacebookResponseException $e) {
            // When Graph returns an error
            echo 'Graph returned an error: ' . $e->getMessage();
            exit;
        } catch (FacebookSDKException $e) {
            // When validation fails or other local issues
            echo 'Facebook SDK returned an error: ' . $e->getMessage();
            exit;
        }

        if (!isset($accessToken)) {
            if ($helper->getError()) {
                header('HTTP/1.0 401 Unauthorized');
                echo "Error: " . $helper->getError() . "\n";
                echo "Error Code: " . $helper->getErrorCode() . "\n";
                echo "Error Reason: " . $helper->getErrorReason() . "\n";
                echo "Error Description: " . $helper->getErrorDescription() . "\n";
            } else {
                header('HTTP/1.0 400 Bad Request');
                echo 'Bad request';
            }
            exit;
        }

        if(isset($accessToken)){
            if(isset($userAccessToken)){
                $fb->setDefaultAccessToken($userAccessToken);
            } else {
                $userAccessToken = (string) $accessToken;
                // OAuth 2.0 client handler
                $oAuth2Client = $fb->getOAuth2Client();
                // Exchanges a short-lived access token for a long-lived one
                $longLivedAccessToken = $oAuth2Client->getLongLivedAccessToken($userAccessToken);
                $userAccessToken = (string) $longLivedAccessToken;
                // setting default access token to be used in script
                $fb->setDefaultAccessToken($userAccessToken);
            }
        }

        $user->setFacebookAccessToken((string)$userAccessToken);

        $this->container->get('fos_user.user_manager')->updateUser($user);
    }`

**Comment by hminvozone** [comment]
@hrvojebrkasic bro how you stored the token in the database in the first place?
