### ISSUE TITLE
Not getting long live access token after redirect uri if i login with someone other account

### ISSUE THREAD

**Issue by prafullwizorbit** [facebook/php-graph-sdk#836]
I am not getting someone other's long lived access token using my facebook login because manage_pages permission is not provided from my login account to someone other accounts. Is there any way to get manage_pages permission for any person facebook account from my login.

**Comment by SammyK** [comment]
Hey @prafullwizorbit. The `manage_pages` permission cannot be obtained from a separate user account. The account that you want the permission for has to be the one that grants the permission. :)

**Comment by prafullwizorbit** [comment]
thanks
