### ISSUE TITLE
(#12) singular published story API is deprecated for version v2.4 and higher

### ISSUE THREAD

**Issue by anonymuos1** [facebook/php-graph-sdk#838]
Hi!

I would need some help with this problem. Deleting the post works on localhost but I get this erros message on webhosting server: **(#12) singular published story API is deprecated for version v2.4 and higher**

This is how I've tried deleting (worked on localhost, but none of the on the server)
```
$this->fb->delete("/".$post_id);
$this->fb->delete("/".$post_id, [], $page->access_token);
$this->fb->delete("/".$post_id, [], $page->access_token, null, "v2.10");
```

The default_graph_version is set to v2.10, but I still get an error message for v2.4.  What do you think is the problem? 

Thank you for your help!

**Comment by SammyK** [comment]
Hey @anonymuos1!

1. What does your instantiation of `$this->fb` look like?
2. And what specifically are you trying to delete? A post from a user's timeline?
3. Was the post created by a (test) user or your app?
4. If it's the app, was it created with the localhost app and you are trying to delete it with the production app?

Lots of questions. :)

**Comment by anonymuos1** [comment]
Hello!

Thank you for your anwer!

1. In Slim Framework, the variable for contaner is $this->fb. So that it is available everywhere. This can't be the problem.
2. I tried deleting it from a Facebook page, not from user timeline.
3. The app made the post.
4. I created it on the webhosting server and that is where I tried deleting it.

**Comment by anonymuos1** [comment]
I found the problem eventually. Pretty amature but oh well. On the server for whatever reason varchar 11 field was created for post ID and the data clearly did not fit, so thanks to the false ID it wouldn't delete. On localhost it was set to 255 so there it was good.

**Comment by SammyK** [comment]
Oh yeah! That's bitten me before too. Glad you figured it out & thanks for sharing your solution! :)
