### ISSUE TITLE
Publishing event from page

### ISSUE THREAD

**Issue by dyanakiev** [facebook/php-graph-sdk#841]
Hello,
I need to create event but i dont have any success doing it.
For example some user is logged in my site with their facebook account then i want this user to be able to create event from my site and to publish it on facebook.

How this can happen?

**Comment by mantissefr** [comment]
Hello there,

I find this is a very good question a power user could answer to.

All the best,

José

2017-08-08 16:50 GMT+02:00 Dimitar Yanakiev <notifications@github.com>:

**Comment by dyanakiev** [comment]
Hey, thanks for the reply, unfortunately everything i found about creating event through api says that the api for create event is deprecated, but ev*ntbrite have the ability to create event for their logged users.

**Comment by SammyK** [comment]
Hey @dyanakiev! The Graph API does not support creating events on the events edge: https://developers.facebook.com/docs/graph-api/reference/page/events#Creating I hope you find an alternative solution! :)
