### ISSUE TITLE
FacebookUrlManipulator parse_url() doesn't expect arrays

### ISSUE THREAD

**Issue by mkormendy** [facebook/php-graph-sdk#845]
I'm getting these PHP warnings:

```
PHP Warning:  parse_url() expects parameter 1 to be string, array given in [SDK-path]/Url/FacebookUrlManipulator.php on line 109
PHP Warning:  parse_url() expects parameter 1 to be string, array given in [SDK-path]/Url/FacebookUrlManipulator.php on line 43
```

Seems a little odd, no?

**Comment by tolbon** [comment]
in PHP docs [parse_url](http://php.net/manual/en/function.parse-url.php) first args take a string.

What is the context of use ? It's your code who call ,`getParamsAsArray` or `removeParamsFromUrl`, or SDK internally ?

**Comment by mkormendy** [comment]
I've moved on in a completely different direction my development. I cannot comment any further.
