### ISSUE TITLE
long-lived(60 days) token not working offline

### ISSUE THREAD

**Issue by ManishLSN** [facebook/php-graph-sdk#847]
i am able to get user profile wall post data, but i am getting two issues.

1) I can only fetch data of my profile from that i have created Facebook app.
I gues its because my app is still under development coz i have added some username in my tester list so i can also get their data. so i think so.

2) The token i am generating by this link
https://graph.facebook.com/oauth/access_token?client_id=MYAPPID&client_secret=MYAPPSECRET&grant_type=fb_exchange_token&fb_exchange_token=ACCESS_TOKEN_GETTING_BY_APP_AUTHORIZATION.
is valid for 60 days. but when user logged out on same browser. so i gets error message:
Facebook SDK returned an error: You must provide an access token. / user has been logged out.

**Comment by yguedidi** [comment]
Thank you for using the Facebook PHP SDK!

If you need help about using it, you should ask your questions on [StackOverflow](https://stackoverflow.com/) and tag them with the `facebook-php-sdk` tag.

So I'm closing this, but if you found a bug in the SDK or think about a feature, feel free to open a new GitHub issues.
