### ISSUE TITLE
 Fatalexception 'Facebook\Exceptions\FacebookAuthenticationException' with message 'Fatal' in /workflows/facebook-autoupload/vendor/facebook/php-sdk-v4/src/Facebook/Exceptions/FacebookResponseException.php:131

### ISSUE THREAD

**Issue by SJ04** [facebook/php-graph-sdk#848]
Hello ,

I have also issue with Facebook Graph API, I am Uploading the Video with Graph API and also doing the copyright process for those video but since one of the admin has changed the Main page password , I started to have this error,

```
 php /workflows/facebook-autoupload/index.php

```
Graph returned an error:
  'Facebook\Exceptions\FacebookAuthenticationException' with message 'Fatal' in /workflows/facebook-autoupload/vendor/facebook/php-sdk-v4/src/Facebook/Exceptions/FacebookResponseException.php:131
Stack trace:
#0 /workflows/facebook-autoupload/vendor/facebook/php-sdk-v4/src/Facebook/FacebookResponse.php(210): Facebook\Exceptions\FacebookResponseException::create(Object(Facebook\FacebookResponse))
#1 /workflows/facebook-autoupload/vendor/facebook/php-sdk-v4/src/Facebook/FacebookResponse.php(255): Facebook\FacebookResponse->makeException()
#2 /workflows/facebook-autoupload/vendor/facebook/php-sdk-v4/src/Facebook/FacebookResponse.php(82): Facebook\FacebookResponse->decodeBody()
#3 /workflows/facebook-autoupload/vendor/facebook/php-sdk-v4/src/Facebook/FacebookClient.php(225): Facebook\FacebookResponse->__construct(Object(Facebook\FacebookRequest), '{"error":{"mess...', 400, Array)
#4 /workflows/facebook-autoupload/vendor/facebook/php-sdk-v4/src/Facebook/Facebook.php(469): Facebook\FacebookClient->sendRequest(Object(Facebook\FacebookRequest))
```
```

can i get here some help . 

Thank you.

**Comment by SammyK** [comment]
Hey @SJ04! Once a user changes their password, all access tokens for that user get invalidated a security feature. You'll have to have the user authenticate your app again after changing their password to get a new access token. :)
