### ISSUE TITLE
I don't get every permission granted

### ISSUE THREAD

**Issue by anonymuos1** [facebook/php-graph-sdk#849]
Hi!

The problem I have is that after a while, when logging in, the Facebook does not give the same permissions as the user has. It didn't happen before, I don't know why now.  The login URL has the manage_pages and publish_pages permissions, but after I log in and check the Access token in the debugger (https://developers.facebook.com/tools/debug/accesstoken) in the scopes line there is barely any permission given to the user. Why does it not have all of if what I set? The user who is the administrator of the application can use all functions and has all the permissions, but other users don't. The application is Public. It worked before and everybody could use it according to their permissions and I don't think I changed anything that would ruin this. Thank you for your help in advance!

**Comment by yguedidi** [comment]
Thanks you for using the Facebook PHP SDK!

Looks like this is an error with the Graph API, so it's not related to the SDK... Please ask your question on StackOverflow.
