### ISSUE TITLE
PHP 7.1 - mcrypt_create_iv is deprecated

### ISSUE THREAD

**Issue by ageofandy** [facebook/php-graph-sdk#850]
A PHP Error was encountered

Severity: 8192

Message: Function mcrypt_create_iv() is deprecated

Filename: PseudoRandomString/McryptPseudoRandomStringGenerator.php

Line Number: 57

**Comment by SammyK** [comment]
This was fixed a long time ago. Make sure to update your version of the Facebook PHP SDK.

**Comment by ageofandy** [comment]
Thx Sammy, didn't look in the PseudoRandomStringGeneratorFactory.
