### ISSUE TITLE
When user birthday return only day and month

### ISSUE THREAD

**Issue by huongthu** [facebook/php-graph-sdk#852]
According to the document here [https://developers.facebook.com/docs/graph-api/reference/user](https://developers.facebook.com/docs/graph-api/reference/user) 

> The person's birthday. This is a fixed format string, like MM/DD/YYYY. However, people can control who can see the year they were born separately from the month and day so this string can be only the year (YYYY) or the month + day (MM/DD)

But seems that when privacy popup opens. There is one option that user will provide their birthday or not. I don't see option that user can choose to show their day and month only.

![untitled](https://user-images.githubusercontent.com/10508736/30510982-95c23e46-9af9-11e7-8724-7494d4593be7.png)

Can you suggest me which case the result of birthday returns day and month of birthday only.
Thanks in advance.

**Comment by yguedidi** [comment]
It's in the profile settings, the user can choose to not share his/her year of birth.
