### ISSUE TITLE
long-lived access tokens does not have the expiration date

### ISSUE THREAD

**Issue by jakopo87** [facebook/php-graph-sdk#855]
When you obtain a long lived acces stoken through the OAuth2Client::getLongLivedAccessToken() method, its expiration date is null instead of 60 days

version 5.6.1

**Comment by OwlLaboratory** [comment]
Maybe because you generated an extended token ? With no expiration date.
Check your token on https://developers.facebook.com/tools/debug/accesstoken?q={YOUR_TOKEN}

**Comment by yguedidi** [comment]
Thank you for using the Facebook PHP SDK!

Looks like not an SDK issue but a Graph API one.

So I'm closing this, but if you found a bug in the SDK or think about a feature, feel free to open a new GitHub issues.
