### ISSUE TITLE
Incorrect phpdoc return type for GraphUser->getBirthday()

### ISSUE THREAD

**Issue by julienbornstein** [facebook/php-graph-sdk#857]
Hello 😀
It seems that there's an incorrect return type in phpdoc In src/Facebook/GraphNodes/GraphUser.php for method getBirthday()
Current : @return \DateTime|null
Should be : @return Facebook\GraphNodes\Birthday|null

**Comment by yguedidi** [comment]
@julienbornstein Thanks for the notice! Can you send a PR that fix it? :)

**Comment by yguedidi** [comment]
Closed by #885
