### ISSUE TITLE
Failing to get an Facebook App to post to a Page's Wall, as that Page.

### ISSUE THREAD

**Issue by tinonetic** [facebook/php-graph-sdk#858]
Hi,

I am struggling going round in circles getting an Facebook App to post to a Page's Wall, as that Page.

In brief:

1. I have the App Secret and ID
2. I have  Page ID
3. I am relying on an in-code approach to generating the token I need.
4. It is based on one of the answers I saw here but does not work : #521 
5. I am using API v 2.9
6. I am using the latest PHP SDK

It's just been hard.

The solution I used is purely based on the one below:

```
<?php
define('FACEBOOK_SDK_V4_SRC_DIR', __DIR__ . '/Facebook');
require_once __DIR__ . '/Facebook/autoload.php';

use Facebook\FacebookRequest;

$app_id = {{your app-id}};
$app_secret = {{your app-secret}};

$fb = new Facebook\Facebook([
  'app_id' => $app_id,
  'app_secret' => $app_secret,
  'default_graph_version' => '{{your app-version}}', 
  ]);

$token = $fb->get(
    '/oauth/access_token?client_id=' . $app_id . '&'.
    'client_secret=' . $app_secret . '&'.
    'grant_type=client_credentials');

$get_token = $token -> getdecodedBody();
$access_token = $get_token['access_token'];

try {
  // Returns a `Facebook\FacebookResponse` object
  $response = $fb->get('/{{your facebook name}}', $access_token);
} catch(Facebook\Exceptions\FacebookResponseException $e) {
  echo 'Graph returned an error: ' . $e->getMessage();
  exit;
} catch(Facebook\Exceptions\FacebookSDKException $e) {
  echo 'Facebook SDK returned an error: ' . $e->getMessage();
  exit;
}

$body = $response->getBody();

print_r($body);
?>
```

I am certainly not lazy. I have been stuck on this issue for weeks.

I have tried the following different solutions and have gotten stuck in either a permissions related issue that was also related to depracated functionality and API calls. 

1. https://stackoverflow.com/questions/38871639/posting-to-a-facebook-page-from-a-website-using-curl (using a pure CURL approach - "The user hasn't authorized the application to perform this action")
2. https://stackoverflow.com/questions/45862794/facebook-sdk-returned-an-error-you-must-provide-an-access-token-php-facebook-a (suggests that I support login and redirection callback - yet I do not want any user intervention everytime when posting onto the page)
3. https://stackoverflow.com/a/14212125/919426 - Best explained step by step process for permissions and tokens, but still failed.
4. https://stackoverflow.com/questions/35171508/graph-returned-an-error-invalid-appsecret-proof-provided-in-the-api-argument - Previous attempt was based on this example but the appsecret-proof issue is the one that led me to #521 
5. https://stackoverflow.com/questions/7818667/simple-example-to-post-to-a-facebook-fan-page-via-php/7833145#7833145 - Another CURL-based approach that failed me

There are countless more that I have tried and failed.

**Comment by yguedidi** [comment]
@tinonetic looks like there is no bug with the SDK, so please use StackOverflow to ask for help, thank you. Closing
