### ISSUE TITLE
Facebook Block my account although i give manage_pages permission with correct app id & App Secret

### ISSUE THREAD

**Issue by prafullwizorbit** [facebook/php-graph-sdk#860]
![screenshot from 2017-10-11 20_03_11](https://user-images.githubusercontent.com/16131039/31448239-9633dcf0-aec1-11e7-87b8-974276a2f904.png)
![screenshot from 2017-10-11 20_02_46](https://user-images.githubusercontent.com/16131039/31448241-98842762-aec1-11e7-85f6-6227ecc3ca27.png)

**Comment by yguedidi** [comment]
Thank you for using the Facebook PHP SDK!

It looks like this is not an SDK issue, please post your question on StackOverflow.
