### ISSUE TITLE
What is the appropriate rule to use so Facebook transformer doesn't remove &nbsp; 

### ISSUE THREAD

**Issue by sephirith** [facebook/php-graph-sdk#861]
What is the appropriate rule to use so Facebook transformer doesn't remove  

> &nbsp

 from my code? I've tried using:

array(
'class' => 'PassThroughRule',
'selector' => '//p[.=codepoints-to-string((160))]',
//'selector' => '//p[.="\u0160"]',
),

**Comment by yguedidi** [comment]
Thank you for using the Facebook PHP SDK!

It looks like this is not an SDK issue, please post your question on StackOverflow.
