### ISSUE TITLE
Graph returned an error: (#200) Requires publish_stream permission

### ISSUE THREAD

**Issue by said-java** [facebook/php-graph-sdk#868]
$permissions = ['email','publish_actions']; // Optional permissions
try {
  // Returns a `Facebook\FacebookResponse` object
  $response = $fb->post('/iduserxxx/feed', $linkData, $accessToken);
} catch(Facebook\Exceptions\FacebookResponseException $e) {
  echo 'Graph returned an error: ' . $e->getMessage();
  exit;
} catch(Facebook\Exceptions\FacebookSDKException $e) {
  echo 'Facebook SDK returned an error: ' . $e->getMessage();
  exit;
}

$graphNode = $response->getGraphNode();

echo 'Posted with id: ' . $graphNode['id'];

}

Graph returned an error: (#200) Requires publish_stream permission

**Comment by vaggelis2018** [comment]
Same here. The problem is that this permission is deprecated.

**Comment by yguedidi** [comment]
Requesting a permission doesn't mean the user will grant it. So there, looks like the logged in user didn't grant the publish permission.

**Comment by vaggelis2018** [comment]
@yguedidi I found the solution to this. The problem was i had to explicit ask for pusblish asctions even if the app has already granted from facebook.

**Comment by jakelinemartins** [comment]
@vaggelis2018 Can you tell me how you did it? HELP

**Comment by vaggelis2018** [comment]
@jakelinemartins Hello and sorry for the late response. I was using laravel socialite.
