### ISSUE TITLE
How to add thumb field to Facebook video

### ISSUE THREAD

**Issue by HanaaGhasoub** [facebook/php-graph-sdk#871]
>  I created desktop application that upload videos to Facebook using graph.facebook and it works ok, but when i try to add "thumb" field to upload request it return error "(OAuthException - #100) (#100) Invalid image format. It should be an image file data." . 
here my code used :note coverpath is full image path and i try to path image as bytes but the same error return.
`dynamic parameters = new ExpandoObject();
        parameters.source = new FacebookMediaObject
                            {
                                ContentType = string.Format("video/{0}", VideoExtension.Split('.')[1]),
                                FileName = VideoName
                            }
                            .SetValue(File.ReadAllBytes(filePath));
        parameters.title = VideoTitle;
        parameters.description = VideoTitle;           
        parameters.universal_video_id = new Guid();
        parameters.thumb = coverPath;
        parameters.published = false;
        parameters.unpublished_content_type = "DRAFT";
        dynamic uploadresult = fb.Post("/367728493684998/videos", parameters);`

**Comment by yguedidi** [comment]
Thank you for using the Facebook PHP SDK!

It looks like this is not an SDK issue, please post your question on StackOverflow.

**Comment by HanaaGhasoub** [comment]
who said i used php sdk ? and i posted my question at all programming sites , thanks for your support

**Comment by yguedidi** [comment]
@HanaaGhasoub this is the Facebook PHP SDK repository, so it's natural to suppose that you use it. Hope you found a solution.
