### ISSUE TITLE
isLongLived()

### ISSUE THREAD

**Issue by kanneg881** [facebook/php-graph-sdk#872]
Hello I am come from Taiwan so may be would write down the wrong English grammar.
Please forgive for any inconveniences caused.

I found an issue about access token function isLongLived()
When I login on web with dialog to get short-lived access token
I saw my access object -> expiresIn: 87662
I don't know why I got it more than 2 hours.
But I think it still is a short-lived token.
So when I call isLongLived() it would return true

```
public function isLongLived()
{
if ($this->expiresAt) {
return $this->expiresAt->getTimestamp() > time() + (60 * 60 * 2);
}

    if ($this->isAppAccessToken()) {
        return true;
    }

    return false;
}
```
I think it have to write other conditions to check it is long-lived access token or not.

**Comment by sairochoa** [comment]
charge value 
(60 * 60 * 2) 
for (2)

**Comment by yguedidi** [comment]
There is no `expiresIn` field...

**Comment by kanneg881** [comment]
@yguedidi 

Refer to the URL below
https://developers.facebook.com/docs/reference/javascript/FB.getLoginStatus

**Comment by yguedidi** [comment]
@kanneg881 Your link points to the Javascript SDK

**Comment by yguedidi** [comment]
@kanneg881 any news on this?

**Comment by kanneg881** [comment]
@yguedidi 
My target is always get the unexpired access token,
I didn't use isLongLived() to check should I get the new long-lived access token.
If access token expire time is close maybe a week.
I will get the new long-lived access token

Refer to the URL below
https://developers.facebook.com/docs/facebook-login/access-tokens/expiration-and-extension

**Comment by yguedidi** [comment]
@kanneg881 I still don't understand what is the issue... In your example, you get an access token that expires in 87662 seconds, which represent one day.
According the doc, a long-lived access token is one that expires in about 60 days, so yours is not a long-lived one, `isLongLived()` will return false.

**Comment by kanneg881** [comment]
@yguedidi 
In the right condition isLongLived() will return false.
But why the code check time is -> time() + (60 * 60 * 2);
It means bigger than 2 hours will return true and isLongLived() will return true
That is not right return when use short-lived access token to check isLongLived()

**Comment by kanneg881** [comment]
The issue existed in my project fews month ago.
Finally I was stopped to continue developing this project.
I have been assigned developing other projects.
I didn't fix this issue at that time.
I wanted to auto update access token if it is soon to expire.
So I write a if statement to check whether need to update access token

define("second", 1);
define("minute", second * 60);
define("hour", minute * 60);
define("day", hour * 24);
define("week", day * 7);

if ($accessToken->getExpiresAt()->getTimestamp() < time() + week) {
    // get a new long-live access token
}

Maybe customers three days browser the website once.
So I set week.

The ideal scenario is customers always don't need to login again.

I think you have to get key vaule more clearly to check access token is LongLived or not.

e.x.
$email1 = abcdefg@gamil.com
$email2 = abcdefg@icloud.com

function isGmail($mail) {
    // easy check, regular expression is better
    if (strpos($mail, "gmail") === false) {
        return false;
    }

    return true;
}

Obviously, isGmail() key value must exist gmail.

**Comment by yguedidi** [comment]
Thanks @kanneg881 for info, closing as no more valid.
