### ISSUE TITLE
Graph returned an error: Can't Load URL

### ISSUE THREAD

**Issue by dungvaph03374** [facebook/php-graph-sdk#873]
Here my settings
App domain: mysite.com
Site URL: https://mysite.com/
Facebook Login product added, Valid OAuth redirect URIs: https://mysite.com/auth/fb-callback.php
App ID, App Secret, App Version configured, all other default
`$loginUrl = $helper->getLoginUrl('https://mysite.com/auth/fb-callback.php', $permissions);`

`https://www.facebook.com/v2.10/dialog/oauth?client_id=333686717095090&state=dd1a2e638977118aad2627f42d4c3171&response_type=code&sdk=php-sdk-5.6.1&redirect_uri=https://mysite.com/auth/fb-callback.php&scope=email`

> Graph returned an error: Can't Load URL: The domain of this URL isn't included in the app's domains. To be able to load this URL, add all domains and subdomains of your app to the App Domains field in your app settings.

**Comment by yguedidi** [comment]
Thank you for using the Facebook PHP SDK!

It looks like this is not an SDK issue, please post your question on StackOverflow.
BTW, check your app settings, there is a field named App Domains where you must enter your domain to allow it
