### ISSUE TITLE
Cross-site request forgery validation failed. Required param "state" missing from persistent data

### ISSUE THREAD

**Issue by ladhani** [facebook/php-graph-sdk#874]
Server: CentOS Linux 7.4.1708 with VirtualMin
PHP: 7.0.10

I have a perfectly working Facebook LOGIN solution with SDK 4.
And pretty good experience with SDK 4.

When I install the SDK 5 with the example code for Facebook LOGIN, I am getting the following error from the callback:

=====================================
Facebook SDK returned an error: Cross-site request forgery validation failed. Required param "state" missing from persistent data.
=====================================

I have double checked all the setting in Facebook Development and as I have a working solution with SDK 4, this should be OK. Of course I also added the callback URL in Valid OAuth redirect URIs.

I have a feeling that something goes wrong with sessions in PHP. 
If I explicitly turn on the sessions in the example code, instead of the cross-site error above, I am getting this very weird error in GERMAN (I am not German, nor in Germany, nor is my FB account in German..):

========================================
Facebook Graph returned an error: URL kann nicht geladen werden: Die Domain dieser URL ist nicht in den Domains der App vorhanden. Um diese URL laden zu können, füge alle Domains und Subdomains deiner App im Appdomain-Feld in deinen App-Einstellungen hinzu.
=========================================

This is strange as this error is shown in the call back function.

I have installed SDK 5 with composer (with correct php version settings).

So weird this????

May be specific for Centos 7 with VirtualMin as Admin panel as for else I have a pretty standard installation.

Any suggestions or other people with same problems with SDK 5?

I now at least two: https://stackoverflow.com/questions/46670802/strange-error-in-facebook-sdk-login/46996087

**Comment by yguedidi** [comment]
Looks like you solved the session issue by starting the session. Because yes, the SDK needs the session to work properly and session need to be started to be used! ;)
Regarding the other one, by translating it, it looks like you didn't allow your app domain in you apps settings.

**Comment by ladhani** [comment]
Hi Yassine,


Thanks for your reaction.


About the other one, I am very very very sure that I did allow the App 
domain in my app setting.

Just to be completely sure, I did replace on exactly the same URL, the 
code that uses SDK V4 and this one works perfectly.

Next, I replaces back the SDK V5 code (of course double checking that 
the call-back URL is exactly the same in both cases) and I got back the 
issue.


Also, the other one is in GERMAN language and if I have a wrong app 
domain, I get the same error message in English with sessions turned OFF.

I have nothing set in or using German.


That's why I find this so weird...


Can you please re-open this issue?


Thank,


Al-Noor Ladhani

**Comment by yguedidi** [comment]
@ladhani so you still encounter this issue?
