### ISSUE TITLE
Facebook SDK not working for me (solved) (bug)

### ISSUE THREAD

**Issue by Miles8of9** [facebook/php-graph-sdk#877]
Just a quick note to explain the problem and its solution: copying and pasting example code returns an error 191 telling that the callback url isn't allowed and pointing you to app settings inside facebook.
What? It's impossible! Check multiple times.. No.. the url is right! So, why?

Solution 1 add callback url to getAccessToken in your code:
$accessToken = $helper->getAccessToken("http://www.yoursite.com/fb-callback.php");

Solution 2 edit facebook sdk code:
https://github.com/facebook/php-graph-sdk/blob/2f9639c15ae043911f40ffe44080b32bac2c5280/src/Facebook/Helpers/FacebookRedirectLoginHelper.php#L226
Edit this line, find ['state'] and add code ['state','code']
Code param isn't stripped from callback url by the helper so it's sent to fb and you get the error.

**Comment by yguedidi** [comment]
@Miles8of9 thanks a lot! Can you send a PR for the solution 2 targeting the 5.x branch as it's a bugfix? :)

**Comment by timwhitlock** [comment]
Thank you @Miles8of9. I spent several hours checking and re-checking my settings. Even going as far as setting up real domains for my local hosts.

With strict URI checking becoming compulsory in March, I imagine lots more people will fall foul of this.

**Comment by shoguniphicus** [comment]
This needs to be put into production code, otherwise by March 2018, lots of production site will not be able to login since this is a forced implementation by Facebook

**Comment by yguedidi** [comment]
SDK 5.6.2 is now on Packagist :)
