### ISSUE TITLE
the Process flow for calls are to big to be any help debugging

### ISSUE THREAD

**Issue by barkermn01** [facebook/php-graph-sdk#884]
This API is great and all until you have a problem then it becomes as useful as a chocolate fireguard when a developer is trying to debug a problem, I mean you have that many methods calls it becomes impossible to debug reasonably in an application using it.

`Fatal error: Uncaught Facebook\Exceptions\FacebookAuthenticationException: Error validating access token: The session has been invalidated because the user changed their password or Facebook has changed the session for security reasons. in /var/dev/martin/frontend/ext/vendor/facebook/graph-sdk/src/Facebook/Exceptions/FacebookResponseException.php:89 Stack trace: #0 /var/dev/martin/frontend/ext/vendor/facebook/graph-sdk/src/Facebook/FacebookResponse.php(210): Facebook\Exceptions\FacebookResponseException::create(Object(Facebook\FacebookResponse)) #1 /var/dev/martin/frontend/ext/vendor/facebook/graph-sdk/src/Facebook/FacebookResponse.php(255): Facebook\FacebookResponse->makeException() #2 /var/dev/martin/frontend/ext/vendor/facebook/graph-sdk/src/Facebook/FacebookResponse.php(82): Facebook\FacebookResponse->decodeBody() #3 /var/dev/martin/frontend/ext/vendor/facebook/graph-sdk/src/Facebook/FacebookClient.php(224): Facebook\FacebookResponse->__construct(Object(Facebook\FacebookRequest), '{"error":{"mess...', 400, Array) #4 / in /var/dev/martin/frontend/ext/vendor/facebook/graph-sdk/src/Facebook/Exceptions/FacebookResponseException.php on line 89`

I mean the trace reported does not even leave the Facebook SDK to report what cause the error as a Web Application developer it would be nice where in my code caused the error not how your system handled the error. 

Could you please put some system into your Exception handler class that goes through the trace and find the first call that is not inside your vendor folder and reports that file/line so developer can debug without having to `die(1)` thought their code to find what call to the API causes the error?

**Comment by yguedidi** [comment]
Thank you for using the Facebook PHP SDK!

The SDK doesn't provide an error handler, so you have to change the PHP one yourself.

So I'm closing this, but if you found a bug in the SDK or think about a feature, feel free to open a new GitHub issues.
