### ISSUE TITLE
not following 30X redirects

### ISSUE THREAD

**Issue by poolerMF** [facebook/php-graph-sdk#886]
https://github.com/facebook/php-graph-sdk/blob/2f9639c15ae043911f40ffe44080b32bac2c5280/src/Facebook/HttpClients/FacebookCurlHttpClient.php#L101

curl option **CURLOPT_RETURNTRANSFER** is not about redirects
there should be new default option **CURLOPT_FOLLOWLOCATION** with value **true**

**Comment by yguedidi** [comment]
@poolerMF Thanks for the report! Do you have a case where you need to follow the redirect?
I'm not sure Graph API uses Location header..
