### ISSUE TITLE
Can't use version parameter

### ISSUE THREAD

**Issue by mateocam** [facebook/php-graph-sdk#902]
I am trying to use the version parameter to specify the version of the graph api I want to use, but it doesn't work.

This is my code:
fb_graph_version = "2.10"
graph = facebook.GraphAPI(access_token=api_key,version=fb_graph_version)
res = graph.get_object(object_endpoint)

And this is the error I get:
Version number should be in the following format: #.# (e.g. 2.0).

I also tried changing fb_graph_version to this value = 2.10 (a float instead of string) but it still doesn't work.

Help please!!

**Comment by yguedidi** [comment]
@mateocam looks like your code is not PHP, while this is the Graph PHP SDK... So I'm closing this. Please use StackOverflow for help.
