### ISSUE TITLE
Can't fetch users data.

### ISSUE THREAD

**Issue by Himanshu77** [facebook/php-graph-sdk#904]
Hello,

1.) I am using below graph API to search users 
https://graph.facebook.com/v2.10/search?q=TEXT_HERE
Using graph API i am fetching only id, name and cover photo only for users, Can you please tell me to get other info for users.
Is there any way to get other fields? Please share every possible way to find it.

2.) How can i filter with the #hashtag using PHP sdk ? Filter is only working with PAGE-ID ? or is this filter with all data.

Can you please help me more to resolve it?

Version: 2.10

Thank you.

**Comment by yguedidi** [comment]
Thank you for using the Facebook PHP SDK!

If you need help about using it, you should ask your questions on [StackOverflow](https://stackoverflow.com/) and tag them with the `facebook-php-sdk` tag.

So I'm closing this, but if you found a bug in the SDK or think about a feature, feel free to open a new GitHub issues.
