### ISSUE TITLE
Fixed Comment

### ISSUE THREAD

**Issue by JeanSauzem** [facebook/php-graph-sdk#908]
in sdk you have the option to fix comment ?

**Comment by yguedidi** [comment]
Thank you for using the Facebook PHP SDK!

If you need help about using it, you should ask your questions on [StackOverflow](https://stackoverflow.com/) and tag them with the `facebook-php-sdk` tag.

So I'm closing this, but if you found a bug in the SDK or think about a feature, feel free to open a new GitHub issues.
