### ISSUE TITLE
Issue with facebook object

### ISSUE THREAD

**Issue by jdanarola** [facebook/php-graph-sdk#909]
I've installed the PHP SDK and trying to run it using example from the top README.

$fb = new \Facebook\Facebook([
    'app_id' => '<id>',
    'app_secret' => '<secret>',
    'default_graph_version' => 'v2.11'
]);
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Facebook\FacebookClient::__construct() must be an instance of Facebook\HttpClients\FacebookHttpClientInterface, instance of Facebook\HttpClients\FacebookCurlHttpClient given, called in /data/event/vendor/facebook/graph-sdk/src/Facebook/Facebook.php on line 148 and defined in /data/event/vendor/facebook/graph-sdk/src/Facebook/FacebookClient.php:94

**Comment by jdanarola** [comment]
I have tried with various ways but still it  gives issue. could you please guide me how to resolve it ?
Thanks

**Comment by yguedidi** [comment]
Thank you for using the Facebook PHP SDK!

If you need help about using it, you should ask your questions on [StackOverflow](https://stackoverflow.com/) and tag them with the `facebook-php-sdk` tag.

So I'm closing this, but if you found a bug in the SDK or think about a feature, feel free to open a new GitHub issues.
