### ISSUE TITLE
Always meet the error that "Sorry, the report cannot be loaded successfully. Please check if your job status is completed..." when I calling AdAccount::getInsightsAsync

### ISSUE THREAD

**Issue by howlittlegrass** [facebook/php-graph-sdk#915]
Hi, php-graph-sdk team,

My code like:

    `$async_job = (new AdAccount($account_id))->getInsightsAsync($fields, $this->params);
     while (!$async_job->read()->isComplete()) {
            sleep(1);
     }`

I always met the error: "Sorry, the report cannot be loaded successfully. Please check if your job status is completed instead of failed or running before fetching the data."

But I have checked the status of job already, before reading the data. Why still got the error.

Sometimes, it was ok, there is no error; 
But sometimes, I got the error, in this case, if I retried it again and again for many times, I can get the data finally.

So, what is the problem? Expecting your feedback.
Thanks!

**Comment by yguedidi** [comment]
Closing because it's the wrong repository, you should post in https://github.com/facebook/facebook-php-ads-sdk

**Comment by JenyaInfiapps** [comment]
Hi yguedidi,

You sent him to the repository where impossible to open issue, how to ask there the same question?

Thanks!

**Comment by JenyaInfiapps** [comment]
> Closing because it's the wrong repository, you should post in https://github.com/facebook/facebook-php-ads-sdk

Hi yguedidi,

You sent him to the repository where impossible to open issue, how to ask there the same question?

Thanks!
