### ISSUE TITLE
 implement strict mode compatible authorization

### ISSUE THREAD

**Issue by kacurez** [facebook/php-graph-sdk#916]
**`UPDATE`** : if I generate the state parameter on my own then `response_type=code` auth is working with strict mode turned on. So implementing oauth via `response_type=token` is not necessary, moreover `response_type=token` is for client-side authorization as it generates callback url with url params separated by hash(`#`) and not question mark(`?`).  However I don't know why state value generated by this sdk causes the problem described below.

probably related to #873 
Facebook is enforcing strict mode to be used in the authorization process.
https://developers.facebook.com/docs/facebook-login/security/#strict_mode

![image](https://user-images.githubusercontent.com/1412120/34882627-76b4b914-f7b7-11e7-95e0-15904810ce6e.png)

I use this sdk to authorize a fb account and retrieve access token. However when I turn on strict mode, then it will fail with error message:
`Can't Load URL: The domain of this URL isn't included in the app's domains.`

I contacted fb support and been told not to use response_type=code. The `response_type=code` is hardwired in the authorization module of this sdk, see:
https://github.com/facebook/php-graph-sdk/blob/5.x/src/Facebook/Authentication/OAuth2Client.php#L140

They recommended me to use `response_type=token`, so I tried it(manually updating source code) and it worked. 
Could you please update the authorization module to comply strict mode policy?

**Comment by sam4jips** [comment]
how did you set the state parameter manually? please teach me. I looked everywhere but couldn't find anywhere.

**Comment by kacurez** [comment]
The api of this library does not offer to put state parameter so I ended up implementing the oauth process on my own without any use of this library.

**Comment by sam4jips** [comment]
actually i found the solution. you can set state manually if you want.

$helper = $fb->getRedirectLoginHelper();
$helper->getPersistentDataHandler()->set('state', $state);
$helper->getPersistentDataHandler()->get('state');

**Comment by claudeschneider** [comment]
We're getting the same problem - oAuth it fails with the same error mentioned above (domain of URL isn't included in the app's domain)

Facebook also gave the same response, that the presence of ?code= in the redirect URL materially changes the redirect URL, and thus stops strict mode from working.

Even though the official docs still mention using "code" to get a response that can be exchanged for an access token
https://developers.facebook.com/docs/facebook-login/manually-build-a-login-flow

If the PHP SDK hard-codes the "response_type=code" into the loginHelper URL, and that no longer works, it needs to be changed in the PHP-SDK.

**Comment by cannond13** [comment]
@kacurez if you manually updated the source code of the SDK on your server -- you are not using Composer?  or you thought the change was a worthwhile deviation from your composer.lock settings?

@sam4jips  once you were able to manually retrieve / set the state parameter, how do you combine that with the other LoginURL parameters -- especially scope?

I'm new-ish to development but wanted to add support for this issue, as I've run into the same error messages as those on this thread.

**Comment by kacurez** [comment]
@cannond13 I manually updated code as an experiment just to prove that the problem is in `state`. I think the problem is in its length - 32 characters afaik. Finally I implemented oauth without this library generating `state` of 16 characters long and it is working.

**Comment by yguedidi** [comment]
Closing this as the SDK should now be compatible with strict mode, thanks to #913 released in 5.6.2!
Thank you all for your detailed feedback! Feel free to open a new issue if you still encounter issue with strict mode.
