### ISSUE TITLE
$account->getAdSets is an Unsupported get request

### ISSUE THREAD

**Issue by Project-FB** [facebook/php-graph-sdk#920]
This is the code I'm using

require __DIR__ . '/vendor/autoload.php';

use FacebookAds\Api;
use FacebookAds\Object\AdAccount;
use FacebookAds\Object\Fields\AdSetFields;

Api::init(
  '<APP ID>',
  '<APP SECRET>',
  '<ACCESS TOKEN>'
);

$account = new AdAccount('act_357674657998325');
$adsets = $account->getAdSets(array(
  AdSetFields::NAME,
  AdSetFields::CONFIGURED_STATUS,
  AdSetFields::EFFECTIVE_STATUS,
));

foreach ($adsets as $adset) {
  echo $adset->{AdSetFields::NAME}.PHP_EOL;
}
And the error i'm getting.

Fatal error: Uncaught FacebookAds\Http\Exception\AuthorizationException: Unsupported get request. in D:\src\FacebookAds\Http\Excepti on\RequestException.php:144

**Comment by yguedidi** [comment]
Closing because it the wrong repository, you should post in https://github.com/facebook/facebook-php-ads-sdk
