### ISSUE TITLE
Email has stopped returning to the request.

### ISSUE THREAD

**Issue by ilusha2012** [facebook/php-graph-sdk#922]
Hello!

A few days ago, the email stopped responding to the request. Only id and name.

`$fb->get('/me?fields=id,name,email', $token)`

**Comment by yguedidi** [comment]
Thanks for the report!

Here what the doc says:
![image](https://user-images.githubusercontent.com/1480128/36641585-21df15a4-1a32-11e8-83bc-e7a5862f8df9.png)

So I'm closing this as it looks like not and SDK issue, but a user who changes his/her email adress to an invalid one.
