### ISSUE TITLE
Guzzle Client

### ISSUE THREAD

**Issue by martinjankov** [facebook/php-graph-sdk#928]
How about you guys make it compatible with guzzlehttp/guzzle version 6.3, that is the latest version.

I am using the latest version and it started throwing errors like 3rd argument expected to be array but string send in client->request. I downgraded to 5.3 and it was working for facebook, but not for the other request I was making using Guzzle.

**Comment by Nyholm** [comment]
Hey. 
We just went with the HTTPlug abstraction. That will be compatible with the [PSR for HTTPClients](https://github.com/php-fig/fig-standards/blob/master/proposed/http-client/http-client.md). I can also promise you that the next version of Guzzle will support the same PSR.

**Comment by yguedidi** [comment]
@martinjankov good suggestion, but v5 of the SDK only supports Guzzle 5.
Moving to Guzzle 6 is a Backward Compatibility break, and AFAICR Guzzle 5 and Guzzle 6 can't live together.

Thats why the next major version of the SDK, v6, will uses HTTPlug thanks to @Nyholm contribution!
v6 is not released yet and still under development, but you can give it a try!
If we want Guzzle 6 under SDK v5, [here](https://www.sammyk.me/how-to-inject-your-own-http-client-in-the-facebook-php-sdk-v5#writing-a-guzzle-6-http-client-implementation-from-scratch) a doc from my co-maintainer @SammyK that will help you!
