### ISSUE TITLE
how to set and retrieve state param manually?

### ISSUE THREAD

**Issue by sam4jips** [facebook/php-graph-sdk#929]
Since strict mode is going to be compulsory in March, I need a way to get some data after user redirects back to my site after login flow?

i looked everywhere but still couldn't find how to use state param? is there even any way? can anyone explain?

**Comment by yguedidi** [comment]
@sam4jips what's your need exactly? Properly support strict mode is done in version 5.6.2. The state parameter is there only to prevent CSRF attacks, and it's handled automatically by the SDK, how you want to use it?

**Comment by psychowico** [comment]
https://developers.facebook.com/docs/facebook-login/security/#strict_mode

Before we was able to use dynamic redirect url to redirect user in any place in our website. In the strict mode we won't be able to use dynamic urls - just limited list of urls given by us in facebook panel.
Often you can't set up all urls in panel, as the urls number is huge and dynamic.

Now we should use state parameter for things like that. e.g. we always redirect user to same website, but we store real redirect url in state params and we use it on given site to redirect user to real goal page.

**Comment by yguedidi** [comment]
Frankly, this looks like a hack to me.. `state` param resposability is to prevent CSRF attack, and this responsability will be the only supported one in the SDK.

Anyway, the SDK can already answer your use case! :)
You just need to use your own `PersistentDataHandler`, pass it as the `persistent_data_handler` config key to `Facebook` class, and call `$myPersistentDataHandler->set('state', 'my-state-value);` before calling `getLoginUrl()`.

Do this solves your issue?

**Comment by fabi0w** [comment]
@yguedidi Everything worked fine. But I activated the strict mode and my oauth login not works! I've already added the primary url to valid OAuth redirect URIs. and the error persists. in PHP log I find the following.`PHP Fatal error: Uncaught Facebook \\ Exceptions \\ FacebookSDKException: You must provide an access token. `. My SDK is 5.6.2. Any solution? Thank you!

**Comment by yguedidi** [comment]
Hello @fabi0w, the error message makes me think it is not an SDK issue.. You should try asking on StackOverflow, or open a new issue with more detail so we can debug it.
I'm closing this one as the original issue about manually setting the state param will not be supported by the SDK.
