### ISSUE TITLE
Error whilie installing through composer

### ISSUE THREAD

**Issue by karansiso** [facebook/php-graph-sdk#930]
Problem 1
    - The requested package facebook/graph-sdk No version set (parsed as 1.0.0) is satisfiable by facebook/graph-sdk[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.

**Comment by Nyholm** [comment]
It looks like you have a syntax error in your composer.json. 
Try running

```cli
composer req facebook/graph-sdk  --no-update
composer update
```

**Comment by yguedidi** [comment]
Closing as there is no feedback on the suggested solution. Thanks a lot @Nyholm!
