### ISSUE TITLE
Strict Mode for Redirect URIs = not working with PHP Sdk

### ISSUE THREAD

**Issue by sollemar** [facebook/php-graph-sdk#934]
If I enable "Use Strict Mode for Redirect URIs", I get the following error from the PHP SDK, but the App Domains are set correctly.

Facebook Graph returned an error: URL kann nicht geladen werden: Die Domain dieser URL ist nicht in den Domains der App vorhanden. Um diese URL laden zu können, füge alle Domains und Subdomains deiner App im Appdomain-Feld in deinen App-Einstellungen hinzu.

I can fix this error with the following modification:

src/Facebook/Helpers/FacebookRedirectLoginHelper.php, Line 226

OLD: $redirectUrl = FacebookUrlManipulator::removeParamsFromUrl($redirectUrl, ['state']);

NEW: $redirectUrl = FacebookUrlManipulator::removeParamsFromUrl($redirectUrl, ['state', 'code']);

Bug?

**Comment by jsleetw** [comment]
Try 
$accessToken = $helper->getAccessToken();
to
$accessToken = $helper->getAccessToken($this->get_fb_callback_uri());

see:
https://stackoverflow.com/questions/47898499/error-on-login-using-facebook-php-sdk-with-strict-mode-enabled

**Comment by sollemar** [comment]
OK, that works, thanks.

**Comment by yguedidi** [comment]
@sollemar just released the 5.6.2 version that fixes this issue! see #913

**Comment by hao214** [comment]
here is my code , it works fine without strict mode.
Please help


<?php
if ( !session_id() ){ 
	session_start(); 
}
// added in v4.0.0
require_once ('autoload.php'); 
require ("../inc/config.php");
require ("../inc/class_mysql.php"); 
require ("functions.php");
// login helper with redirect_uri 
$id = trim($_GET['id']); 
$url = 'https://'. $domain; 

$fb = new Facebook\Facebook([ 'app_id' => $appid, 'app_secret' => $secret, 'default_graph_version' => 'v2.2', ]); 

$helper = $fb->getRedirectLoginHelper(); 
$_SESSION['FBRLH_state'] = $_GET['state']; 
try {
  $accessToken = $helper->getAccessToken(); 
} catch(Facebook\Exceptions\FacebookResponseException $e) {
  // When Graph returns an error
  echo 'Graph returned an error: ' . $e->getMessage();
  exit;
} catch(Facebook\Exceptions\FacebookSDKException $e) {
  // When validation fails or other local issues
  echo 'Facebook SDK returned an error: ' . $e->getMessage();
  exit;
}

if ( !isset($accessToken) ){ 
	if ( $helper->getError() ){ 
		header('HTTP/1.0 401 Unauthorized');
		echo "Error: " . $helper->getError() . "\n";
		echo "Error Code: " . $helper->getErrorCode() . "\n";
		echo "Error Reason: " . $helper->getErrorReason() . "\n";
		echo "Error Description: " . $helper->getErrorDescription() . "\n";
	} else {
		header('HTTP/1.0 400 Bad Request');
		echo 'Bad request';
	}
	exit; 
}
/*
// Logged in
echo '<h3>Access Token</h3>'; 
var_dump($accessToken->getValue()); 

// The OAuth 2.0 client handler helps us manage access tokens
$oAuth2Client = $fb->getOAuth2Client();

// Get the access token metadata from /debug_token
$tokenMetadata = $oAuth2Client->debugToken($accessToken);
echo '<h3>Metadata</h3>';
var_dump($tokenMetadata); 
// Validation (these will throw FacebookSDKException's when they fail)
$tokenMetadata->validateAppId($appid); // Replace {app-id} with your app id
// If you know the user ID this access token belongs to, you can validate it here
//$tokenMetadata->validateUserId('123');
$tokenMetadata->validateExpiration(); 

if ( !$accessToken->isLongLived() ){ 
  // Exchanges a short-lived access token for a long-lived one
  try {
    $accessToken = $oAuth2Client->getLongLivedAccessToken($accessToken);
  } catch (Facebook\Exceptions\FacebookSDKException $e) {
    echo "<p>Error getting long-lived access token: " . $helper->getMessage() . "</p>\n\n";
    exit;
  }
  //echo '<h3>Long-lived</h3>';
  //var_dump($accessToken->getValue()); 
}
*/

$_SESSION['fb_access_token'] = (string) $accessToken; 

// User is logged in with a long-lived access token 
//$fbid = $tokenMetadata->getField('user_id');  // To Get Facebook ID 
try {
  // If you provided a 'default_access_token', the '{access-token}' is optional first_name,last_name 
  $response = $fb->get('/me?fields=id,name,email', $accessToken->getValue()); 
  // print_r($response);
} catch(Facebook\Exceptions\FacebookResponseException $e) { 
  // When Graph returns an error
  echo 'ERROR: Graph ' . $e->getMessage();
  exit;
} catch(Facebook\Exceptions\FacebookSDKException $e) {
  // When validation fails or other local issues
  echo 'ERROR: validation fails ' . $e->getMessage();
  exit; 
}

$user = $response->getGraphUser(); 
$fbid = $user['id']; 
$ffname = $user['name']; 
$femail = $user['email']; 
//Session Variables 
$_SESSION['FBID'] = $fbid; 
$_SESSION['FULLNAME'] = $ffname; 
$_SESSION['EMAIL'] = $femail; 

$db = new mysql($mysql_server_name, $mysql_username, $mysql_password, $mysql_database, 'utf8'); 

checkuser($fbid,$ffname,$femail); 

/* ---- header location after session ----*/
$sql = "select uid,password,usergid from na_users where fbid='". $fbid ."' "; 
$result = $db -> query($sql); 
if( mysql_num_rows($result) ){ 
	$row = $db -> fetch_array($result); 
	setcookie("uid", $row['uid'], time()+3600*24*15, '/'); 
	setcookie("password", $row['password'], time()+3600*24*15, '/'); 
	setcookie("username", str_replace("+"," ",$ffname), time()+3600*24*15, '/'); 
	setcookie("firstname", str_replace("+"," ",$ffname), time()+3600*24*15, '/'); 
	setcookie("usergid", $row['usergid'], time()+3600*24*15, '/'); 
}

if( is_numeric($id) && $id!="" ){ 
	$sql = "SELECT valcode,orderno FROM na_orderform WHERE st=0 and id=". sqlreF($id) ." ORDER BY id DESC LIMIT 1"; 
	$result = $db -> query($sql); 
	if( mysql_num_rows($result) ){ 
		$row = $db -> fetch_array($result); 
		setcookie("valcode", $row[0], time()+3600*24*15, '/'); 
		setcookie("orderno", $row[1], time()+3600*24*15, '/'); 
	}
}

header("HTTP/1.1 303 See Other"); 
header("Location: ". $url ."/shoppingcart.php?act=nextinf&"); 
exit; 
?>
