### ISSUE TITLE
Can't Understand Why Facebook Block App

### ISSUE THREAD

**Issue by deepeshdkpathak** [facebook/php-graph-sdk#940]
Hi 

I am developer and use Facebook php sdk more then 9 years in different project and I am writing this on behalf of developer. For each user action like Facebook login and Facebook login with share we ask permission from Facebook 'public_profile', 'user_photos' and 'publish_actions', 'public_profile', 'user_photos'. If user comes first time for our app then Facebook show popup for permission asked, after that user allow the permission and Facebook stored in user settings, from next time when we ask for same permission with same code Facebook return the response url, as it's an general process.

But today i.e. 14Feb2018 fb blocked our client app, that total bounce my mind. I can't understand why Facebook do that. Below are the message received from Facebook.

Facebook Message -

In working to create a great Platform experience for everyone, we ask developers to ensure the apps they build comply with our Platform Policies. Your app YYYYYY (AppId: xxxxxxxxx) doesn't comply with the following Platform Policies:

Platform Policy 2.1: Obtain consent from people before publishing content on their behalf.

This means that your app appears to be posting without user consent. If a person grants you a publishing permission, make sure you obtain their consent when posting to Facebook on their behalf. For example, provide clear publishing options, such as post, publish, or share.  After people grant your app a write permission, you must still obtain their permission each time your app allows them to share to Facebook. For more information on sharing, check out our Sharing documentation: ﻿https://developers.facebook.com/docs/sharing﻿

Platform Policy 7.3: Use a clearly branded "Login with Facebook" button and follow the Facebook Brand Guidelines: https://www.facebookbrand.com/.
Your Login button doesn't properly reference Facebook. To fix this issue, you should always use our official SDK for Login. For more information on Login best practices, check out the Login section of our developer documents: https://developers.facebook.com/docs/facebook-login/best-practices#buttondesign.

#End Facebook Message

I really don't know why Facebook do that. If i get understand these blocking reason that I note that and do for all apps that i have worked on. 

But as i believe i do not make any mistake if so then please Facebook team clarify to me. Otherwise i believe some Strong entity will make force Facebook to do that. Facebook are platform where people can grow connect share and many more. So please help me to clarify the same, I hope this might be bug and fix asap by Facebook team.

Thanks for you in anticipation.

**Comment by yguedidi** [comment]
@deepeshdkpathak I'm sorry for the issue you encounter.. But maintainers of this SDK are not from Facebook, so we can't help.
I suggest you to ask the via the [Facebook issue tracker](https://developers.facebook.com/bugs/).
So I'm closing this as it's not SDK related. I hope you'll find the reasons why.
