### ISSUE TITLE
"The domain of this URL isn't included in the app's domain" only in WebView version of website.

### ISSUE THREAD

**Issue by tafelnl** [facebook/php-graph-sdk#946]
I have a fully working Web OAuth login flow. When I login via the web version of the site, it works. I also have an app for Android with a simple WebView which shows the site. If I try to login that way, I get the following error message: `The domain of this URL isn't included in the app's domain`.

This only happens when "Strict Mode" is turned on.

So to be clear: "Strict Mode" does actually work on the 'normal' version of the website, but not when using it in a webview although I checked "Embedded Browser OAuth Login".

**Comment by sandermuru** [comment]
See my comment here: https://github.com/facebook/php-graph-sdk/issues/947#issuecomment-367259245

**Comment by tafelnl** [comment]
Thanks. I don't know why the fix mentioned on Stackoverflow worked. But it did. Thank you very much!

**Comment by sandermuru** [comment]
Because 5.6.2 is now also available from Packagist, you should revert Stackoverflow changes and update SDK.

**Comment by yguedidi** [comment]
Thanks @sandermuru for your help!
