### ISSUE TITLE
Can't load URL: The domain of this URL isn't included in the app's domains. To be able to load this URL, add all domains and sub-domains of your app to the App Domains field in your app settings.

### ISSUE THREAD

**Issue by ahtishamashraf** [facebook/php-graph-sdk#951]
I have my app Live on Facebook and Using Facebook SDK for Login Now Due to the Change in Policy of Facebook , the Use of Strict Mode is Mandatory and The Valid OAuth URLs are to be listed in the Valid OAuth , I have Listed the URLs there and now When I try to Log in via Facebook it Returns an Error \
"**Can't load URL: The domain of this URL isn't included in the app's domains. To be able to load this URL, add all domains and sub-domains of your app to the App Domains field in your app settings.**"
I have my Domain Listed on App Domains , Everything Works fine if I turn off the Strict Mode for Redirect URI. Please Guide me if I am missing something or I need to Update anything.

**Comment by yguedidi** [comment]
Do you use the latest version of the SDK (5.6.2)? It contains a fix to support Strict Mode (#913)

**Comment by ahtishamashraf** [comment]
I have updated now and it is working now, Thanks.

**Comment by stoevno1** [comment]
I had the same issue. Now fixed with the SDK (5.6.2). Many thanks ;)

**Comment by satay** [comment]
Hi Team,
I am facing same issue..Please suggest changes..I have update to SDK 5.6.2, but still facing issue.
********************************************************************************************************
Can't load URL: The domain of this URL isn't included in the app's domains. To be able to load this URL, add all domains and sub-domains of your app to the App Domains field in your app settings.
***************************************************************************************

define('FACEBOOK_SDK_V4_SRC_DIR', __DIR__ . '/facebook-sdk-v5.6.2/');
require_once __DIR__ . '/facebook-sdk-v5.6.2/autoload.php';

$fb = new Facebook\Facebook([
  'app_id' => $app_id,
  'app_secret' => $app_secret,
  'default_graph_version' => 'v2.5',
  ]);

**Comment by satay** [comment]
Hi Team,

Any suggestion on it.

**Comment by satay** [comment]
Yes..I have included both urls.

**Comment by yguedidi** [comment]
@satay `http://myvoicepost.com/` is not a domain but an URL, `myvoicepost.com` is a domain ;)

**Comment by satay** [comment]
@yguedidi Yes I have included myvoicepost.com in domain list. But it was not working.

**Comment by yguedidi** [comment]
@satay on the facebook page that show you the error message "Can't load URL: The domain of this URL isn't included in the app's domains.", simply check the URL in your browser and check the `redirect_uri` value

**Comment by satay** [comment]
https://www.facebook.com/v2.6/dialog/oauth?client_id=461609294031645&state=1b26120ffc4426ae2ccb2d7a1e91e2c6&response_type=code&sdk=php-sdk-5.6.2&redirect_uri=http%3A%2F%2Fmyvoicepost.com%2Ffbxl%2Ffb-callback.php%3Fp%3D180426163032_87885850881%26msg%3Dhi&scope=email%2Cpublish_actions

This is complete url..so what need to pass in redirect_uri value now..

**Comment by yguedidi** [comment]
@satay looks like your redirect URL is not HTTPS

**Comment by yguedidi** [comment]
@satay here, your redirect URL is `http://myvoicepost.com/fbxl/fb-callback.php?p=180426163032_87885850881&msg=hi`, wich is not EXACTLY the one you configured.
If you need more help, please ask StackOverflow

**Comment by satay** [comment]
@yguedidi  actually it's callback url which we pass at the time of login auth-

$callback_url="http://myvoicepost.com/fbxl/fb-callback.php?p=".$p."&msg=".$msg;
$loginUrl = $helper->getLoginUrl($callback_url, $permissions);

**Comment by yguedidi** [comment]
@satay Facebook require that any redirect URL match exactly the one configured in the app

**Comment by satay** [comment]
@yguedidi  I set Share Redirect Whitelist url with "http://myvoicepost.com/fbxl/fb-callback.php" but still getting error.
https://www.facebook.com/v2.6/dialog/oauth?client_id=461609294031645&state=1b26120ffc4426ae2ccb2d7a1e91e2c6&response_type=code&sdk=php-sdk-5.6.2&redirect_uri=http%3A%2F%2Fmyvoicepost.com%2Ffbxl%2Ffb-callback.php&scope=email%2Cpublish_actions

**Comment by satay** [comment]
@yguedidi thank you very much ..it's working fine for me now..do we need to submit app again for review ?

**Comment by yguedidi** [comment]
@satay I don't know sorry, ask Facebook

**Comment by Madhushanudeshike** [comment]
**Graph returned an error: Can't load URL: The domain of this URL isn't included in the app's domains. To be able to load this URL, add all domains and sub-domains of your app to the App Domains field in your app settings.**

Please Help

**Comment by Madhushanudeshike** [comment]
[](http://www.coolfun.club/callback.php?code=AQCVruCrS1VDbEbPFSFqsTwx3OWFg4l2oe4DiF329TAG6Nkl4v0uQVS0SVMo2FEL6YIo4eQRwGXHxYpYKuSa1rvIvZNApX_sKRlCz2h5-1DfOD6MHzb2xd14tStUXalSL6WwQCuyywN9QAjqI7Zp6GFBEKY4Gu1IzxfZcTSSovmOXYC8QTndQtNrR1sSp2lNcS2L0D3cznKZN2aBRpQ_jkvQVp2nqkDlRiGRnhBasQBBC4EIRIjEZwQhaliTVBEt_AEAYcTEHm_TbEVdY5haWlqTTXAiB-eczlOt0zF15-NAOQwMljyFYe-PvQZQJfh-pk332nYDht-Q77pQfrsfuurE&state=d41a1f8c088ccf9da8e39ef7505592e9#_=_)

**Comment by Madhushanudeshike** [comment]
[http://www.coolfun.club/callback.php?code=AQCVruCrS1VDbEbPFSFqsTwx3OWFg4l2oe4DiF329TAG6Nkl4v0uQVS0SVMo2FEL6YIo4eQRwGXHxYpYKuSa1rvIvZNApX_sKRlCz2h5-1DfOD6MHzb2xd14tStUXalSL6WwQCuyywN9QAjqI7Zp6GFBEKY4Gu1IzxfZcTSSovmOXYC8QTndQtNrR1sSp2lNcS2L0D3cznKZN2aBRpQ_jkvQVp2nqkDlRiGRnhBasQBBC4EIRIjEZwQhaliTVBEt_AEAYcTEHm_TbEVdY5haWlqTTXAiB-eczlOt0zF15-NAOQwMljyFYe-PvQZQJfh-pk332nYDht-Q77pQfrsfuurE&state=d41a1f8c088ccf9da8e39ef7505592e9#_=_](http://www.coolfun.club/callback.php?code=AQCVruCrS1VDbEbPFSFqsTwx3OWFg4l2oe4DiF329TAG6Nkl4v0uQVS0SVMo2FEL6YIo4eQRwGXHxYpYKuSa1rvIvZNApX_sKRlCz2h5-1DfOD6MHzb2xd14tStUXalSL6WwQCuyywN9QAjqI7Zp6GFBEKY4Gu1IzxfZcTSSovmOXYC8QTndQtNrR1sSp2lNcS2L0D3cznKZN2aBRpQ_jkvQVp2nqkDlRiGRnhBasQBBC4EIRIjEZwQhaliTVBEt_AEAYcTEHm_TbEVdY5haWlqTTXAiB-eczlOt0zF15-NAOQwMljyFYe-PvQZQJfh-pk332nYDht-Q77pQfrsfuurE&state=d41a1f8c088ccf9da8e39ef7505592e9#_=_)

**Comment by gauravshimpi** [comment]
hello all,
i have the same issue
this is the fb link
https://www.facebook.com/v2.2/dialog/oauth?client_id=2077887022527500&state=f0dfeef85107cf350e82f1b713d2f110&response_type=code&sdk=php-sdk-5.5.0&redirect_uri=https%3A%2F%2Frtcampappbookproject.herokuapp.com%2Ffbcallback.php&scope=email%2Cuser_photos

my app is still in development mode...
it was working correctly in localhost
but now its not working on live https site

![demosend1](https://user-images.githubusercontent.com/39704891/45254163-5b686c00-b391-11e8-915c-2e1a22b24ede.png)

![demosend2](https://user-images.githubusercontent.com/39704891/45254171-894db080-b391-11e8-9b22-d011a254c1ad.png)


these are my app configurations
what should i do??

**Comment by alexwai** [comment]
Finally i manage to find the problem when using the  PHP SDK.

The message that always shows is "The domain of this URL isn't included in the app's domains."

On the callback page in the getAccessToken need to specify the call back url even thou it is optional

```
try 
{
	$accessToken = $helper->getAccessToken('https://place-your-callback-url-here');
} 
catch (\Facebook\Exceptions\FacebookResponseException $e) 
{
	echo $e->getMessage();
} 
catch (\Facebook\Exceptions\FacebookSDKException $e) 
{

	echo $e->getMessage();
}
if (!$accessToken) 
{
	echo 'FAIL';
}
```

Hope this helps......
