### ISSUE TITLE
Class 'FacebookSession' not found

### ISSUE THREAD

**Issue by afaridanquah** [facebook/php-graph-sdk#952]
Am trying to use the package in a Laravel app. 
After composer require facebook/graph-sdk
and doing use Facebook\FacebookSession; in my class 

i get -- Class 'FacebookSession' not found -- 
i understand in the previous versions you may need to require autoload. I tried it and bumped up.
Any help would be appreciated.

**Comment by yguedidi** [comment]
`FacebookSession` is from SDK v4.0... you should update to the latest 5.6.2! :)
