### ISSUE TITLE
Does Facebook Javascript SDK work after breaking change?

### ISSUE THREAD

**Issue by EGreg** [facebook/php-graph-sdk#954]
Hi there. According to this announcement about a "strict mode", we will have to change our apps to only have exact redirect URLs:

https://developers.facebook.com/docs/facebook-login/security#strict_mode

However, in there it says "For apps using only the Facebook SDK, redirect traffic is already protected. No further action is needed."

Can you clarify this? Does it refer to the Javascript SDK, and do we have to change anything on the client side if the authentication is on the client side?

Does it ALSO refer to the PHP SDK, and if so, do we have to download the latest one? Can you explain exactly how the PHP SDK was adjusted to deal with this change, and what we should do to be compatible with this required change?

**Comment by yguedidi** [comment]
Yes you must use the latest version, 5.6.2, to work with strict mode.

This repository is about the Graph API PHP SDK and reported issues must be related to it, like SDK code bugs, documentation mistakes or new feature suggestions.
For issues with Graph API itself, you can report a bug in the [Facebook issue tracker](https://developers.facebook.com/bugs/).
For help about how to use the SDK, [StackOverflow](https://stackoverflow.com) is a better place to get answers. Don't forget to tag your question with the [facebook-php-sdk](https://stackoverflow.com/questions/tagged/facebook-php-sdk) tag.
So I'm closing this, and hope to see you soon contributing to the SDK. :)
