### ISSUE TITLE
Problem getting friends list

### ISSUE THREAD

**Issue by orlandoabreu221** [facebook/php-graph-sdk#959]
Hi folks, I'm having a problem getting the user's friends list with Facebook PHP Graph SDK(this repository), I'm just getting the friends of the user that have accepted and used the app before, i mean, those who already granted permissions to the app, i have read that this is something new on the new version of facebook sdk, but the previous one [https://github.com/facebookarchive/facebook-php-sdk](https://github.com/facebookarchive/facebook-php-sdk) says is deprecated and i can't use it. Does anyone know a way to get all of the user's friends, even if they haven't use this app before, with this new SDK? If it is not possible with this new SDK, there is any way i can use the older one? And if it is not possible either, does anyone know if i can perform this action with Instagram SDK? thank you very much in advance
`try {
  // Returns a 'Facebook\FacebookResponse' object
  $response = $fb->get('/me?fields=id,name,friends', my_token']);
} catch(Facebook\Exceptions\FacebookResponseException $e) {
  echo 'Graph returned an error: ' . $e->getMessage();
  exit;
} catch(Facebook\Exceptions\FacebookSDKException $e) {
  echo 'Facebook SDK returned an error: ' . $e->getMessage();
  exit;
}

$user = $response->getGraphNode();

$all_friends = $user['friends']->all();
//just returning one friend who accepted and used the app before
var_dump($all_friends);`

**Comment by yguedidi** [comment]
@orlandoabreu221 it's not an SDK limitation, it's the Graph API that limit that access. Please read the Graph API documentation ;)
