### ISSUE TITLE
Error : Can't Load URL: The domain of this URL isn't included in the app

### ISSUE THREAD

**Issue by gurjanjua** [facebook/php-graph-sdk#963]
When i am trying to login with facebook on my site, after facebook login it throwing 

Graph returned an error : Can't Load URL: The domain of this URL isn't included in the app's domains. To be able to load this URL, add all domains and subdomains of your app to the App Domains field in your app settings.

It was working fine two days ago. Today one of my user told me regarding this and when i checked it is throwing error after facebook login.

What is the problem & how do I fix it? I've searched, and found many similar posts, but none of them have a solution that I can figure out how to apply. 

Thanx for help in advance

**Comment by bigktmbig** [comment]
Me too, who can help me?

**Comment by revPushker** [comment]
same issue , i have facing when i  am logging with facebook from my app, it throws Graph returned an error : Can't Load URL: The domain of this URL isn't included in the app's domains. To be able to load this URL, add all domains and subdomains of your app to the App Domains field in your app settings

**Comment by mirondi** [comment]
Same here, maybe the last update for strict urls break things ?

**Comment by peterlcf0403** [comment]
guys I also faced this problem just today. In my case it was the sdk version problem. I updated to the latest version and the problem is fixed. hope this help.

Wonder if this is related to recent data leak scandal and they may made some changes to the service.

**Comment by arvidbjorkstrom** [comment]
This is probably related to the [strict mode](https://developers.facebook.com/docs/facebook-login/security/#strict_mode) now being compulsory since a few weeks back.
Add your full callback url in the setting at https://developers.facebook.com/apps/XXXXXXXXXXX/fb-login/settings/ (replace XXX with your app id) and that will hopefully fix the problem. :)

**Comment by Ivan-ShRt** [comment]
Spent many hours fighting this... Simply updating to 5.6.2  solves the problem.

**Comment by Celsyum** [comment]
I had issues with this. Noticed that after moving to https:// it still redirects to http://
after long hours of looking into fb sdk found that they have issues detecting if your site is secure.
Developers should take a look.

So, on file 

facebookd-v5.*-sdk/Url/FacebookUrlDetectionHandler.php
update two functions. 
Updated versions:

    protected function protocolWithActiveSsl($protocol)
    {
        $protocol = strtolower((string)$protocol);

        return in_array($protocol, ['on', '1', 'https', 'ssl', 'https, https'], true);
    }


and 

    protected function getHostName()
    {
        ...

        // Don't append port number if a normal port.
        if (($scheme == 'http' && $port == '80') || ($scheme == 'https' && $port == '443') || ($scheme == 'https' && $port == '80')) {
            $appendPort = '';
        }

        return $host . $appendPort;
    }

**Comment by karelsmetana** [comment]
Solved, not only updated sdk, but right callback url - I added there referer parameter, but it was problem for facebook. After removing this parameter, everything works.

**Comment by DavidConstantine88** [comment]
karelsmetana - what is considered a right callback url?
for example if my login is https://mydomain/login
and facebook login is https://mydomain/facebook-login

do I need to provide something else there?
lets assume I need only email permission...

**Comment by karelsmetana** [comment]
@DavidConstantine88 you have to enter callback url, where will be user redirected by facebook.

**Comment by jhoegsdal** [comment]
I had the same issue and it was to do with the Valid OAuth Redirect URIs. I had to add "/signin-facebook" for it to work. E.g. https://mydomain/signin-facebook

**Comment by yguedidi** [comment]
@ferreirabraga just upgrade to 5.6.2, it includes that fix ;)

**Comment by csimpi** [comment]
@Ivan-ShR thx it was a lifesaver 👍

**Comment by abdulghani200** [comment]
updating to 5.6.2 solved the problem :heart:

**Comment by ToxicTree** [comment]
updating to 5.6.2 solved the problem here too!

**Comment by ToxicTree** [comment]
cd into the dir and run composer require package_name:5.6.2

**Comment by Madhushanudeshike** [comment]
Graph returned an error: Can't load URL: The domain of this URL isn't included in the app's domains. To be able to load this URL, add all domains and sub-domains of your app to the App Domains field in your app settings.


`session_start();
require_once __DIR__ . '/Facebook/autoload.php';

$fb = new Facebook\Facebook([
  'app_id' => 'xxxxxxxx',
  'app_secret' => 'xxxxxxxxxxxxxxxxxxxx',
  'default_graph_version' => 'v2.6',
  "persistent_data_handler"=>"session"
  ]);


$helper = $fb->getRedirectLoginHelper();
try {
  $accessToken = $helper->getAccessToken();
} catch(Facebook\Exceptions\FacebookResponseException $e) {
  // When Graph returns an error
  echo 'Graph returned an error: ' . $e->getMessage();
  exit;
} catch(Facebook\Exceptions\FacebookSDKException $e) {
  // When validation fails or other local issues
  echo 'Facebook SDK returned an error: ' . $e->getMessage();
  exit;
}
`

**Comment by mithlesh425** [comment]
Please help, same issue!

**Comment by csimpi** [comment]
@mithlesh425 have you tried the update to  5.6.2? 
Are your settings okay in the APP's settings regarding the domain?

**Comment by mithlesh425** [comment]
@csimpi thanks, now it's solved by updating to new version.

**Comment by iamkarthick** [comment]
Solutions:

After along research, the problem got fixed.

Please use the PHP SDK 5.6.2. And edit the following files in the FacebookRedirectLoginHelper.

Edit in PHP SDK
Find file: facebook\graph-sdk\src\Facebook\Helpers\FacebookRedirectLoginHelper.php

Find word
$redirectUrl = FacebookUrlManipulator::removeParamsFromUrl($redirectUrl, ['state','code']);
Change to
$redirectUrl = FacebookUrlManipulator::removeParamsFromUrl($redirectUrl, ['state','code','enforce_https']);

**Comment by VadimIzmalkov** [comment]
iamkarthick's fix works for me

**Comment by harimayco** [comment]
@iamkarthick you saved my life. thank u

**Comment by DustinVII** [comment]
@iamkarthick Thanks !! It works!

**Comment by abdulghanitech** [comment]
@iamkarthick many thanks man! It helped a lot 👍

**Comment by xyfantis** [comment]
@iamkarthick fix works for me

**Comment by htdung83** [comment]
> Solutions:
> 
> After along research, the problem got fixed.
> 
> Please use the PHP SDK 5.6.2. And edit the following files in the FacebookRedirectLoginHelper.
> 
> Edit in PHP SDK
> Find file: facebook\graph-sdk\src\Facebook\Helpers\FacebookRedirectLoginHelper.php
> 
> Find word
> $redirectUrl = FacebookUrlManipulator::removeParamsFromUrl($redirectUrl, ['state','code']);
> Change to
> $redirectUrl = FacebookUrlManipulator::removeParamsFromUrl($redirectUrl, ['state','code','enforce_https']);

I am using Laravel 5.7.x. Do I have to downgrade to 5.6.2?

**Comment by Slymcode** [comment]
Thanks a whole lot... fix worked!

**Comment by arnoldandpearn** [comment]
@iamkarthick worked for me too SDK 5.6.3

**Comment by lahchimi** [comment]
fix works for me

**Comment by NadafG** [comment]
Hey,

> Can't load URL: The domain of this URL isn't included in the app's domains. To be able to load this URL, add all domains and sub-domains of your app to the App Domains field in your app settings.


- I have added all fields in an app 
- My app in a live mode 
- But when m calling from other domain then this issue occurs 
- if m call the same domain then not an issue.
- here is screenshot - https://take.ms/heByh

Please help me.
