### ISSUE TITLE
IMPORTANT Facebook Restriction

### ISSUE THREAD

**Issue by tolbon** [facebook/php-graph-sdk#966]
This message is for pure information, close if you want
Facebook restrict lot of fields on GraphAPI

https://newsroom.fb.com/news/2018/04/restricting-data-access/

@yguedidi

**Comment by yguedidi** [comment]
Thanks @tolbon! I'm aware of those changes :)
Restricting them doen't mean that they're removed, and if they're not removed, they should be accessible through the SDK ;)
