### ISSUE TITLE
videoToUpload returns empty on failure and not exception.

### ISSUE THREAD

**Issue by barkermn01** [facebook/php-graph-sdk#973]
## Test information
PHP-SDK Version: latest composer (`composer update` was run as part of debugging)
PHP Verison: 7.2-fpm
Web Server: Apache 2.

## Problem:

`$response = $fb->videoToUpload()` does not seem to be working correctly. it works when i upload an animated gif and i get an Id back and the video is added to my page.

However, I give it a path to a .mp4 file and I get an empty response no error triggered or Exception is thrown.

## Reproduction:
When connecting to a Facebook Page using a `page_access_token` and yes my app is verified for pages access.

### Smallest Reproducable code 
```
$this->connection = new \Facebook\Facebook([
	'app_id' => $this->app_id,
	'app_secret' => $this->app_Secret,
	'default_graph_version' => 'v2.10',
	'default_access_token' => $page_access_token
]);

$s3Path = $mediaPath = "https://s3-eu-west-1.amazonaws.com/---omited---/".$fileNameFromDatabase;
$data = array("path" => "videos", "file" => $this->getConnection()->videoToUpload($s3Path));
#DEBUGGING BELOW
error_log($output);
error_log("Sent Facebook url {$s3Path}");
error_log(json_encode($data));
# return 
return $data;
```

### Test Cases i have run 
`.mp4` file used.

```
[Tue Apr 10 16:16:08.101134 2018] [php7:notice] [pid 1752] [client 172.31.21.62:41649] Sent Facebook url https://s3-eu-west-1.amazonaws.com/---omited---, referer: http://localhost:3000/posts
[Tue Apr 10 16:16:08.101195 2018] [php7:notice] [pid 1752] [client 172.31.21.62:41649] {"path":"videos","file":{}}, referer: http://localhost:3000/posts
```

and `.gif` (just a note the debugging was not as advanced when using doing a gif only had it do `error_log(json_encode($data));`
```
[Tue Apr 10 16:13:36.047993 2018] [php7:notice] [pid 1926] [client 172.31.32.224:35919] stdClass Object\n(\n    [status] => success\n    [id] => 1771728942870999\n)\n, referer: http://localhost:3000/posts
```

## Other notes
While i was building this ticket after testing for about an hour I now get a complete failure to upload videos with an error when i try to upload a gif
```
[Tue Apr 10 16:48:06.596359 2018] [php7:notice] [pid 1918] [client 172.31.21.62:43493]{"path":"videos","file":null}, referer: http://localhost:3000/posts
[Tue Apr 10 16:48:07.187202 2018] [php7:notice] [pid 1918] [client 172.31.21.62:43493] stdClass Object\n(\n    [status] => failure\n    [error] => Array\n        (\n            [code] => 390\n            [message] => There was a problem uploading your video file. Please try again.\n            [connected] => 1\n        )\n\n)\n, referer: http://localhost:3000/posts
```

**Comment by yguedidi** [comment]
@barkermn01 thanks for your report! It looks like it's an issue in the Graph API as it returns an error, please check with Facebook support what is the error 390.
So I'm closing this.
