### ISSUE TITLE
Graph version v2.12

### ISSUE THREAD

**Issue by Plytas** [facebook/php-graph-sdk#974]
I see that for the stable version (5.5) default graph api version is still v2.10. Is there a reason it's not being updated to v2.12?
And also is it safe to just pass version v2.12 to Facebook constructor?

**Comment by litan1106** [comment]
you can pass the version (v2.12) into the Facebook constructor for now.

$fb = new \Facebook\Facebook([
  'app_id' => '{app-id}',
  'app_secret' => '{app-secret}',
  'default_graph_version' => 'v2.12',
  //'default_access_token' => '{access-token}', // optional
]);

**Comment by yguedidi** [comment]
Thanks @litan1106!
@Plytas the Graph version you use should always be passed to the constructor ;)
