### ISSUE TITLE
Please make sure your redirect_uri is identical to the one you used in the OAuth dialog request

### ISSUE THREAD

**Issue by deepulbit** [facebook/php-graph-sdk#980]
I have created an app and I use facebook login and signup using that on my website. Everything was working fine until last month. But now when I try to signup using facebook I am getting an error saying _Graph returned an error: Error validating verification code. Please make sure your redirect_uri is identical to the one you used in the OAuth dialog request_. I have added the redirect uris in app settings. But it doesn't help. Any help/suggestion is much appreciated.

This is the redirect url I am getting

https://www.facebook.com/v2.10/dialog/oauth?client_id=1234567890&state=55dc98ff67f37e99854ca2a58fb98fc2&response_type=code&sdk=php-sdk-5.0.0&redirect_uri=http%3A%2F%2Fwww.photowishlist.com%2Flogin%2Ffb_login_callback%2Fshopper&scope=email

and the below url is added to app redirect uri

http://www.photowishlist.com/login/fb_login_callback/shopper

**Comment by kergekacsa** [comment]
+1 for me, it's the same for me, I've checked over a hundred times...
Before the addition if the correct URL, I got the error message on facebook's page, but now it's on my domain, after I got forwarded back.

**Comment by yguedidi** [comment]
Thanks @kergekacsa!

**Comment by zackijack** [comment]
Hi @yguedidi , I got the same issue, and running composer update doesn't resolve this issue. the SDK I have had is the last stable version, 5.6.3.
I got this issue just today, before there were no problems.

**Comment by yguedidi** [comment]
@zackijack maybe a session issue? or maybe related to #1049?

**Comment by betulsenoglu** [comment]
Hi @deepulbit,
I know maybe its too late but I just wanted to comment. If you still having this issue, make sure that you have same FacebookCallBack method name everywhere. I mean, for instance I have an External Login function which returns ;

`https://www.facebook.com/dialog/oauth?client_id=" + FB_APP_ID + "&redirect_uri=" + System.Net.WebUtility.UrlEncode(pageUrl + "account/**FacebookLoginCallback**?returnUrl=%2F").Replace("%3F", "&") + "&scope=email&enforce_https=1;`

and also I have a FacebookLoginCallback method which has exactly the same name with I have above. ("account/FacebookLoginCallback?....")

```
[HttpGet("**FacebookLoginCallback**")]
public async Task<IActionResult> **FacebookLoginCallback**(string code, string returnUrl)
        {
            try
            {
                var myUrl = new Uri(HttpContext.Request.GetDisplayUrl()).GetLeftPart(UriPartial.Authority);
                var pageUrl = new UriBuilder(myUrl);
                var result = (IDictionary<string, object>)fb.Get("oauth/access_token", new
                {
                    client_id = FB_APP_ID,
                    client_secret = FB_APP_SECRET,
                    redirect_uri = pageUrl.Uri.AbsoluteUri.TrimEnd('/') + Url.Action("**FacebookLoginCallback**", "Account", new { returnUrl = returnUrl }),
                    code = code
                });
       }

......
}

```

Please double check your variable/function names if you have those in your url. 

Happy Coding

**Comment by mcanepa** [comment]
Still an error in 2021

**Comment by ve3** [comment]
This still error.
I have 2 language URL 
1. is https://domain/admin/fblogincallback
2. is https://domain/en-US/admin/fblogincallback
both URLs are added to **Valid OAuth Redirect URIs** with trailing slash and non-trailing slash.

The 1st URL works fine but 2nd contains error.
