### ISSUE TITLE
Graph returned an error: 无法加载网址: 这个 URL 的域名未包含应用的域名。为了能够加载 URL，请在应用设置的应用域名字段添加应用的所有域和子域。

### ISSUE THREAD

**Issue by kl521516** [facebook/php-graph-sdk#983]
login.php
`
if(!session_id()) {
    session_start();
}

require_once __DIR__ . '/vendor/autoload.php';

$facebook_appId = '123';
$facebook_appSecret = '123';

$fb = new Facebook\Facebook([
  'app_id' => $facebook_appId,
  'app_secret' => $facebook_appSecret,
  'default_graph_version' => 'v2.11',
]);

$helper = $fb->getRedirectLoginHelper();

$permissions = ['email']; // Optional permissions
$loginUrl = $helper->getLoginUrl('http://www.123.com/login-callback.php', $permissions);

echo '<a href="' . htmlspecialchars($loginUrl) . '">Login via Facebook!</a>';

`

login-callback.php
`
// error_reporting (E_ALL & ~E_NOTICE);

if(!session_id()) {
	session_start();
}

require_once __DIR__ . '/vendor/autoload.php';

$facebook_appId = '123';
$facebook_appSecret = '123';

$fb = new \Facebook\Facebook([
	'app_id' => $facebook_appId,
	'app_secret' => $facebook_appSecret,
	'default_graph_version' => 'v2.11',
]);

// Use one of the helper classes to get a Facebook\Authentication\AccessToken entity.
//   $helper = $fb->getRedirectLoginHelper();
//   $helper = $fb->getJavaScriptHelper();
//   $helper = $fb->getCanvasHelper();
//   $helper = $fb->getPageTabHelper();

try {
  // Get the \Facebook\GraphNodes\GraphUser object for the current user.
  // If you provided a 'default_access_token', the '{access-token}' is optional.

  $helper = $fb->getRedirectLoginHelper();  
  $accessToken = $helper->getAccessToken();
  $response = $fb->get('/me?fields=id,name', $accessToken );
  // $response = $fb->get('/me', $accessToken );

} 
catch(\Facebook\Exceptions\FacebookResponseException $e) {
  // When Graph returns an error
  echo 'Graph returned an error: ' . $e->getMessage();
  exit;
} 
catch(\Facebook\Exceptions\FacebookSDKException $e) {
  // When validation fails or other local issues
  echo 'Facebook SDK returned an error: ' . $e->getMessage();
  exit;
}

$me = $response->getGraphUser();
echo 'Logged in as ' . $me->getName();
`

When I click on the "login.php" output link, it jumps to the "login-callback.php" and prints the following error message. How do I solve this problem?

Graph returned an error: 无法加载网址: 这个 URL 的域名未包含应用的域名。为了能够加载 URL，请在应用设置的应用域名字段添加应用的所有域和子域。

**Comment by boanneu** [comment]
we have te same issue

**Comment by kl521516** [comment]
thanks for your feedback,but I have  added all domains and subdomains of our app to the "Application domains" field in our app settings,It still reports this error.

**Comment by boanneu** [comment]
what i have done is create canvas on Facebook, withe Facebook Web Games and so we get the session it self, and the basic user info

**Comment by yguedidi** [comment]
Thank you for posting your issue here!
But this repository is about the Graph API PHP SDK and reported issues must be related to it, like SDK code bugs, documentation mistakes or new feature suggestions.
For issues with Graph API itself, you can report a bug in the [Facebook issue tracker](https://developers.facebook.com/bugs/).
For help about how to use the SDK, [StackOverflow](https://stackoverflow.com) is a better place to get answers. Don't forget to tag your question with the [facebook-php-sdk](https://stackoverflow.com/questions/tagged/facebook-php-sdk) tag.
So I'm closing this, and hope to see you soon contributing to the SDK. :)
