### ISSUE TITLE
Latest release of php-graph-sdk uses defunct version of graph-sdk? (probably VERY easy to fix with a new 5.6.x release)

### ISSUE THREAD

**Issue by ryancwalsh** [facebook/php-graph-sdk#985]
We got emails today (on 2018-05-01) saying:

> Your app XXXXX currently accesses a version of the Marketing API prior to v2.11. We will be deprecating all versions prior to v2.11 on Tuesday, May 8, 2018. To ensure a smooth transition, please migrate all calls to Marketing API v2.11 or higher.

The only place in my code that I could find that might be accessing an earlier version is this `php-graph-sdk` (version 5.6.2), because it says `const DEFAULT_GRAPH_VERSION = 'v2.10';` (even though 5.6.2 is the latest release!).

**What happens if I just pass `null` as the version? Will that work fine? Does that tell your API to use the latest, or what?**

```
$fb = new \Facebook\Facebook([
   'app_id' => '{app-id}',
   'app_secret' => '{app-secret}',
   'default_graph_version' => null,
]);
```

I see Line 115 of a future release of this SDK that implies that null will be allowed (and maybe even will serve as the default):
https://github.com/facebook/php-graph-sdk/blob/dda97c2d82a17994325e321bc84e14ea579513f8/src/Facebook.php#L115

Thanks.

**Comment by Plytas** [comment]
I already asked this question on #974 . (I see you put a thumbs up there).

The answer I got is to put `'v2.12'` for `default_graph_version`.
```
$fb = new \Facebook\Facebook([
   'app_id' => '{app-id}',
   'app_secret' => '{app-secret}',
   'default_graph_version' => 'v2.12',
]);
```

**Comment by yguedidi** [comment]
Thanks @Plytas!
@ryancwalsh you should always pass a fixed version of the Graph API

**Comment by ryancwalsh** [comment]
@yguedidi and @Plytas I'm confused that the "Usage" section of the docs at https://github.com/facebook/php-graph-sdk still say `'default_graph_version' => 'v2.10'`.

Isn't that version not supported anymore?

**How / where would I find what the number is of the newest version (which I assume I should be using)?**

Thanks.

**Comment by ryancwalsh** [comment]
Ahh, I bet https://developers.facebook.com/docs/graph-api/changelog/ is the official place to find it, and it looks like v2.10 will still be supported a little while longer (and maybe is the oldest supported version) while v4.0 is newest.
