### ISSUE TITLE
Multiple uncaught errors with Facebook login

### ISSUE THREAD

**Issue by danielcoates** [facebook/php-graph-sdk#989]
Following the [`facebook-login.md`](https://github.com/facebook/php-graph-sdk/blob/5.x/docs/examples/facebook_login.md) example that is provided in this SDK leads to two uncaught errors.

![xdebug screen shot](https://user-images.githubusercontent.com/19962341/39820065-d56e6112-539c-11e8-8cdb-4f846a61a291.png)

This seems to stem from not sending the App Domain with the `$accessToken = $helper->getAccessToken();` request on line `8` of the example [`fb-callback.php`](https://github.com/facebook/php-graph-sdk/blob/5.x/docs/examples/facebook_login.md) script.

Changing this to `$accessToken = $helper->getAccessToken({app-domain});` results in the script executing correctly.

I don't know if this is a bug, or a change that you made with all the recent changes.

**Comment by danielcoates** [comment]
@yguedidi, did you even read the issue?  This is a report on a bug/error in the documentation.

I even included what I did that made it work, after spending 4 hours on stack exchange and google.

**Comment by yguedidi** [comment]
@danielcoates You're right! I'm currently cleaning up the issues of the repo, and I must admit I was too fast on this one, when I saw "Can't load URL: The domain of this URL...". My bad!
Regarding your issue, passing the redirect URL is not mandatory, by default the SDK will set the current one as the redirect URL.
But you're right there may be a lack in documentation... Would you like to open a pull request? :)
