### ISSUE TITLE
FB RedirectLoginHelper object is missing information

### ISSUE THREAD

**Issue by cjluzius** [facebook/php-graph-sdk#997]
FB RedirectLoginHelper object is missing information for some users causing a NULL session.

PHP SDK 5.0

$helper = new FacebookCanvasLoginHelper();
$session = $helper->getSession();

I did a var_dump of the $helper for users who are working vs those that are failing. and theirs a huge difference between users that gain access and users that fail with the following differences.

- Raw Signed Request is much shorter (188 characters vs 546)
- no [expires] property
- no [oauth] property
- no [user_id] property

Any ideas why the $helper would fail for some users but work for others?

**Comment by yguedidi** [comment]
@cjluzius looks like not an SDK issue. You should dump the parsed signed request, it may contain an error message. Please then use StackOverflow for support, thanks
